## One location for the blat of all genomic sequences in design (regions + references)

In [1]:
import pandas as pd 
import yaml 

# import local module helpful functions as hf (/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/00_helpful_functions/helpful_functions.py)
import sys
sys.path.append("/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/00_helpful_functions")
import helpful_functions as hf

# # reload helpful_functions module
# import importlib
# importlib.reload(hf)


config_path = "/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/global80K_config.yaml"
config_path = "../../global80K_config.yaml"
# config_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/global80K_config.yaml"
# load config file
with open(config_path, "r") as f:
    config = yaml.load(f, Loader=yaml.FullLoader)

In [2]:
# load design file
designd_sequences = hf.fasta_to_dataframe(config['files']['final_design']['design_fasta'])

### blat results from tested elements and sequences
- input for blat: /data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/05_variant_region_list/tested_ref_and_elements_finished.fasta (all tested sequences (regions and references))

In [ ]:
# bash commands to generate a tsv out of the psl file
# tail -n +6 blat_matched_file.psl > blat_result_without_header.tsv
file = '/data/cephfs-2/unmirrored/groups/ag-kircher/MPRA/kilian_projects/hg38/ncbi_dataset/data/GCF_000001405.26/blat_result_without_header.tsv'
# remove header

blat_result_df = pd.read_csv(file, sep='\t', header=None)

# add column names
blat_result_columns = ['match', 'mismatch', 'rep_match', 'Ns', 'Q_gap_count', 'Q_gap_bases', 'T_gap_count', 'T_gap_bases', 'strand', 'Q_name', 'Q_size', 'Q_start', 'Q_end', 'T_name', 'T_size', 'T_start', 'T_end', 'block_count', 'blockSizes', 'qStarts', 'tStarts']

blat_result_df.columns = blat_result_columns

blat_result_df
# filter: number of matches=270, 
perfect_matches = blat_result_df[blat_result_df['match'] == 270]
perfect_matches.shape # 28276
# filter for blockSizes = 270
perfect_matches = perfect_matches[perfect_matches['blockSizes'] == '270,']
perfect_matches.shape # 28236
# check all columns for unique values and did not find any suspecious values
perfect_matches.T_name.value_counts() # 0 
# filter for matches startwith "NC_" in T_name
perfect_matches = perfect_matches[perfect_matches['T_name'].str.startswith('NC_')]
perfect_matches.shape # 27482
perfect_matches.Q_name.nunique() # 27482

# get subset of interesting columns
interesting_blat_results = ['Q_name', 'match', 'strand', 'T_name', 'T_start', 'T_end']
interesting_blat_results

perfect_matches = perfect_matches[interesting_blat_results]
perfect_matches

### Blat for intersting neuro controls
- /data/cephfs-2/unmirrored/groups/ag-kircher/MPRA/kilian_projects/hg38/ncbi_dataset/data/GCF_000001405.26/blat_interesting_neuro_controls_matched.tsv

In [3]:
path_to_blat_results = '/data/cephfs-2/unmirrored/groups/ag-kircher/MPRA/kilian_projects/hg38/ncbi_dataset/data/GCF_000001405.26/blat_interesting_neuro_controls_matched.tsv'
header_names = ['match', 'mismatch', 'rep_match', 'Ns', 'Q_gap_count', 'Q_gap_bases', 'T_gap_count', 'T_gap_bases', 'strand', 'Q_name', 'Q_size', 'Q_start', 'Q_end', 'T_name', 'T_size', 'T_start', 'T_end', 'block_count', 'blockSizes', 'qStarts', 'tStarts']
blat_results = pd.read_csv(path_to_blat_results, sep="\t", header=None)
blat_results.columns = header_names
blat_results

# filter: number of matches=270, 
perfect_matches = blat_results[blat_results['match'] == 270]
perfect_matches.shape # 519
# filter for blockSizes = 270
perfect_matches = perfect_matches[perfect_matches['blockSizes'] == '270,']
perfect_matches.shape # 519
# # check all columns for unique values and did not find any suspecious values
# perfect_matches.T_name.value_counts() # 0 
# filter for matches startwith "NC_" in T_name
perfect_matches = perfect_matches[perfect_matches['T_name'].str.startswith('NC_')]
perfect_matches.shape # 500
perfect_matches.Q_name.nunique() # 498 

# get subset of interesting columns
interesting_blat_results = ['Q_name', 'match', 'strand', 'T_name', 'T_start', 'T_end']
interesting_blat_results

perfect_matches = perfect_matches[interesting_blat_results]
perfect_matches

,Q_name,match,strand,T_name,T_start,T_end
0,C_negative_neuron_MK:tile_14444_chr15_67066278...,270,+,NC_000015.10,67066277,67066547
1,C_negative_neuron_MK:tile_9599_chr12_65742272_...,270,+,NC_000012.12,65742271,65742541
2,C_negative_neuron_MK:tile_9256_chr12_26114182_...,270,+,NC_000012.12,26114181,26114451
3,C_negative_neuron_MK:tile_44145_chr8_80578146_...,270,+,NC_000008.11,80578145,80578415
6,C_negative_neuron_MK:tile_33520_chr5_77645003_...,270,+,NC_000005.10,77645002,77645272
...,...,...,...,...,...,...
4122,C_positive_neuron_NP:GW18_PFC_ABC_chr12_121536...,270,+,NC_000012.12,121536100,121536370
4123,C_positive_neuron_NP:NGN2_iPSC_ABC_chr4_850290...,270,+,NC_000004.12,85029018,85029288
4124,C_positive_neuron_NP:GW18_PFC_ABC_NGN2_iPSC_AB...,270,+,NC_000004.12,781750,782020
4125,C_positive_neuron_NP:Fetal_Cerebrum_Cicero_GW1...,270,+,NC_000001.11,110538278,110538548
4127,C_positive_neuron_NP:GW18_PFC_ABC_chr1_1690485...,270,+,NC_000001.11,16904850,16905120

In [5]:
# check which are in the input fasta but not cannot be matched and check if you can find the sequence in the ucsc
input_fasta_intersting_controls_path = '/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/05_variant_region_list/results/control_sequences/blat_interesting_neuro_controls.fa'
input_fasta_intersting_controls = hf.fasta_to_dataframe(input_fasta_intersting_controls_path)
input_header_set = set(input_fasta_intersting_controls['header'].to_list())
matched_sequences_set = set(perfect_matches['Q_name'].to_list())

#

In [7]:
not_matchable_blat = input_header_set - matched_sequences_set
print(len(not_matchable_blat))
not_matchable_blat
# checked C_negative_neuron_MK:rdhs_350036_chr2_60214636_60214905_A_T_69__0.281429052959334

224

{'C_negative_neuron_MK:rdhs_350036_chr2_60214636_60214905_A_T_69__0.281429052959334',
 'C_negative_neuron_MK:rdhs_350036_chr2_60214636_60214905_C_G_257__0.366970377196711',
 'C_negative_neuron_MK:rdhs_459624_chr3_79178526_79178795_A_T_9__0.307547494437252',
 'C_negative_neuron_MK:rdhs_459624_chr3_79178526_79178795_C_G_253__0.359488132581695',
 'C_negative_neuron_MK:rdhs_581339_chr6_14500893_14501162_A_T_253__0.361955206804656',
 'C_negative_neuron_MK:rdhs_681310_chr8_76841456_76841725_T_A_141__0.3306686502775',
 'C_negative_neuron_MK:tile_10786_chr13_71759785_71760054_C_G_181__0.32568038614907',
 'C_negative_neuron_MK:tile_10789_chr13_71760386_71760655_C_G_193__0.288427385780119',
 'C_negative_neuron_MK:tile_11200_chr13_105364096_105364365_A_T_201__0.290852855921551',
 'C_negative_neuron_MK:tile_11200_chr13_105364096_105364365_T_A_13__0.27122115537836',
 'C_negative_neuron_MK:tile_13042_chr14_103542966_103543235_G_C_129__0.385465789555967',
 'C_negative_neuron_MK:tile_13042_chr14_103542966_103543235_T_A_89__0.286552521521648',
 'C_negative_neuron_MK:tile_15711_chr16_49060720_49060989_C_G_263__0.273126846867878',
 'C_negative_neuron_MK:tile_1898_chr1_87560611_87560880_A_T_221__0.311677031223304',
 'C_negative_neuron_MK:tile_1898_chr1_87560611_87560880_G_C_21__0.36630504090172',
 'C_negative_neuron_MK:tile_1898_chr1_87560611_87560880_T_A_49__0.272078444421042',
 'C_negative_neuron_MK:tile_1898_chr1_87560611_87560880_T_A_93__0.292520553163671',
 'C_negative_neuron_MK:tile_19302_chr18_44826594_44826863_C_G_101__0.271605364151252',
 'C_negative_neuron_MK:tile_1996_chr1_88462143_88462412_G_C_201__0.299237434732552',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_C_73__0.371450118599892',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_C_91__0.458438635540335',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_G_15__0.286363572028671',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_G_207__0.460952850283534',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_G_83__0.309718648887639',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_T_123__0.503924964163125',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_T_153__0.324926938410187',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_T_181__0.613378112568899',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_T_185__0.567370235060652',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_T_217__0.589327998488527',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_A_T_37__0.51268771807735',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_C_G_109__0.291710820755985',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_C_G_141__0.295047642441601',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_C_G_161__0.742187250156855',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_C_G_17__0.548252163426475',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_C_G_257__0.480076732238992',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_G_C_156__0.30169653579154',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_G_C_19__0.435763634709985',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_G_C_241__0.27823374980502',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_G_C_250__0.46468849450411',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_G_T_186__0.299549745430785',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_G_T_196__0.363530522250441',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_G_T_20__0.569820613655987',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_T_A_201__0.327242190951764',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_T_A_249__0.416448886155984',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_T_A_261__0.482263420426159',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_T_A_29__0.277408189156603',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_T_A_89__0.530375626775895',
 'C_negative_neuron_MK:tile_1997_chr1_88462325_88462594_hs327A2__0.412831211438912',
 'C_negative_neuron_MK:tile_1999_chr1_88462556_88462825_A_G_23__0.876434621875319',
 'C_negative_neuron_MK:tile_1999_chr1_88462556_88462825_A_T_2__0.94196907866527',
 'C_negative_neuron_MK:tile_1999_chr1_88462556_88462825_G_C_19__0.955831785228529',
 'C_negative_neuron_MK:tile_22146_chr2_72898113_72898382_C_G_33__0.320814462166541',
 'C_negative_neuron_MK:tile_22146_chr2_72898113_72898382_T_A_73__0.429424156591446',
 'C_negative_neuron_MK:tile_22397_chr2_103176684_103176953_A_T_257__0.418330976255658',
 'C_negative_neuron_MK:tile_22397_chr2_103176684_103176953_C_G_193__0.404478633869283',
 'C_negative_neuron_MK:tile_22397_chr2_103176684_103176953_T_A_129__0.330794099790811',
 'C_negative_neuron_MK:tile_22418_chr2_103401978_103402247_A_T_233__0.288282127322364',
 'C_negative_neuron_MK:tile_22418_chr2_103401978_103402247_C_G_29__0.274420051532681',
 'C_negative_neuron_MK:tile_28727_chr3_79178601_79178870_A_T_245__0.390287888410175',
 'C_negative_neuron_MK:tile_28727_chr3_79178601_79178870_T_A_173__0.313972378751707',
 'C_negative_neuron_MK:tile_28727_chr3_79178601_79178870_T_A_201__0.381433685705068',
 'C_negative_neuron_MK:tile_28728_chr3_79178837_79179106_G_C_133__0.270705257259097',
 'C_negative_neuron_MK:tile_30691_chr3_194212256_194212525_A_T_109__0.283215646927479',
 'C_negative_neuron_MK:tile_30691_chr3_194212256_194212525_C_G_189__0.316979551586783',
 'C_negative_neuron_MK:tile_30691_chr3_194212256_194212525_T_A_105__0.278110155806714',
 'C_negative_neuron_MK:tile_30691_chr3_194212256_194212525_T_A_233__0.270469367094904',
 'C_negative_neuron_MK:tile_31775_chr4_112403206_112403475_A_T_69__0.326076195377385',
 'C_negative_neuron_MK:tile_31790_chr4_112521555_112521824_A_T_109__0.412699919125482',
 'C_negative_neuron_MK:tile_31790_chr4_112521555_112521824_G_C_1__0.331678594587159',
 'C_negative_neuron_MK:tile_31790_chr4_112521555_112521824_T_A_113__0.27649150257248',
 'C_negative_neuron_MK:tile_31901_chr4_125519633_125519902_A_T_129__0.293993468689244',
 'C_negative_neuron_MK:tile_33675_chr5_87787823_87788092_G_C_77__0.413576586415791',
 'C_negative_neuron_MK:tile_33677_chr5_87788242_87788511_A_T_57__0.319310204136462',
 'C_negative_neuron_MK:tile_33677_chr5_87788242_87788511_G_C_73__0.308598731714052',
 'C_negative_neuron_MK:tile_33726_chr5_88396602_88396871_C_G_37__0.364212635182057',
 'C_negative_neuron_MK:tile_33739_chr5_88544835_88545104_G_C_225__0.289618660678557',
 'C_negative_neuron_MK:tile_33739_chr5_88544835_88545104_T_A_269__0.275089109857028',
 'C_negative_neuron_MK:tile_34429_chr5_125317175_125317444_T_A_133__0.327935403368665',
 'C_negative_neuron_MK:tile_34429_chr5_125317175_125317444_T_A_213__0.448639517315185',
 'C_negative_neuron_MK:tile_36043_chr6_14500968_14501237_A_T_109__0.399453963254672',
 'C_negative_neuron_MK:tile_36043_chr6_14500968_14501237_G_C_197__0.2986487319304',
 'C_negative_neuron_MK:tile_36043_chr6_14500968_14501237_G_C_261__0.274168942409752',
 'C_negative_neuron_MK:tile_36043_chr6_14500968_14501237_G_C_73__0.345323615192071',
 'C_negative_neuron_MK:tile_37242_chr6_97306494_97306763_A_T_141__0.387284334317795',
 'C_negative_neuron_MK:tile_38403_chr7_1226413_1226682_G_T_42__0.383795925558626',
 'C_negative_neuron_MK:tile_38662_chr7_20964368_20964637_A_C_48__0.278802254110125',
 'C_negative_neuron_MK:tile_38662_chr7_20964368_20964637_G_C_225__0.284038287890459',
 'C_negative_neuron_MK:tile_38662_chr7_20964368_20964637_T_A_141__0.281617456059186',
 'C_negative_neuron_MK:tile_38662_chr7_20964368_20964637_T_A_205__0.310333272290411',
 'C_negative_neuron_MK:tile_38662_chr7_20964368_20964637_T_A_45__0.273178656080785',
 'C_negative_neuron_MK:tile_40116_chr7_42152982_42153251_T_A_161__0.317350305984148',
 'C_negative_neuron_MK:tile_41677_chr7_70132447_70132716_A_T_69__0.290570377281993',
 'C_negative_neuron_MK:tile_41677_chr7_70132447_70132716_C_G_161__0.371161949818312',
 'C_negative_neuron_MK:tile_43391_chr8_28513838_28514107_T_A_9__0.311074994247958',
 'C_negative_neuron_MK:tile_44055_chr8_77130565_77130834_A_T_265__0.271223695729321',
 'C_negative_neuron_MK:tile_44055_chr8_77130565_77130834_C_G_193__0.283719484450166',
 'C_negative_neuron_MK:tile_44055_chr8_77130565_77130834_C_G_221__0.272981222943062',
 'C_negative_neuron_MK:tile_44055_chr8_77130565_77130834_C_G_85__0.291302792539924',
 'C_negative_neuron_MK:tile_44058_chr8_77131243_77131512_T_A_85__0.318706168632168',
 'C_negative_neuron_MK:tile_45646_chr9_78440240_78440509_G_C_133__0.284040757539017',
 'C_negative_neuron_MK:tile_45784_chr9_81112997_81113266_A_T_17__0.312337766730427',
 'C_negative_neuron_MK:tile_47223_chrX_24990440_24990709_A_C_79__0.356960712587706',
 'C_negative_neuron_MK:tile_47223_chrX_24990440_24990709_A_G_205__0.307325345316911',
 'C_negative_neuron_MK:tile_47223_chrX_24990440_24990709_A_G_75__0.281711043909743',
 'C_negative_neuron_MK:tile_47231_chrX_24999634_24999903_T_C_31__0.301378589165095',
 'C_negative_neuron_MK:tile_9231_chr12_24081372_24081641_C_G_69__0.292511935594091',
 'C_negative_neuron_MK:tile_9231_chr12_24081372_24081641_G_C_133__0.475828585711215',
 'C_negative_neuron_MK:tile_9231_chr12_24081372_24081641_T_A_73__0.299621261273752',
 'C_positive_neuron_CD:n1_rs2279982_G_A_alt_50::chr2:164841902-164842172-mean_ratio2.16',
 'C_positive_neuron_CD:n1_rs275835_G_A_alt_50::chr7:132509137-132509407-mean_ratio2.11',
 'C_positive_neuron_CD:n1_rs7214382_G_C_alt_50::chr17:33292592-33292862-mean_ratio1.83',
 'C_positive_neuron_CD:p1_rs10971392_T_C_alt_50_T::chr9:33083775-33084045-mean_ratio1.9',
 'C_positive_neuron_CD:p1_rs115202710_C_T_alt_50_C::chr6:24704205-24704475-mean_ratio2.05',
 'C_positive_neuron_CD:p1_rs1159310_C_G_alt_50_C::chr9:114389124-114389394-mean_ratio2.02',
 'C_positive_neuron_CD:p1_rs11913731_A_G_alt_50_G::chr22:37859057-37859327-mean_ratio1.83',
 'C_positive_neuron_CD:p1_rs12411493_A_G_alt_50_A::chr10:79335890-79336160-mean_ratio1.85',
 'C_positive_neuron_CD:p1_rs154568_G_C_alt_50_C::chr5:90558496-90558766-mean_ratio1.85',
 'C_positive_neuron_CD:p1_rs17175954_C_T_alt_50_T::chr8:38422216-38422486-mean_ratio1.89',
 'C_positive_neuron_CD:p1_rs1763596_C_T_alt_50_C::chr1:16017205-16017475-mean_ratio1.83',
 'C_positive_neuron_CD:p1_rs17653_G_A_alt_50_G::chr19:46838102-46838372-mean_ratio1.9',
 'C_positive_neuron_CD:p1_rs2224873_T_A_alt_50_T::chr1:197676184-197676454-mean_ratio1.85',
 'C_positive_neuron_CD:p1_rs2529627_C_T_alt_50_C::chr17:14196616-14196886-mean_ratio1.89',
 'C_positive_neuron_CD:p1_rs28365157_C_T_alt_50_T::chr17:4715661-4715931-mean_ratio1.85',
 'C_positive_neuron_CD:p1_rs34241773_C_T_alt_50_C::chr1:2446472-2446742-mean_ratio1.9',
 'C_positive_neuron_CD:p1_rs34761481_G_A_alt_50_G::chr7:129161739-129162009-mean_ratio2.14',
 'C_positive_neuron_CD:p1_rs35341445_T_C_alt_50_T::chr16:1458852-1459122-mean_ratio1.85',
 'C_positive_neuron_CD:p1_rs55985730_T_G_alt_50_T::chr7:128776855-128777125-mean_ratio2.34',
 'C_positive_neuron_CD:p1_rs5771096_T_C_alt_50_T::chr22:50199938-50200208-mean_ratio1.87',
 'C_positive_neuron_CD:p1_rs584415_A_G_alt_50_A::chr5:178613192-178613462-mean_ratio2.04',
 'C_positive_neuron_CD:p1_rs60027384_T_C_alt_50_C::chr21:44339337-44339607-mean_ratio1.88',
 'C_positive_neuron_CD:p1_rs606742_A_G_alt_50_G::chr6:73604699-73604969-mean_ratio1.88',
 'C_positive_neuron_CD:p1_rs61828645_G_A_alt_50_G::chr1:174375920-174376190-mean_ratio1.86',
 'C_positive_neuron_CD:p1_rs61901488_A_T_alt_50_T::chr11:117861140-117861410-mean_ratio1.85',
 'C_positive_neuron_CD:p1_rs62028868_C_A_alt_50_C::chr15:75699375-75699645-mean_ratio1.93',
 'C_positive_neuron_CD:p1_rs62086577_G_A_alt_50_G::chr17:76540878-76541148-mean_ratio2.05',
 'C_positive_neuron_CD:p1_rs6798807_C_T_alt_50_C::chr3:14130440-14130710-mean_ratio1.85',
 'C_positive_neuron_CD:p1_rs7072579_T_G_alt_50_T::chr10:98036206-98036476-mean_ratio2.0',
 'C_positive_neuron_CD:p1_rs7107603_T_C_alt_50_T::chr11:90225342-90225612-mean_ratio1.92',
 'C_positive_neuron_CD:p1_rs7115714_G_A_alt_50_A::chr11:120424017-120424287-mean_ratio2.13',
 'C_positive_neuron_CD:p1_rs7156717_A_G_alt_50_A::chr14:49738920-49739190-mean_ratio1.88',
 'C_positive_neuron_CD:p1_rs76990668_T_C_alt_50_T::chr19:55207192-55207462-mean_ratio1.86',
 'C_positive_neuron_CD:p1_rs7794324_T_C_alt_50_C::chr7:38171772-38172042-mean_ratio1.86',
 'C_positive_neuron_CD:p1_rs923347_G_A_alt_50_A::chr11:68265036-68265306-mean_ratio1.85',
 'C_positive_neuron_CD:p1_rs9931091_G_T_alt_50_G::chr16:1433404-1433674-mean_ratio1.83',
 'C_positive_neuron_CD:p1_rs9975055_T_G_alt_50_G::chr21:44929969-44930239-mean_ratio2.18',
 'C_positive_neuron_CD:p2_rs7582466_A_G_alt_75_A::chr2:68162901-68163171-mean_ratio1.85',
 'C_positive_neuron_MK:tile_10789_chr13_71760386_71760655_A_T_33_0.664263211913968',
 'C_positive_neuron_MK:tile_13541_chr15_57133321_57133590_A_T_157_0.515579075860904',
 'C_positive_neuron_MK:tile_13541_chr15_57133321_57133590_A_T_221_0.524015982555253',
 'C_positive_neuron_MK:tile_13541_chr15_57133321_57133590_G_C_181_0.519955347108908',
 'C_positive_neuron_MK:tile_13541_chr15_57133321_57133590_G_C_253_0.504839395322824',
 'C_positive_neuron_MK:tile_13541_chr15_57133321_57133590_G_C_81_0.552358413966575',
 'C_positive_neuron_MK:tile_13541_chr15_57133321_57133590_T_A_145_0.549912600382367',
 'C_positive_neuron_MK:tile_13542_chr15_57133361_57133630_A_T_181_0.522651501113252',
 'C_positive_neuron_MK:tile_13542_chr15_57133361_57133630_G_C_249_0.564933294947607',
 'C_positive_neuron_MK:tile_13542_chr15_57133361_57133630_G_C_37_0.510700935595109',
 'C_positive_neuron_MK:tile_13542_chr15_57133361_57133630_G_C_41_0.562657187862888',
 'C_positive_neuron_MK:tile_13542_chr15_57133361_57133630_G_C_93_0.514745361376944',
 'C_positive_neuron_MK:tile_1997_chr1_88462325_88462594_G_A_35_0.540490750010783',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_109_0.576133496880657',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_117_0.568550488323686',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_121_0.649630048711471',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_153_0.704310315650298',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_181_0.51430437557178',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_1_0.562204129450572',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_217_0.584378973128977',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_249_0.520999727435436',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_37_0.591581855782454',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_45_0.580305705162065',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_53_0.550378823642343',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_57_0.595467686503805',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_77_0.561946291287962',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_A_T_93_0.591901720681984',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_105_0.588351825790094',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_133_0.601927394738928',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_157_0.527979095181779',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_165_0.621832378953701',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_177_0.547864271014139',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_193_0.563001519694954',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_213_0.606042794887001',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_253_0.514770476762862',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_29_0.51644449893917',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_33_0.589713990660527',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_49_0.535273408793379',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_65_0.562089245266142',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_69_0.560964774172212',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_73_0.596972780608526',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_81_0.541081922932932',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_C_G_85_0.592797090405334',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_101_0.526686827384914',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_125_0.554058505399564',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_149_0.545319725007704',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_161_0.552272307083099',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_173_0.530128663613834',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_185_0.524290092365292',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_189_0.581711719216663',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_197_0.538264003175463',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_201_0.567058188521964',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_229_0.564894210503252',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_233_0.575747924842928',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_237_0.583683647286775',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_269_0.550310056665328',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_61_0.58710627527132',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_89_0.560301537944007',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_G_C_97_0.557107546169056',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_113_0.52122729238276',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_129_0.587651886963826',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_137_0.55323323728102',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_13_0.56278024959106',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_17_0.551902569298178',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_221_0.593721763028585',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_245_0.515388041495509',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_257_0.552315448275341',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_25_0.562271670273117',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_41_0.535380998297195',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_5_0.582178750166717',
 'C_positive_neuron_MK:tile_34824_chr5_141041068_141041337_T_A_9_0.551831501239983',
 'C_positive_neuron_MK:tile_37243_chr6_97306567_97306836_A_T_149_0.750659896963247',
 'C_positive_neuron_MK:tile_37243_chr6_97306567_97306836_A_T_225_0.536289765272405',
 'C_positive_neuron_MK:tile_37243_chr6_97306567_97306836_G_C_245_0.578264941971671',
 'C_positive_neuron_MK:tile_37243_chr6_97306567_97306836_T_A_181_0.561176244891747',
 'C_positive_neuron_MK:tile_38236_chr6_162856883_162857152_T_A_161_0.524291536449335',
 'C_positive_neuron_MK:tile_38236_chr6_162856883_162857152_T_A_189_0.55613625946892',
 'C_positive_neuron_MK:tile_41677_chr7_70132447_70132716_C_G_253_0.550257939716087'}

### Blat for control variants (tried to do all REF sequences)
- problem: only 309 perfekt matches
- what is the expected number of sequences in the control we want a region for? ~ 6K
- make new blat investigation with new headers

In [ ]:
# input for the controls: (should be all the ref and regions from the variant control set)
input_fasta = '/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/05_variant_region_list/results/control_sequences/control_variant_reference_sequence.fasta'

In [8]:
# load blat results and check if only one perfect match of each sequence
header_names = ['match', 'mismatch', 'rep_match', 'Ns', 'Q_gap_count', 'Q_gap_bases', 'T_gap_count', 'T_gap_bases', 'strand', 'Q_name', 'Q_size', 'Q_start', 'Q_end', 'T_name', 'T_size', 'T_start', 'T_end', 'block_count', 'blockSizes', 'qStarts', 'tStarts']
path_to_blat_results = '/data/cephfs-2/unmirrored/groups/ag-kircher/MPRA/kilian_projects/hg38/ncbi_dataset/data/GCF_000001405.26/blat_variant_control_sequences_matched_file.tsv'
blat_results = pd.read_csv(path_to_blat_results, sep="\t", header=None)
blat_results.columns = header_names
blat_results

# filter: number of matches=270, 
perfect_matches = blat_results[blat_results['match'] == 270]
perfect_matches.shape # 314
# filter for blockSizes = 270
perfect_matches = perfect_matches[perfect_matches['blockSizes'] == '270,']
perfect_matches.shape # 311
# check all columns for unique values and did not find any suspecious values
perfect_matches.T_name.value_counts() # 0 
# filter for matches startwith "NC_" in T_name
perfect_matches = perfect_matches[perfect_matches['T_name'].str.startswith('NC_')]
perfect_matches.shape # 309
perfect_matches.Q_name.nunique() # 309

# get subset of interesting columns
interesting_blat_results = ['Q_name', 'match', 'strand', 'T_name', 'T_start', 'T_end']
interesting_blat_results

perfect_matches = perfect_matches[interesting_blat_results]
perfect_matches

,Q_name,match,strand,T_name,T_start,T_end
0,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...,270,+,NC_000001.11,154813248,154813518
1,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...,270,+,NC_000001.11,154839744,154840014
2,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...,270,+,NC_000001.11,154840018,154840288
3,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...,270,+,NC_000001.11,154840331,154840601
4,GC_Atrial_fib:REF_rs1218584|KCNN3|STARR-seq-AF...,270,+,NC_000001.11,154860467,154860737
...,...,...,...,...,...,...
5563,C_positive_heart_CAD:REF_rs7865618,270,+,NC_000009.12,22030870,22031140
5939,C_positive_heart_CAD:REF_rs4977757,270,+,NC_000009.12,22094195,22094465
6625,C_positive_heart_CAD:REF_rs1537373,270,+,NC_000009.12,22103206,22103476
6626,C_positive_heart_CAD:REF_rs10811656,270,+,NC_000009.12,22124337,22124607
6627,C_positive_heart_CAD:REF_rs507666,270,+,NC_000009.12,133273847,133274117

In [11]:
perfect_matches['labels'] = perfect_matches['Q_name'].apply(hf.get_label)

In [10]:
labels.value_counts()

Q_name
GC_Selvarajan            165
C_positive_heart_CAD      48
GC_Mendelian_variants     46
GC_Atrial_fib             21
GC_Mohlke                 16
GC_Liang                   8
GC_Kircher                 5
Name: count, dtype: int64

In [12]:
perfect_matches[perfect_matches['labels'] == 'GC_Selvarajan']

,Q_name,match,strand,T_name,T_start,T_end,labels
218,GC_Selvarajan:REF_rs9660819|STARR-seq-HepG2~rs...,270,+,NC_000001.11,3036131,3036401,GC_Selvarajan
219,GC_Selvarajan:REF_rs2993510|STARR-seq-HepG2~rs...,270,+,NC_000001.11,3039882,3040152,GC_Selvarajan
220,GC_Selvarajan:REF_rs2993510|STARR-seq-HepG2~rs...,270,+,NC_000001.11,3039924,3040194,GC_Selvarajan
221,GC_Selvarajan:REF_rs2993510|STARR-seq-HepG2~rs...,270,+,NC_000001.11,3039966,3040236,GC_Selvarajan
222,GC_Selvarajan:REF_rs2493288|STARR-seq-HepG2_fw...,270,+,NC_000001.11,3414235,3414505,GC_Selvarajan
...,...,...,...,...,...,...,...
5143,GC_Selvarajan:REF_rs10121140|STARR-seq-HepG2~r...,270,+,NC_000009.12,14292520,14292790,GC_Selvarajan
5144,GC_Selvarajan:REF_rs10121140|STARR-seq-HepG2~r...,270,+,NC_000009.12,14292585,14292855,GC_Selvarajan
5145,GC_Selvarajan:REF_rs6475604|STARR-seq-HepG2_fw...,270,+,NC_000009.12,22052630,22052900,GC_Selvarajan
5146,GC_Selvarajan:REF_rs1333045|STARR-seq-HepG2_fw...,270,+,NC_000009.12,22119060,22119330,GC_Selvarajan
5147,GC_Selvarajan:REF_rs2297400|STARR-seq-HepG2_fw...,270,+,NC_000009.12,104837064,104837334,GC_Selvarajan