## preprocessing results are investigated here

In [3]:
import pandas as pd

In [4]:
## final output (counts and sequences)
# /data/gpfs-1/users/kisa11_c/work/coding/MPRA/IGVF_Y1_design/projects/bc_tradeoff/NGN2_counts_sequences.tsv.gz
counts_sequences = '/data/gpfs-1/users/kisa11_c/work/coding/MPRA/IGVF_Y1_design/projects/bc_tradeoff/NGN2_counts_sequences.tsv.gz'

counts_sequences_df = pd.read_csv(counts_sequences, sep='\t', header=None)
counts_sequences_df.columns = ["variant_id", "allele", "barcode", "DNA1", "RNA1", "DNA2", "RNA2", "DNA3", "RNA3"]
counts_sequences_df

,variant_id,allele,barcode,DNA1,RNA1,DNA2,RNA2,DNA3,RNA3
0,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,ACCAGGCGCATGCGC,1,1,1,3,2,5
1,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,CTAGTCCTATGGCCG,1,1,1,5,1,7
2,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,GCGACGGGGATATGG,1,12,3,2,3,4
3,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,GTGGTTTGCTCGTTG,1,12,5,6,6,3
4,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,TTAAGATCACTTGTC,1,5,3,4,2,2
...,...,...,...,...,...,...,...,...,...
3497662,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TAGTTTCTGGGCATG,8,15,7,15,4,12
3497663,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,GGAAGACGCCCGGAG,8,24,6,20,12,22
3497664,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,CTAACTCAAGCGTGC,8,5,2,15,4,14
3497665,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,AAGGGATAAAAGCCG,9,19,5,12,7,15
3497666,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,AGATATGTCGGGCGC,9,27,5,24,6,13

In [5]:
counts_sequences_df["allele"].value_counts()
# allele
# alt    1970324
# ref    1527343

allele
alt    1970324
ref    1527343
Name: count, dtype: int64

### Pia: we have barcodes assigned to two variants in NGN2_counts_sequences.tsv.gz
- Question: is the assignment correct?

In [6]:
# load the used assignment file 
assignment_file = "/data/gpfs-1/groups/ag_kircher/work/MPRA/IGVF_Y1_design/experiment/results/experiments/run1counts_run2Assignment_NoDupAss/assignment/assignmentFixDuplicates.tsv.gz"
assignement_df = pd.read_csv(assignment_file, sep='\t', header=None)
assignement_df.columns = ["barcode", "oligo_id", "informations", "assignment_number"] # 7078311 rows
curr_file = "assignement_df"
# identify if the barcode column is unique or not
print(f"Check if barcode column in {curr_file} is unique")
if assignement_df["barcode"].is_unique: # True
    print("barcode column is unique")

In [11]:
assignement_df

,barcode,oligo_id,informations,assignment_number
0,AAAAAAAAAAACGTC,GC_Vista:eye;fb;hb;mb_hs1644_vistaElementContr...,16;270M;NM:i:0;MD:Z:270;60,5/5
1,AAAAAAAAAACAAGT,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,16;270M;NM:i:0;MD:Z:270;6,7/7
2,AAAAAAAAAACACCA,cardiac_neuro_cava_random:ALT_FTO|ENSG00000140...,16;270M;NM:i:0;MD:Z:270;6,10/10
3,AAAAAAAAAACCTCG,cardiac_neuro_cava_random:REF_FKRP|ENSG0000018...,16;270M;NM:i:0;MD:Z:270;6,7/7
4,AAAAAAAAAAGCTGG,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,16;270M;NM:i:0;MD:Z:270;6,8/8
...,...,...,...,...
7078306,TTTTTTTTTTGACGA,cardiac_neuro_cava_random:ALT_ACTN2|ENSG000000...,16;270M;NM:i:0;MD:Z:270;6,11/11
7078307,TTTTTTTTTTGCACA,cardiac_neuro_cava_random:ALT_CARD11|ENSG00000...,16;270M;NM:i:0;MD:Z:270;6,25/26
7078308,TTTTTTTTTTGCACC,cardiac_neuro_cava_random:ALT_KRAS|ENSG0000013...,16;214M1I56M;NM:i:1;MD:Z:270;5,6/7
7078309,TTTTTTTTTTGCTAA,cardiac_neuro_cava_random:REF_NR4A2|ENSG000001...,16;270M;NM:i:0;MD:Z:270;6,6/6
7078310,TTTTTTTTTTGTCCC,cardiac_neuro_cava_random:ALT_NBN|ENSG00000104...,16;270M;NM:i:0;MD:Z:270;6,3/3

#### Question: Why is the NGN2_counts_sequences.tsv.gz file larger than NGN2_counts_per_bc_sorted.tsv.gz

In [12]:
# idea: load the NGN2_counts_per_bc_sorted.tsv.gz and find duplicated barcodes
counts_per_bc = "/data/gpfs-1/groups/ag_kircher/work/MPRA/IGVF_Y1_design/projects/bc_tradeoff/NGN2_counts_per_bc_sorted.tsv.gz"
counts_per_bc_df = pd.read_csv(counts_per_bc, sep='\t', header=None) # 3482468 rows
counts_per_bc_df.columns = ["barcode", "oligo_id", "DNA1", "RNA1", "DNA2", "RNA2", "DNA3", "RNA3"]

curr_file = "counts_per_bc"

In [14]:
counts_per_bc_df

In [15]:
print(f"Check if barcode column of {curr_file} is unique")
if counts_per_bc_df["barcode"].is_unique: # True
    print("barcode column is unique")

Check if barcode column of {curr_file} is unique
barcode column is unique

In [16]:
count_sequence = "/data/gpfs-1/groups/ag_kircher/work/MPRA/IGVF_Y1_design/projects/bc_tradeoff/NGN2_counts_sequences.tsv.gz"
count_sequence_df = pd.read_csv(count_sequence, sep='\t', header=None) # 3497667 rows
count_sequence_df.columns = ["variant_id", "allele", "barcode", "DNA1", "RNA1", "DNA2", "RNA2", "DNA3", "RNA3"]
curr_file = "joint_count_sequences"

In [17]:
count_sequence_df

,variant_id,allele,barcode,DNA1,RNA1,DNA2,RNA2,DNA3,RNA3
0,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,AAAACAAGCATACGG,5,7,3,4,4,13
1,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,AAGTTGATCCCATTC,3,3,2,9,2,8
2,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,AATCCGTCCAAGTCG,12,16,7,18,9,14
3,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,AATGACAACTCACTT,9,29,10,21,15,28
4,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,alt,ACACCGGCAAGGAAT,1,8,5,8,3,13
...,...,...,...,...,...,...,...,...,...
3497662,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTGCAGCGAGGAACC,5,8,6,14,6,9
3497663,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTGGCAGCCCGTCGC,1,8,3,7,6,4
3497664,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTGGGCTCCGAGTAG,6,9,4,8,10,9
3497665,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTGTGTATCCCTGGA,5,15,3,11,2,14
3497666,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTTCTGAGACATACC,1,9,3,4,1,8

In [23]:
count_sequence_df["variant_id"].is_unique # False

False

In [21]:
# print(f"Check if barcode column of {curr_file} is unique")
# if count_sequence_df["barcode"].is_unique: # True
#     print("barcode column is unique")
# else: 
#     print("barcode column is not unique")

# investigate barcodes matching to multiple oligos
# find duplicated barcodes and show their variant ids
duplicated_barcodes = count_sequence_df[count_sequence_df.duplicated(['barcode'], keep=False)]
duplicated_barcodes

,variant_id,allele,barcode,DNA1,RNA1,DNA2,RNA2,DNA3,RNA3
177,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,ref,AACTTTATCAATCAG,3,16,1,5,4,9
178,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,ref,AATCCATCCGACTGG,2,14,5,9,3,13
179,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,ref,AATTTGCTACGCTTC,10,28,12,23,15,20
180,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,ref,ACAAGCTCCATGGCG,7,16,4,20,5,12
181,cardiac_neuro_cava_random:AARS1|ENSG0000009086...,ref,AGGAAAATACGGCTG,2,7,6,5,1,6
...,...,...,...,...,...,...,...,...,...
3497662,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTGCAGCGAGGAACC,5,8,6,14,6,9
3497663,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTGGCAGCCCGTCGC,1,8,3,7,6,4
3497664,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTGGGCTCCGAGTAG,6,9,4,8,10,9
3497665,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTGTGTATCCCTGGA,5,15,3,11,2,14
3497666,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,ref,TTTCTGAGACATACC,1,9,3,4,1,8

In [25]:
# check if all barcodes have a count > 1 => yes
(duplicated_barcodes["barcode"].value_counts() > 1).all() # True

True

In [26]:
# duplicated_barcodes_df has 1156879 rows how many unique barcodes are there?
duplicated_barcodes["barcode"].nunique() # 407946 so 1165879 / 407946 = 2.86 => each barcode is assigned to 2.86 other barcodes

407946

#### Investigate if pias data is correct

In [29]:
pia_count_sequence = "/data/gpfs-1/users/kisa11_c/work/coding/MPRA/ProximalPromoter/projects/tt_analysis/malacoda_input_HepG2.tsv.gz"
pia_count_sequence_df = pd.read_csv(pia_count_sequence, sep='\t', header=0) #
pia_count_sequence_df

,variant_id,allele,barcode,DNA1,RNA1,DNA2,RNA2,DNA3,RNA3
0,Arensbergen_rs1004571_chr20:45278169A>G,alt,ATTGAAACGAAAGAA,2,1,5,3,1,4
1,Arensbergen_rs1004571_chr20:45278169A>G,alt,GCGATGAGCATGATA,5,12,8,12,6,22
2,Arensbergen_rs1004571_chr20:45278169A>G,alt,TACACGGGTGAGAAG,2,7,2,4,3,1
3,Arensbergen_rs1004571_chr20:45278169A>G,alt,TCAAAAAAAAGAATA,2,4,6,3,2,3
4,Arensbergen_rs1004571_chr20:45278169A>G,alt,TGTACTAAAGTGGTA,3,4,8,14,1,1
...,...,...,...,...,...,...,...,...,...
6552198,SaturationMutagenesis_TERT_28_C.T_chr5:1295240G>A,ref,GGGATCATATCCATC,11,37,6,23,7,19
6552199,SaturationMutagenesis_TERT_28_C.T_chr5:1295240G>A,ref,GTCATGCGAAGTCAG,5,12,11,4,6,5
6552200,SaturationMutagenesis_TERT_28_C.T_chr5:1295240G>A,ref,GTTTACTTTGTTGAT,11,4,9,2,2,2
6552201,SaturationMutagenesis_TERT_28_C.T_chr5:1295240G>A,ref,TAAAAATTGTTGAAT,7,8,8,3,1,2
6552202,SaturationMutagenesis_TERT_28_C.T_chr5:1295240G>A,ref,TGATGAGACACGCCA,1,6,3,2,3,2

In [ ]:
counts_per_bc = "/data/gpfs-1/users/kisa11_c/work/coding/MPRA/ProximalPromoter/projects/tt_analysis/HepG2_counts_per_bc.tsv.gz"