## This script identifies all reads matching the missing sequences (unique)
- read the all_exact_match.tsv in (`/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences/results/match_missing_sequences/all_exact_match.tsv`)
- get the unique reads (first column)
- store at (`/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences/results/matched_reads/all_exact_matched_reads.tsv`)

In [14]:
import pandas as pd

In [17]:
all_exact_matches_file = "/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences/results/match_missing_sequences/all_exact_match.tsv"
all_exact_matches_df = pd.read_csv(all_exact_matches_file, sep="\t", header=None)
all_exact_matches_df.columns = ["read", "oligo", "match_length"]
all_exact_matches_df

,read,oligo,match_length
0,@NB501960:812:HH53WAFX5:1:11101:21622:1110 XI:...,>cardiac_neuro_cava_random:REF_PPP2R2A|ENSG000...,270M
1,@NB501960:812:HH53WAFX5:1:11101:4019:1255 XI:Z...,>cardiac_neuro_cava_random:REF_ANK2|ENSG000001...,270M
2,@NB501960:812:HH53WAFX5:1:11101:3848:1256 XI:Z...,>cardiac_neuro_cava_random:REF_LMNA|ENSG000001...,270M
3,@NB501960:812:HH53WAFX5:1:11101:5659:1395 XI:Z...,>MK:newcore_110746|chr13-80235318+80235587|ref...,270M
4,@NB501960:812:HH53WAFX5:1:11101:23682:1535 XI:...,>cardiac_neuro_cava_random:ALT_RAI1|ENSG000001...,270M
...,...,...,...
1812287,@NB501960:812:HH53WAFX5:4:21612:8584:19852 XI:...,>cardiac_neuro_cava_random:REF_CNN3|ENSG000001...,270M
1812288,@NB501960:812:HH53WAFX5:4:21612:23901:19994 XI...,>cardiac_neuro_cava_random:REF_AHDC1|ENSG00000...,270M
1812289,@NB501960:812:HH53WAFX5:4:21612:18136:20141 XI...,>cardiac_neuro_cava_random:REF_CNN3|ENSG000001...,270M
1812290,@NB501960:812:HH53WAFX5:4:21612:8167:20283 XI:...,>MK:tile_47747|chr5-87945240+87945510|T-A-1_forw,270M
1812291,@NB501960:812:HH53WAFX5:4:21612:22607:20285 XI...,>MK:tile_47745|chr5-87945001+87945271|G-C-264_...,270M

In [18]:
## get all unique reads in that file (@ read name _ XI:... (Barcode))
all_exact_matches_df["read"].value_counts() # 864426

read
@NB501960:812:HH53WAFX5:1:11101:21622:1110 XI:Z:GAACTGCAGTGCGGA,YI:Z:AAAAAEEEEEEEEEE     1
@NB501960:812:HH53WAFX5:1:11105:7723:1957 XI:Z:TTTAATCAACGCATG,YI:Z:AAAAAEE6EEEEAEE      1
@NB501960:812:HH53WAFX5:1:11105:12701:2923 XI:Z:GTCCCAGGTTTACTA,YI:Z:AAAAAEEEEEEEEEE     1
@NB501960:812:HH53WAFX5:1:11105:22589:2783 XI:Z:CATCATTTTGCATAA,YI:Z:AAAAAEEEEEEEEEE     1
@NB501960:812:HH53WAFX5:1:11105:23844:2511 XI:Z:TTGGGACTCCACTCG,YI:Z:AAAAAEEEEEEEAEE     1
                                                                                        ..
@NB501960:812:HH53WAFX5:1:11101:9816:12624 XI:Z:TGCAGTACAGCAAAC,YI:Z:AAAAAEEEEEEEEEE     1
@NB501960:812:HH53WAFX5:1:11101:7183:12622 XI:Z:AACGCGTACGTCTAG,YI:Z:AAAAAEEEEEEEEEE     1
@NB501960:812:HH53WAFX5:1:11101:4551:12492 XI:Z:TAACCCTGGCACGAA,YI:Z:AAAAAEEEEEEEEEE     1
@NB501960:812:HH53WAFX5:1:11101:22665:12361 XI:Z:CGGTATGAGCGGTGT,YI:Z:AAAAAEEEEEEEEEE    1
@NB501960:812:HH53WAFX5:4:21612:22607:20285 XI:Z:ATACGCTCTGAAGTG,YI:Z:AAAAAEEEEEEEEEE    1
Name: count, Length: 1812292, dtype: int64

In [13]:
# investigate read: XI:Z:GGGGGGGGGGGGGGG,YI:Z:AAAAAEEEEEEEEEE with more detail
read = "XI:Z:GGGGGGGGGGGGGGG,YI:Z:AAAAAEEEEEEEEEE"
most_frequent_read = all_exact_matches_df[all_exact_matches_df["read"] == read]
most_frequent_read["label"] = most_frequent_read["oligo"].str.split(":").str[0]
most_frequent_read["label"].value_counts()

/data/gpfs-1/users/kisa11_c/scratch/tmp/hpc-cpu-96/ipykernel_1783515/1586897560.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  most_frequent_read["label"] = most_frequent_read["oligo"].str.split(":").str[0]

label
cardiac_neuro_cava_random    3059
MK                            125
GC_Mendelian_variants         123
GC_GABA_Chengyu                67
C_negative_neuron_NP           12
GC_Selvarajan                   9
GC_Glut_Chengyu                 8
GC_Vista                        2
C_positive_neuron_MK            2
GC_Kircher                      2
Name: count, dtype: int64

## Investigate if there are duplicated sequences in the missing sequences exact tsv (with reverse complement)
- load the file `/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences/resources/align_missing_sequences/missing_reference_exact.tsv`
- check for duplicated sequences

In [11]:
missing_seq_reference_file = "/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences/resources/align_missing_sequences/missing_reference_exact.tsv"
missing_seq_ref_df = pd.read_csv(missing_seq_reference_file, sep="\t", header=None)
missing_seq_ref_df.columns = ["header", "sequence"]
missing_seq_ref_df # 10168 
# ## check if there are any duplicated sequence 
# missing_seq_ref_df["sequence"].value_counts() # 10168
## All unique sequences => reads having exact matches of two sequences are not possible

,header,sequence
0,cardiac_neuro_cava_random:PRDM16|ENSG000001426...,AGGACCGGATCAACTGCCGCCCAGGAGCTCTCGTGCATCCACTCTG...
1,cardiac_neuro_cava_random:SZT2|ENSG00000198198...,AGGACCGGATCAACTGGGGGCGTGTGGTGGGTGGGGGGTGGGTGTT...
2,cardiac_neuro_cava_random:ST3GAL3|ENSG00000126...,AGGACCGGATCAACTCCCCAACCTCTCTCACGTACACCTGCGTGTT...
3,cardiac_neuro_cava_random:NOS1AP|ENSG000001989...,AGGACCGGATCAACTTGTTTGTTGTTTTGAGCACGTTTTAACTTTC...
4,cardiac_neuro_cava_random:RERE|ENSG00000142599...,AGGACCGGATCAACTGGGCTTCGAGGTGAAGCCCCCAGAGCTGGAC...
...,...,...
10163,MK:tile_985|chr1-33363966+33364235|LC28t6_revc,TCGGTTCACGCAATGAGGGGGTATGGCAGTGAGGAATGTGTTCTCC...
10164,MK:tile_985|chr1-33363966+33364235|LC28t7_revc,TCGGTTCACGCAATGAGGGGGTATGGCAGTGAGGAATGTGTTCTCC...
10165,MK:tile_985|chr1-33363966+33364235|LC28t9_revc,TCGGTTCACGCAATGAGGGGGTATGGCAGTGAGGAATGTGTTCTCC...
10166,MK:tile_30307|chr3-171305106+171305375|scrambl...,TCGGTTCACGCAATGACTGAATGAAAGTTAAGGATTGAGCTCACTA...
10167,MK:tile_22033|chr2-71506006+71506275|scramble_...,TCGGTTCACGCAATGGAGCCCCCCTGGCTACCTGCGCGCACTCCTA...