## Identify in the `exact_match.*.tsv` files which oligos were found
- Which oligos were matched to these reads?
- How many different oligos matched?

In [74]:
import pandas as pd
import matplotlib.pyplot as plt
import os

#### Check how many sequences are missing 5084 or 10168?
- Check if duplicates are present in the `/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences/all_missing_seqs_270.fa` file

In [19]:
missing_sequenes_file = "/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences/missing_reference_exact_uniq.tsv"
missing_sequenes_df = pd.read_csv(missing_sequenes_file, sep="\t", header=None)
missing_sequenes_df.columns = ["oligo", "sequence"]
missing_sequenes_df # all_missing_seqs_270_df
## duplicated sequences
missing_sequenes_df["sequence"].unique().shape # (8366,)
missing_sequenes_df["oligo"].unique().shape # (5084,)

(10168,)

In [41]:
# read the file in
exact_match_test = "/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences/old_match_missing_sequences/exact_match.0.tsv" # 60305
exact_match_test = "/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences/old_match_missing_sequences/all_exact_match.tsv" # 1812292 
exact_match_df = pd.read_csv(exact_match_test, sep="\t", header=None)
exact_match_df.columns = ["read", "oligo", "match_length"]
exact_match_df[exact_match_df["oligo"].str.contains("cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E2358113_fwd_tile1-1_fw")] # 5254

,read,oligo,match_length
25,@NB501960:812:HH53WAFX5:1:11101:9993:2788,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M
85,@NB501960:812:HH53WAFX5:1:11101:11561:7519,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M
292,@NB501960:812:HH53WAFX5:1:11102:1624:5911,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M
1038,@NB501960:812:HH53WAFX5:1:11105:19271:5658,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M
1256,@NB501960:812:HH53WAFX5:1:11106:6859:4261,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M
...,...,...,...
1811242,@NB501960:812:HH53WAFX5:4:21607:6313:15257,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M
1811257,@NB501960:812:HH53WAFX5:4:21607:20018:17022,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M
1811356,@NB501960:812:HH53WAFX5:4:21608:16423:7290,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M
1811397,@NB501960:812:HH53WAFX5:4:21608:8445:11046,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M
1811615,@NB501960:812:HH53WAFX5:4:21609:25514:12190,cardiac_neuro_cava_random:REF_TRIO|ENSG0000003...,270M

#### Make exact match unique

In [51]:
exact_match_df # (1812292,)
# exact_match_df["read"].unique().shape # (60305,)
exact_match_df["oligo"].unique().shape # (2800,)
exact_match_df["found"] = 1
unique_oligo_matches = exact_match_df.drop_duplicates('oligo', keep='first') # 2800 
unique_oligo_matches
#

,read,oligo,match_length,found
0,@NB501960:812:HH53WAFX5:1:11101:21622:1110,cardiac_neuro_cava_random:REF_PPP2R2A|ENSG0000...,270M,1
1,@NB501960:812:HH53WAFX5:1:11101:4019:1255,cardiac_neuro_cava_random:REF_ANK2|ENSG0000014...,270M,1
2,@NB501960:812:HH53WAFX5:1:11101:3848:1256,cardiac_neuro_cava_random:REF_LMNA|ENSG0000016...,270M,1
3,@NB501960:812:HH53WAFX5:1:11101:5659:1395,MK:newcore_110746|chr13-80235318+80235587|refe...,270M,1
4,@NB501960:812:HH53WAFX5:1:11101:23682:1535,cardiac_neuro_cava_random:ALT_RAI1|ENSG0000010...,270M,1
...,...,...,...,...
1700856,@NB501960:812:HH53WAFX5:1:21107:12668:11101,cardiac_neuro_cava_random:REF_CELF2|ENSG000000...,270M,1
1736257,@NB501960:812:HH53WAFX5:3:21607:24356:5621,cardiac_neuro_cava_random:ALT_SLC25A22|ENSG000...,270M,1
1740108,@NB501960:812:HH53WAFX5:4:11412:21401:15560,cardiac_neuro_cava_random:REF_NOS3|ENSG0000016...,270M,1
1780204,@NB501960:812:HH53WAFX5:2:21210:16496:7958,cardiac_neuro_cava_random:REF_RFX3|ENSG0000008...,270M,1
1805952,@NB501960:812:HH53WAFX5:4:21403:17929:12627,cardiac_neuro_cava_random:ALT_AUTS2|ENSG000001...,270M,1

### Check if all reads are reverse reads (not possible)

In [16]:
read_investigating_df = exact_match_df["read"]
read_investigating_df
# only have the shown name: How to get if it is reverse or forward read? -> not possible

0           @NB501960:812:HH53WAFX5:1:11101:21622:1110
1            @NB501960:812:HH53WAFX5:1:11101:4019:1255
2            @NB501960:812:HH53WAFX5:1:11101:3848:1256
3            @NB501960:812:HH53WAFX5:1:11101:5659:1395
4           @NB501960:812:HH53WAFX5:1:11101:23682:1535
                              ...
1812287    @NB501960:812:HH53WAFX5:4:21612:19871:20005
1812288    @NB501960:812:HH53WAFX5:4:21612:15389:20148
1812289    @NB501960:812:HH53WAFX5:4:21612:24636:20151
1812290    @NB501960:812:HH53WAFX5:4:21612:15829:20292
1812291    @NB501960:812:HH53WAFX5:4:21612:22140:20293
Name: read, Length: 1812292, dtype: object

### Investigate which and how many oligos are matched

In [4]:
def fasta_to_tsv(fasta_file, tsv_file):
    with open(fasta_file, "r") as f:
        with open(tsv_file, "w") as t:
            for line in f:
                if line.startswith(">"):
                    t.write(line[1:].strip())
                    t.write("\t")
                else:
                    t.write(line.strip())
                    t.write("\n")

#### Investigate the matched oligo names

In [37]:
missing_sequenes_df # 10168 
# filter for cardiac_neuro_cava_random
cardiac_neuro_cava_random = missing_sequenes_df[missing_sequenes_df["oligo"].str.contains("cardiac_neuro_cava_random")] # 9314
cardiac_neuro_cava_random[cardiac_neuro_cava_random["oligo"].str.contains("cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E2358113_fwd_tile1-1_fw")]["oligo"].to_list()

['cardiac_neuro_cava_random:TRIO|ENSG00000038382.23|EH38E3626932_fwd_tile1-1_fw',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E2358113_fwd_tile1-1_fw',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3626976_fwd_tile1-1_fw',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3626983_fwd_tile1-1_fw',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_fw',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E2358158_fwd_tile1-1_fw',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E2358165_fwd_tile1-1_fw',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3627038_fwd_tile1-1_fw',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3627090_fwd_tile1-1_fw',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626915_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626915|5-14119587-A-G_fw',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626983_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626983|5-14203817-A-T_fw',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207232-C-T_fw',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207320-A-T_fw',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207321-C-T_fw',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207323-C-T_fw',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207324-A-T_fw',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207325-C-T_fw',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3627038_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3627038|5-14262323-G-A_fw',
 'cardiac_neuro_cava_random:TRIO|ENSG00000038382.23|EH38E3626932_fwd_tile1-1_rv',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E2358113_fwd_tile1-1_rv',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3626976_fwd_tile1-1_rv',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3626983_fwd_tile1-1_rv',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_rv',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E2358158_fwd_tile1-1_rv',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E2358165_fwd_tile1-1_rv',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3627038_fwd_tile1-1_rv',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3627090_fwd_tile1-1_rv',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626915_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626915|5-14119587-A-G_rv',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626983_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626983|5-14203817-A-T_rv',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207232-C-T_rv',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207320-A-T_rv',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207321-C-T_rv',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207323-C-T_rv',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207324-A-T_rv',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626987_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626987|5-14207325-C-T_rv',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3627038_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3627038|5-14262323-G-A_rv']

#### Match exact matches and oligos

In [94]:
unique_oligo_matches[["oligo","found"]]
# merge missing_sequences_tsv and found_oligos left join
missing_sequences = pd.merge(missing_sequenes_df, unique_oligo_matches, on="oligo", how="left")
missing_sequences["label"] = missing_sequences["oligo"].str.split(":").str[0] 
missing_sequences["forward/rev_comp"] = missing_sequences["oligo"].str.split("_").str[-1]
missing_sequences

,oligo,sequence,found,label,forward/rev_comp
0,cardiac_neuro_cava_random:PRDM16|ENSG000001426...,AGGACCGGATCAACTGCCGCCCAGGAGCTCTCGTGCATCCACTCTG...,NaN,cardiac_neuro_cava_random,fw
1,cardiac_neuro_cava_random:SZT2|ENSG00000198198...,AGGACCGGATCAACTGGGGGCGTGTGGTGGGTGGGGGGTGGGTGTT...,NaN,cardiac_neuro_cava_random,fw
2,cardiac_neuro_cava_random:ST3GAL3|ENSG00000126...,AGGACCGGATCAACTCCCCAACCTCTCTCACGTACACCTGCGTGTT...,NaN,cardiac_neuro_cava_random,fw
3,cardiac_neuro_cava_random:NOS1AP|ENSG000001989...,AGGACCGGATCAACTTGTTTGTTGTTTTGAGCACGTTTTAACTTTC...,NaN,cardiac_neuro_cava_random,fw
4,cardiac_neuro_cava_random:RERE|ENSG00000142599...,AGGACCGGATCAACTGGGCTTCGAGGTGAAGCCCCCAGAGCTGGAC...,NaN,cardiac_neuro_cava_random,fw
...,...,...,...,...,...
10163,MK:tile_985|chr1-33363966+33364235|LC28t6_rv,TCGGTTCACGCAATGAGGGGGTATGGCAGTGAGGAATGTGTTCTCC...,NaN,MK,rv
10164,MK:tile_985|chr1-33363966+33364235|LC28t7_rv,TCGGTTCACGCAATGAGGGGGTATGGCAGTGAGGAATGTGTTCTCC...,NaN,MK,rv
10165,MK:tile_985|chr1-33363966+33364235|LC28t9_rv,TCGGTTCACGCAATGAGGGGGTATGGCAGTGAGGAATGTGTTCTCC...,NaN,MK,rv
10166,MK:tile_30307|chr3-171305106+171305375|scrambl...,TCGGTTCACGCAATGACTGAATGAAAGTTAAGGATTGAGCTCACTA...,NaN,MK,rv
10167,MK:tile_22033|chr2-71506006+71506275|scramble_...,TCGGTTCACGCAATGGAGCCCCCCTGGCTACCTGCGCGCACTCCTA...,NaN,MK,rv

In [95]:
found_oligos = missing_sequences[missing_sequences["found"] == 1] # 2800 
still_missing_oligos = missing_sequences[missing_sequences["found"] != 1] # 7368

### Identify distribution of matches and distribution of still missing oligos
- How many oligos are still missing? 7368
- How many (unique) oligos are matched? 2800 (at least once)
- Plot of distribution of labels of the found oligos
- Plot of distribution of labels of the missing oligos
- Plot of distribution of found oligos (forward)
- Plot of distribution of found oligos (reverse complement)

In [96]:
# all found oligos
found_oligos
# all missing oligos
still_missing_oligos
# only forward reads
forward_found_oligos = found_oligos[found_oligos["forward/rev_comp"] == "fw"] # 1187 rows
# only reverse reads
reverse_found_oligos = found_oligos[found_oligos["forward/rev_comp"] == "rv"] # 1613 rows

In [99]:
reverse_found_oligos

,oligo,sequence,found,label,forward/rev_comp
5118,cardiac_neuro_cava_random:NOS3|ENSG00000164867...,TCGGTTCACGCAATGGCCAGCCTGCCTCTGTTTCTAGGTCCCCGAG...,1.0,cardiac_neuro_cava_random,rv
5119,cardiac_neuro_cava_random:NOS3|ENSG00000164867...,TCGGTTCACGCAATGTGCAGGCTCAGGGTAGGGCAGGAGAGTCCCC...,1.0,cardiac_neuro_cava_random,rv
5120,cardiac_neuro_cava_random:NOS3|ENSG00000164867...,TCGGTTCACGCAATGCTGGTGTCCCCACTTCTCTGAGCATCCCCCA...,1.0,cardiac_neuro_cava_random,rv
5121,cardiac_neuro_cava_random:NOS3|ENSG00000164867...,TCGGTTCACGCAATGGTGTGAGCTGGTACAGGGGCTGTGTGTGTCA...,1.0,cardiac_neuro_cava_random,rv
5122,cardiac_neuro_cava_random:NOS3|ENSG00000164867...,TCGGTTCACGCAATGCAGAGGTCAAGGACAGGAGGGTCCTAATTCT...,1.0,cardiac_neuro_cava_random,rv
...,...,...,...,...,...
9829,GC_Glut_Chengyu:Glut|chr12:44310889-44311158|-...,TCGGTTCACGCAATGTGGAAATACGAGTTTAAAATTAGACTATGAT...,1.0,GC_Glut_Chengyu,rv
9830,GC_Glut_Chengyu:Glut|chr2:212699336-212699605|...,TCGGTTCACGCAATGATTACTTGCGACATAGGACTCAGGAATCTGT...,1.0,GC_Glut_Chengyu,rv
9831,GC_Glut_Chengyu:Glut|chr2:212699336-212699605|...,TCGGTTCACGCAATGATTTCTCTGATTATTTGTATATTTTTCATAT...,1.0,GC_Glut_Chengyu,rv
9832,GC_Glut_Chengyu:Glut|chr2:212699351-212699620|...,TCGGTTCACGCAATGAACACACATGGACATATTACTTGCGACATAG...,1.0,GC_Glut_Chengyu,rv
9833,GC_Glut_Chengyu:Glut|chr2:212699351-212699620|...,TCGGTTCACGCAATGTGTATATTTTTCATATACTACATAATTCCCT...,1.0,GC_Glut_Chengyu,rv

In [90]:
def plot_oligo_label_distribution(oligo_label_df, outpath):
    """
    Plots the distribution of the labels in the dataframe
    @input: label_df: dataframe with a column "label" and a column "oligo"
    """
    sorted_missing_seqs = oligo_label_df.groupby('label').count().sort_values(by='oligo', ascending=False)["oligo"]
    ax = sorted_missing_seqs.plot(kind='bar', figsize=(20, 6))
    print(ax.patches)
    for p in ax.patches:
        ax.annotate(str(p.get_height()), (p.get_x() * 1.005, (p.get_height() + 15) * 1.005))
    # store the plot as png
    ax.get_figure().savefig(outpath, dpi=300, bbox_inches='tight')
    plt.close()

In [101]:
output_dir = "/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/01_missing_sequences"
# plot the distribution of the found oligos
plot_oligo_label_distribution(found_oligos, os.path.join(output_dir , "identified_oligos/found_oligos_distribution.png"))

# # plot the distribution of the found oligos in the reverse reads
plot_oligo_label_distribution(reverse_found_oligos, os.path.join(output_dir , "identified_oligos/reverse_found_oligos_distribution.png"))
# # plot the distribution of the missing oligos
plot_oligo_label_distribution(still_missing_oligos, os.path.join(output_dir , "identified_oligos/missing_oligos_distribution.png"))
# # plot the distribution of the found oligos in the forward reads
plot_oligo_label_distribution(forward_found_oligos, os.path.join(output_dir , "identified_oligos/forward_found_oligos_distribution.png"))

<Axes.ArtistList of 17 patches>
<Axes.ArtistList of 3 patches>
<Axes.ArtistList of 21 patches>
<Axes.ArtistList of 15 patches>

### No oligo names could be matched (because of wrong input files; bad note taking)

### Identify all the matching reads

In [ ]:
# found_oligos