### Mohan did the new prediction of the variants again so I have the correct IDs
- get the number of different variant ids

In [2]:
import pandas as pd

In [3]:
variant_path = "/data/gpfs-1/users/kisa11_c/work/coding/MPRA/IGVF_Y1_design/projects/enformer_predictions/variants_80k_680.tsv"

variant_prediction_df = pd.read_csv(variant_path, sep="\t")
variant_prediction_df.head()

,chrom,pos,id,ref,alt,0_DNASE:cerebellum mal,1_DNASE:frontal cortex,2_DNASE:chorion,3_DNASE:Ishikawa treat,4_DNASE:GM03348,...,665_DNASE:testis male ad,666_DNASE:transverse col,667_DNASE:right renal pe,668_DNASE:lung embryo (1,669_DNASE:inferior parie,670_DNASE:kidney capilla,671_DNASE:placenta male,672_DNASE:right kidney m,673_DNASE:coronary arter,674_ATAC:BM0106-Day0-MCP
0,chr1,2179591,cardiac_neuro_cava_random:SKI|ENSG00000157933....,T,C,-24.532421,7.422592,4.616910,3.232340,0.709609,...,1.303913,-6.704362,0.892136,5.766830,1.435593,-2.547557,-4.155036,1.067765,1.663347,0.862448
1,chr1,2191444,cardiac_neuro_cava_random:SKI|ENSG00000157933....,G,A,-0.190993,0.284395,0.140426,0.344883,0.244013,...,-0.092939,0.778827,-0.036971,1.074118,-0.398899,0.711352,-1.020760,-0.143923,0.184462,0.291147
2,chr1,2192015,cardiac_neuro_cava_random:SKI|ENSG00000157933....,G,T,0.150436,-2.591567,9.908080,3.370937,-2.697484,...,-0.615270,-4.682690,-3.194387,-16.274694,-1.268586,-0.251593,-5.991785,-4.505129,-7.675299,-0.453357
3,chr1,2192366,cardiac_neuro_cava_random:SKI|ENSG00000157933....,T,G,-127.368546,-7.038474,54.407074,16.822454,5.431040,...,2.671842,145.295640,59.828503,259.200600,-7.615203,14.868539,176.643550,65.624180,110.170120,-9.438502
4,chr1,2193142,cardiac_neuro_cava_random:SKI|ENSG00000157933....,G,A,-1.632162,5.861496,20.475412,-0.096696,1.420127,...,-0.458741,1.784662,-0.228986,7.328242,-2.774963,4.021713,-2.348675,0.166304,-0.649004,0.029709

In [5]:
variant_vcf_path ="/home/kisa/coding/80K_MPRA/design_data/design_info/variants.vcf.gz"
vcf_file = pd.read_csv(variant_vcf_path, sep="\t", comment="#", header=None)
vcf_file.columns = ['#CHROM', 'POS', 'ID', 'REF', 'ALT', 'QUAL', 'FILTER', 'INFO']
# vcf_file['chr_pos_ref_alt'] = vcf_file['ID'].apply(get_chrom_pos_ref_alt_pattern)
# vcf_file['chr_pos_ref_alt'].nunique() # 45738
# vcf_file['chr_pos_ref_alt'].shape[0] # 46143
vcf_file['ID'].nunique() # 46143

46143

In [6]:
filtered_variant_prediction_df = variant_prediction_df[['id', '0_DNASE:cerebellum mal']]
filtered_variant_prediction_df

,id,0_DNASE:cerebellum mal
0,cardiac_neuro_cava_random:SKI|ENSG00000157933....,-24.532421
1,cardiac_neuro_cava_random:SKI|ENSG00000157933....,-0.190993
2,cardiac_neuro_cava_random:SKI|ENSG00000157933....,0.150436
3,cardiac_neuro_cava_random:SKI|ENSG00000157933....,-127.368546
4,cardiac_neuro_cava_random:SKI|ENSG00000157933....,-1.632162
...,...,...
46468,cardiac_neuro_cava_random:B3GNT9|ENSG000002371...,-2.009432
46469,cardiac_neuro_cava_random:B3GNT9|ENSG000002371...,-1.219052
46470,cardiac_neuro_cava_random:B3GNT9|ENSG000002371...,1.608583
46471,cardiac_neuro_cava_random:B3GNT9|ENSG000002371...,-5.485970
46472,cardiac_neuro_cava_random:B3GNT9|ENSG000002371...,-1.317142

In [11]:
# get the number of variants
variant_prediction_df['id'].nunique() # 31911
unique_filtered_variant_prediction_df = filtered_variant_prediction_df.drop_duplicates()
unique_filtered_variant_prediction_df.shape[0] # 36374
unique_filtered_variant_prediction_df['id'].nunique()

36374

way to low, expected: 46143

In [8]:
filtered_variant_prediction_df['id'].shape[0]

46473

In [7]:
vcf_with_prediction = vcf_file.merge(filtered_variant_prediction_df, left_on='ID', right_on='id', how='left')
not_matched_variants = vcf_with_prediction.loc[vcf_with_prediction['0_DNASE:cerebellum mal'].isna()]
matched_variants = vcf_with_prediction.loc[~vcf_with_prediction['0_DNASE:cerebellum mal'].isna()]
# Numbers:
print(f'Number of matched variants: {matched_variants.shape[0]}')
print(f'Number of not matched variants: {not_matched_variants.shape[0]}')
print()

Number of matched variants: 46473
Number of not matched variants: 14232