# Look at the errors of the SPDI column after validation
- output path: /home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/spdi_verification

In [3]:
import ast
from importlib import reload
import pandas as pd
import sys
import os
import yaml

sys.path.append('../helpful_functions')
import helpful_functions as hf
reload(hf)

# config
config_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/config_file.yaml"
with open(config_path) as conf:
    config = yaml.load(conf, Loader=yaml.FullLoader)
    conf.close()

In [ ]:
# column names
col_name = 'name'
col_header = 'name'
col_sequence = 'sequence'
col_category = 'category'
col_class = 'class'
col_source = 'source'
col_ref = 'ref'
col_chr = 'chr'
col_start = 'start'
col_end = 'end'
col_strand = 'strand'
col_variant_class = 'variant_class'
col_variant_pos = 'variant_pos'
col_SPDI = 'SPDI'
col_allele = 'allele'
col_info = 'info'
my_col_ref_base = 'tmp_ref_base'
my_col_alt_base = 'tmp_alt_base'

In [28]:
# Link to the metadata output
directory_path = config['final_output_dir'] # '/data/cephfs-2/unmirrored/groups/kircher/MPRA/IGVF_Y1_design/design/mpra_metadata_format'
metadata_file_ending = '.metadata.tsv.gz'

# error directory
validation_dir = '/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/spdi_verification'

## Definition of the indels in the metadata file
### Process: 
- combine the metadata files
- filter for indel

In [76]:
# helpful functions
def list_metadata_files_in_subdirectories(directory, file_ending, file_beginning="........."):
    """Returns all the files in the subdirectories of a given directory"""
    file_list = []
    for root, dirs, files in os.walk(directory):
        for file in files:
            if file_ending in file and (file.startswith(file_beginning) or file_beginning == "........."):
                file_list.append(os.path.join(root, file))
    return file_list


def safe_eval(x):
    if pd.isna(x):
        return None
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return x


def get_category(header):
    """
    Get the category of the headers set all to element if not scarmbled
    """

    label = hf.get_label(header)

    if 'scramble' in header:
        # Check if header is scrambled
        # Info: scrambled is in C_negative_neuron_NP and scramble MK
        # Note: Other cases are not checked with this function
        return 'scrambled'
    else:
        return 'element'


def get_reference_genome(row):
    """If col_category is synthetic or scrambled or in dnase_control_groups, set ref to GRCh37 else GRCh38"""
    row[col_ref] = 'GRCh38'
    return row


def extract_rsid(s):
    import re
    match = re.findall(r"rs\d+", s)
    return match[-1] if match else None

import requests

def get_rsid_position(rsid, assembly="GRCh38"):
    url = f"https://rest.ensembl.org/variation/human/{rsid}"
    headers = {"Content-Type": "application/json"}
    response = requests.get(url, headers=headers, params={"genome": assembly})
    if response.status_code == 200:
        data = response.json()
        for mapping in data.get("mappings", []):
            if mapping["assembly_name"] == assembly:
                return {
                    "chromosome": mapping["seq_region_name"],
                    "start": mapping["start"],
                    "end": mapping["end"],
                }
    return None



# dict of chr number to refseq chromosome number
chrom_2_refseq = {
    "chr1": "NC_000001.11",
    "chr2": "NC_000002.12",
    "chr3": "NC_000003.12",
    "chr4": "NC_000004.12",
    "chr5": "NC_000005.10",
    "chr6": "NC_000006.12",
    "chr7": "NC_000007.14",
    "chr8": "NC_000008.11",
    "chr9": "NC_000009.12",
    "chr10": "NC_000010.11",
    "chr11": "NC_000011.10",
    "chr12": "NC_000012.12",
    "chr13": "NC_000013.11",
    "chr14": "NC_000014.9",
    "chr15": "NC_000015.10",
    "chr16": "NC_000016.10",
    "chr17": "NC_000017.11",
    "chr18": "NC_000018.10",
    "chr19": "NC_000019.10",
    "chr20": "NC_000020.11",
    "chr21": "NC_000021.9",
    "chr22": "NC_000022.11",
    "chrX": "NC_000023.11",
    "chrY": "NC_000024.10"}


def create_speedy_chromosomes(user_string, seperator="-", indices=[0,1,2,3]):
    """
    Returns SPDI identifier for given variant
    spdi: refseq_chromosome:pos:ref:alt
    @params: indices: list of indices for chromosome, position, ref and alt in user_string
    """
    if len(user_string.split(seperator)) < 4:
        raise ValueError('Not enough indices given: Expected chrom, pos, ref, alt position in user_string')
    split_string = user_string.split(seperator)
    zero_based_position = int(split_string[indices[1]]) # I think everything is now 0-based
    return f'{chrom_2_refseq[split_string[indices[0]]]}:{zero_based_position}:{split_string[indices[2]]}:{split_string[indices[3]]}'


def get_spdi(row):
    """
    Returns the SPDI identifier for the given variant using start and variant_pos
    Assumption: allele need to be set beforehands
    """
    if not (hf.is_alternative(row[col_allele])) and (row[my_col_ref_base] and row[my_col_alt_base]):
        row['SPDI'] = 'NA'
        return row
    # identify the variant chrom-pos-ref-alt pattern
    chrom_pos_ref_alt = f'{row[col_chr]}-{row[col_start]+row[col_variant_pos]}-{row[my_col_ref_base]}-{row[my_col_alt_base]}'
    if chrom_pos_ref_alt == "NA":
        raise ValueError('Variant pattern could not be found')
    # create the SPDI identifier
    row[col_SPDI] = create_speedy_chromosomes(chrom_pos_ref_alt, seperator='-', indices=[0,1,2,3])
    return row

def is_indel(variant_class):
    if isinstance(variant_class, list):
        return 'indel' in variant_class
    else: # variant class is just a string
        return variant_class == 'indel'

def is_non_zero_file(fpath):
    return os.path.isfile(fpath) and os.path.getsize(fpath) > 0

def read_and_eval_metadata(file):
    list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]

    # load metadata file
    metadata_file = pd.read_csv(file, sep="\t")
    # Apply the safe_eval function to the specified columns
    for col in list_columns:
        metadata_file[col] = metadata_file[col].apply(safe_eval)
    return metadata_file

### Check for the overall numbers

In [23]:
file_list = list_metadata_files_in_subdirectories(directory_path, metadata_file_ending)
list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]


n_indels = 0
for file in file_list:
    group_name = file.split('/')[-1].split(metadata_file_ending)[0]
    # load metadata file
    metadata_file = pd.read_csv(file, sep="\t")
    # Apply the safe_eval function to the specified columns
    for col in list_columns:
        metadata_file[col] = metadata_file[col].apply(safe_eval)
    # find the indel rows
    indel_rows = metadata_file.loc[metadata_file[col_variant_class].apply(is_indel)]
    if indel_rows.shape[0] > 0:
        # print(group_name)
        print(file)
        # print('n_indel', indel_rows.shape[0])
    n_indels += indel_rows.shape[0]

print(n_indels)


# GC_Mendelian_variants
# n_indel 6
# GC_Mohlke
# n_indel 1
# C_positive_heart_CAD
# n_indel 2

/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/GC_Mendelian_variants/GC_Mendelian_variants.metadata.tsv.gz
/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/GC_Mohlke/GC_Mohlke.metadata.tsv.gz
/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/C_positive_heart_CAD/C_positive_heart_CAD.metadata.tsv.gz
9

### Investigate them by hand:

In [82]:
file_list = list_metadata_files_in_subdirectories(directory_path, metadata_file_ending)
list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]


n_indels = 0
# file_list = ['/data/cephfs-2/unmirrored/groups/kircher/MPRA/IGVF_Y1_design/design/mpra_metadata_format/cardiac_neuro_cava_random/cardiac_neuro_cava_random.metadata.tsv.gz']
for file in file_list:
    group_name = file.split('/')[-1].split(metadata_file_ending)[0]
    # load metadata file
    metadata_file = pd.read_csv(file, sep="\t")
    # Apply the safe_eval function to the specified columns
    for col in list_columns:
        metadata_file[col] = metadata_file[col].apply(safe_eval)
    # find the indel rows
    indel_rows = metadata_file.loc[metadata_file[col_variant_class].apply(is_indel)].copy()
    if indel_rows.shape[0] > 0:
        print(group_name)
        print(indel_rows[col_name])
        break
    n_indels += indel_rows.shape[0]

print(n_indels)

GC_Mendelian_variants
42     GC_Mendelian_variants:ALT_chr8:11703860G>T|GAT...
43     GC_Mendelian_variants:ALT_chr8:11703890AG>A|GA...
50     GC_Mendelian_variants:ALT_chr1:209816133C>CA|I...
98     GC_Mendelian_variants:ALT_chr7:156791255G>C|SH...
99     GC_Mendelian_variants:ALT_chr7:156791257G>A|SH...
100    GC_Mendelian_variants:ALT_chr7:156791274T>TTAA...
Name: name, dtype: object
0

In [21]:
indel_rows

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info
42,GC_Mendelian_variants:ALT_chr8:11703860G>T|GAT...,CGGGGCTGGGAGGATCCCCACTACCCCTGCCCAGGAACTAGCATCC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr8,11703724,11703994,.,indel,165.0,NC_000008.11:11703889:AG:A,alt,NaN
43,GC_Mendelian_variants:ALT_chr8:11703890AG>A|GA...,CCAGGAACTAGCATCCAGCCGGGCACCCCGGGTGACCCAGTGCCCC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr8,11703754,11704024,.,indel,135.0,NC_000008.11:11703889:AG:A,alt,NaN
50,GC_Mendelian_variants:ALT_chr1:209816133C>CA|I...,TTGAGCCCAGGGGCTGAATCTGGAGCTTTGGGGCCTGGGAACCTCT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,209815997,209816267,.,indel,135.0,NC_000001.11:209816132:C:CA,alt,NaN
98,GC_Mendelian_variants:ALT_chr7:156791255G>C|SH...,GAGATATGGCTTCATTTTCTGTAATAAACACTAAGATCAAAACATG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791119,156791389,.,indel,154.0,NC_000007.14:156791273:T:TTAAGGAAGTGATT,alt,NaN
99,GC_Mendelian_variants:ALT_chr7:156791257G>A|SH...,GATATGGCTTCATTTTCTGTAATAAACACTAAGATCAAAACATGAC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791121,156791391,.,indel,152.0,NC_000007.14:156791273:T:TTAAGGAAGTGATT,alt,NaN
100,GC_Mendelian_variants:ALT_chr7:156791274T>TTAA...,TGTAATAAACACTAAGATCAAAACATGACCCAAGTTAAATTTCCTT...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr7,156791138,156791408,.,indel,135.0,NC_000007.14:156791273:T:TTAAGGAAGTGATT,alt,NaN

## Look at the SNP cases

In [81]:
file_list = list_metadata_files_in_subdirectories(validation_dir, file_ending='.tsv', file_beginning='error_')
metadata_files = list_metadata_files_in_subdirectories(directory_path, file_ending=metadata_file_ending)

list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]

ignorable_error_dfs = ['cardiac_neuro_cava_random']


for file in file_list:
    group_name = file.split('/')[-1].split(metadata_file_ending)[0].split('.tsv')[0].split('error_SPDI_')[1]
    # load file only if not empty:
    if not is_non_zero_file(file):
        continue
    if group_name in ignorable_error_dfs:
        continue
    error_file = pd.read_csv(file, sep="\t", header=None)
    error_file.columns = [col_SPDI, 'error_info', 'error_valid']

    if error_file.shape[0] > 0:
        print(group_name, f'n={error_file.shape[0]}')

C_positive_heart_CAD n=1
GC_Mendelian_variants n=3
GC_Mohlke n=1

In [128]:
file_list = list_metadata_files_in_subdirectories(validation_dir, file_ending='.tsv', file_beginning='error_')
metadata_files = list_metadata_files_in_subdirectories(directory_path, file_ending=metadata_file_ending)

list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]

ignorable_error_dfs = ['cardiac_neuro_cava_random']


for file in file_list:
    group_name = file.split('/')[-1].split(metadata_file_ending)[0].split('.tsv')[0].split('error_SPDI_')[1]
    # load file only if not empty:
    if not is_non_zero_file(file):
        continue
    if group_name in ignorable_error_dfs:
        continue
    error_file = pd.read_csv(file, sep="\t", header=None)
    error_file.columns = [col_SPDI, 'error_info', 'error_valid']

    if error_file.shape[0] > 0:
        print(group_name)
        print(file)
        # print(error_file.head())

        current_metadata_file = [file for file in metadata_files if group_name in file.split('/')[-1]]
        print(current_metadata_file)
        error_spdi_rows = []
        # get spdis in error df
        error_spdi_list = error_file[error_file.columns[0]].to_list()
        # concatenate metadata files:
        current_metadata = pd.concat([read_and_eval_metadata(file) for file in current_metadata_file], ignore_index=True)
        # print(current_metadata.head())
        current_metadata_alt = current_metadata.loc[current_metadata[col_allele].apply(hf.is_alternative)].copy()

        # print('metadata size:', current_metadata_alt.shape[0])
        # print('metadata size:', current_metadata_alt[col_SPDI].nunique())

        # print(current_metadata_alt.head())
        # print(current_metadata_alt[col_SPDI].to_list())
        current_metadata_alt[col_SPDI] = current_metadata[col_SPDI].astype(str)
        error_file[col_SPDI] = error_file[col_SPDI].astype(str)
        # filter df for error spdis (left join)

        result = pd.merge(error_file, current_metadata_alt, on=[col_SPDI], how="inner")
        result['group_name'] = group_name
        print(result.shape[0])
        # print(result.head())
        # print start and end of the metadata => create bed file => get reference sequences => find position of indel
        # store group_name_indel.bed
        # result[[col_chr, col_start, col_end, col_SPDI, 'group_name']].to_csv(f'{group_name}_indel.bed', index=False, sep="\t", header=None)

C_positive_heart_CAD
/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/spdi_verification/error_SPDI_C_positive_heart_CAD.tsv
['/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/C_positive_heart_CAD/C_positive_heart_CAD.metadata.tsv.gz']
1
GC_Mendelian_variants
/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/spdi_verification/error_SPDI_GC_Mendelian_variants.tsv
['/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/GC_Mendelian_variants/GC_Mendelian_variants.metadata.tsv.gz']
5
GC_Mohlke
/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/spdi_verification/error_SPDI_GC_Mohlke.tsv
['/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/GC_Mohlke/GC_Mohlke.metadata.tsv.gz']
1

- NC_000008.11:11703889:AG:A	NC_000008.11:11703890:GGGGGGG:GGGGGG
- ref: CGGGGCTGGGAGGATCCCCACTACCCCTGCCCAGGAACTAGCATCCAGCCGGGCACCCCGGGTGACCCAGTGCCCCACACAAGATCGAGAGTTGAGCCCAAGAGGTCACCTTCTTCTCTACTGGCCCCGCCCCTCGCCCGCCGCTGCGGGATGAGGACCACAGGAAGGGGGGGCGGGGAGGGAGAAAGGGAACTCATTAATAAAGCTGACCCTGGGCACCACAGCGAACCCAATCGACCTCCGGCTGGGTTGCGGGTGATTCCCCGCTCC
- alt: CGGGGCTGGGAGGATCCCCACTACCCCTGCCCAGGAACTAGCATCCAGCCGGGCACCCCGGGTGACCCAGTGCCCCACACAAGATCGAGAGTTGAGCCCAAGAGGTCACCTTCTTCTCTACTGGCCCCGCCCCTCGCCCGCCGCTGCGGGATGAGGACCACAGGAAGGGGGGCGGGGAGGGAGAAAGGGAACTCATTAATAAAGCTGACCCTGGGCACCACAGCGAACCCAATCGACCTCCGGCTGGGTTGCGGGTGATTCCCCGCTCCC
- => 165 0-based (start: 11703724) => 11703889
- NC_000008.11:11703889:AG:A	NC_000008.11:11703890:GGGGGGG:GGGGGG
- alt: CCAGGAACTAGCATCCAGCCGGGCACCCCGGGTGACCCAGTGCCCCACACAAGATCGAGAGTTGAGCCCAAGAGGTCACCTTCTTCTCTACTGGCCCCGCCCCTCGCCCGCCGCTGCGGGATGAGGACCACAGGAAGGGGGGCGGGGAGGGAGAAAGGGAACTCATTAATAAAGCTGACCCTGGGCACCACAGCGAACCCAATCGACCTCCGGCTGGGTTGCGGGTGATTCCCCGCTCCCTGGCGGTAGCACTTGGGCATTTTCCGCGGA
- NC_000008.11:11703889:AG:A	NC_000008.11:11703890:GGGGGGG:GGGGGG
- alt: CGGGGCTGGGAGGATCCCCACTACCCCTGCCCAGGAACTAGCATCCAGCCGGGCACCCCGGGTGACCCAGTGCCCCACACAAGATCGAGAGTTGAGCCCAAGAGGTCACCTTCTTCTCTACTGGCCCCGCCCCTCGCCCGCCGCTGCGGGATGAGGACCACAGGAAGGGGGGCGGGGAGGGAGAAAGGGAACTCATTAATAAAGCTGACCCTGGGCACCACAGCGAACCCAATCGACCTCCGGCTGGGTTGCGGGTGATTCCCCGCTCCC
- NC_000008.11:11703889:AG:A	NC_000008.11:11703890:GGGGGGG:GGGGGG
- alt: CCAGGAACTAGCATCCAGCCGGGCACCCCGGGTGACCCAGTGCCCCACACAAGATCGAGAGTTGAGCCCAAGAGGTCACCTTCTTCTCTACTGGCCCCGCCCCTCGCCCGCCGCTGCGGGATGAGGACCACAGGAAGGGGGGCGGGGAGGGAGAAAGGGAACTCATTAATAAAGCTGACCCTGGGCACCACAGCGAACCCAATCGACCTCCGGCTGGGTTGCGGGTGATTCCCCGCTCCCTGGCGGTAGCACTTGGGCATTTTCCGCGGA
- NC_000001.11:209816132:C:CA	NC_000001.11:209816133:AA:AAA
- ref: TTGAGCCCAGGGGCTGAATCTGGAGCTTTGGGGCCTGGGAACCTCTCTACCTGCGTCAATGTCTGGAGGCCCTGAGAGTTTCGCTCAGGCTCAGAGCAGGCATCGCAACCTCCCAGTTACTATTCTGTGCTGTGGCAAGTGCCAGCTTGTCCTCTCTTCCCCACCCAGCCCGGGAAACCGGCAGCATTTCTAGTTCAGGCCCAGACCCGTCCTGGCAGCCTGGATTCCACTGCCTAGGCAGGAAGCTCATCTCAGCCCAGTGACCTTTTC
- alt: TTGAGCCCAGGGGCTGAATCTGGAGCTTTGGGGCCTGGGAACCTCTCTACCTGCGTCAATGTCTGGAGGCCCTGAGAGTTTCGCTCAGGCTCAGAGCAGGCATCGCAACCTCCCAGTTACTATTCTGTGCTGTGGCAAAGTGCCAGCTTGTCCTCTCTTCCCCACCCAGCCCGGGAAACCGGCAGCATTTCTAGTTCAGGCCCAGACCCGTCCTGGCAGCCTGGATTCCACTGCCTAGGCAGGAAGCTCATCTCAGCCCAGTGACCTT
=> 135 0-based (start: 209815997) => 209816132

In [129]:
result

,SPDI,error_info,error_valid,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,allele,info,group_name
0,NC_000001.11:230159328:TCTTAAAGTGTTCAGCACTCCC:T,NC_000001.11:230159329:CTTAAAGTGTTCAGCACTCCCCT:CT,False,GC_Mohlke:ALT_NC000001.11|230158967|C|A|Mohlke...,GTTTACCCAGCCGTGGGAAAGGACGCTGTACCCCTGCCCTATTGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159136,230159406,+,indel,192.0,alt,NaN,GC_Mohlke

In [119]:
base_dir = '/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata'
group_name_list = ['C_positive_heart_CAD', 'GC_Mendelian_variants', 'GC_Mohlke']
print([os.path.join(base_dir, f'{group_name}_indel.bed') for group_name in group_name_list])
indel_bed_file = pd.concat([pd.read_csv(os.path.join(base_dir, f'{group_name}_indel.bed'), sep="\t", header=None) for group_name in group_name_list])
indel_bed_file.columns = ['chr', 'start', 'end', 'name', 'group']

['/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/C_positive_heart_CAD_indel.bed', '/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/GC_Mendelian_variants_indel.bed', '/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/GC_Mohlke_indel.bed']

In [122]:
indel_bed_file[['chr', 'start', 'end', 'name']].to_csv('80K_indel_bed.bed', sep='\t', index=False, header=None)

### Solve by hand
/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/GC_Mendelian_variants/GC_Mendelian_variants.metadata.tsv.gz
/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/GC_Mohlke/GC_Mohlke.metadata.tsv.gz
/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/C_positive_heart_CAD/C_positive_heart_CAD.metadata.tsv.gz

- C_positive_heart_CAD
- 135 zero based (compare to the bed file)
- start + 135 => 201917640
- is the correct position: https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1%3A201917640%2D201917650&hgsid=347309970_CdGL5A7oNaEACHjM4ebivIe8Qek2

In [125]:
# C_positive_heart_CAD
group_name = 'C_positive_heart_CAD'
current_metadata_file = '/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/C_positive_heart_CAD/C_positive_heart_CAD.metadata.tsv.gz'
error_file_path = '/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/spdi_verification/error_SPDI_C_positive_heart_CAD.tsv'

error_file = pd.read_csv(error_file_path, sep="\t", header=None)
error_file.columns = [col_SPDI, 'error_info', 'error_valid']


# concatenate metadata files:
current_metadata = read_and_eval_metadata(current_metadata_file)
# print(current_metadata.head())
current_metadata_alt = current_metadata.loc[current_metadata[col_allele].apply(hf.is_alternative)].copy()

# filter df for error spdis (left join)

# filter df for error spdis (left join)
result = pd.merge(error_file, current_metadata_alt, on=[col_SPDI], how="inner")
result.sequence.to_list()
result
# CTTCTCGGCCAATGAAGGGTCAACTCCATTGCTCTCAGCAGAACTAAATGCTTTGCCAACTGGTCTGGTGACTCATACTGGGAAGCTTGTAGCAAACCCCATTTTTGGAGAAACCGGGAAATCTCTTTGGGGAGATAAAACAAGTCACTGTAGCACTCTGCTCTCTGAAGTGCCTGGCTAGTACTTTCTGCTTCTTCATTTTATCCCAGCACCAAGGAAAACCCAAGCAAGTCTGGGAAATGTTGTAAAGATCTACACAAATGCAAGC
# 135 zero based (compare to the bed file)
# start + 135 => 201917640
# is the correct position: https://genome-euro.ucsc.edu/cgi-bin/hgTracks?db=hg38&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr1%3A201917640%2D201917650&hgsid=347309970_CdGL5A7oNaEACHjM4ebivIe8Qek2

,SPDI,error_info,error_valid,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,allele,info
0,NC_000001.11:201917640:T:TA,NC_000001.11:201917641:AAA:AAAA,False,C_positive_heart_CAD:ALT_rs34091558_rs34091558,CTTCTCGGCCAATGAAGGGTCAACTCCATTGCTCTCAGCAGAACTA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,201917505,201917775,.,indel,136.0,[alt],NaN

- mohlke: NC_000001.11:230159328:TCTTAAAGTGTTCAGCACTCCC:T: info: NC_000001.11:230159329:CTTAAAGTGTTCAGCACTCCCCT:CT
ref: 
- GTTTACCCAGCCGTGGGAAAGGACGCTGTACCCCTGCCCTATTGGCTGCACCCTTTGCTGTTGATGTGAGGCTTTATTTACCTGGGAATTGACAGGGTTTTGGTCCATGATTGCTCCTTTCTCCGCAATCACATTTAATGCCCATGATATCTCATCTTTGCACACGAAGGCAAAGCCTTCTACTGCTTTTTCTCTTAAAGTGTTCAGCACTCCCCTGAGTTTATTAGAAGGATCAGAAGAAAGAGACCCTGAGTGTGAGGCTAGGTCAAC
- alt: GTTTACCCAGCCGTGGGAAAGGACGCTGTACCCCTGCCCTATTGGCTGCACCCTTTGCTGTTGATGTGAGGCTTTATTTACCTGGGAATTGACAGGGTTTTGGTCCATGATTGCTCCTTTCTCCGCAATCACATTTAATGCCCATGATATCTCATCTTTGCACACGAAGGCAAAGCCTTCTACTGCTTTTTCTCTGAGTTTATTAGAAGGATCAGAAGAAAGAGACCCTGAGTGTGAGGCTAGGTCAACCGGAGAAATTCACCCAATTAT

In [55]:
test = ['/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/neuro_controls/C_negative_neuron_NP.metadata.tsv.gz', '/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/neuro_controls/neuro_controls.metadata.tsv.gz', '/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/neuro_controls/C_positive_neuron_NP.metadata.tsv.gz', '/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/neuro_controls/C_positive_neuron_CD.metadata.tsv.gz', '/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/neuro_controls/C_positive_heart_MK.metadata.tsv.gz', '/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/neuro_controls/C_negative_heart_MK.metadata.tsv.gz', '/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/neuro_controls/C_positive_neuron_MK.metadata.tsv.gz', '/home/kisa/coding/80K_MPRA/MPRAOligoDesign/resources/controls/neuro_controls/C_negative_neuron_MK.metadata.tsv.gz']
[read_and_eval_metadata(file) for file in current_metadata_file]

217
1086
99
96
97
243
100
234

[                                                  name  \
 0    C_negative_neuron_NP:GW18_PFC_ABC_chr15_894002...
 1    C_negative_neuron_NP:NGN2_iPSC_ABC_chr4_112626...
 2    C_negative_neuron_NP:Midfetal_Cortex_Trevino_c...
 3    C_negative_neuron_NP:NGN2_iPSC_ABC_chr2_275913...
 4    C_negative_neuron_NP:Fetal_Cerebrum_Cicero_chr...
 ..                                                 ...
 212  C_negative_neuron_NP:NGN2_iPSC_ABC_chr3_427240...
 213  C_negative_neuron_NP:GW18_PFC_ABC_chr11_133690...
 214  C_negative_neuron_NP:NGN2_iPSC_ABC_chr15_32862...
 215  C_negative_neuron_NP:GW18_PFC_ABC_Midfetal_Cor...
 216  C_negative_neuron_NP:GW18_PFC_ABC_chr4_6245249...

                                               sequence category  \
 0    AGGCGCGATACGAACCCGTGGGAGCCTCCCCAACCCCGCAGTCCCA...  element
 1    CGAAAAGTGTGTGAAGTGTGAATTATATCTCAATAAAGCTGTTAAA...  element
 2    GGCTGAGAGGCCTGATTCCTTCCACGCATCACAACCTGAAAATCGC...  element
 3    CATCTGTACTGACGACGGAATCCCAGCAGGACACCTTCACTCACTT...  element
 4    TCTCCGCCCAGGGCAGCAGCGCGCGGGGCCCCCGGGAGCCGAAGAG...  element
 ..                                                 ...      ...
 212  CTTCACATCCTCACATCAACCAGCCGTTGGATACAGGCTGTCCATG...  element
 213  GGCCCTCAGGTGTCTCGAGATGGCCCGGGCTCCGAGCGCTCCCGGC...  element
 214  GGAGACCTGAAGGCTAATTAATGATGACACCGGAGACTGGCAGTGC...  element
 215  CCCCCACCATGCCCTCCTTTTCCTAACTGGGCTGAGGGAGGCTGTT...  element
 216  GAGCTGGGAAAGCCAGAAGCCAGCGCAGCGCGTGCATCTGAGAGTC...  element

                         class     source     ref    chr        start  \
 0    element inactive control  Nick Page  GRCh38  chr15   89400286.0
 1    element inactive control  Nick Page  GRCh38   chr4  112626228.0
 2    element inactive control  Nick Page  GRCh38  chr20   63366571.0
 3    element inactive control  Nick Page  GRCh38   chr2    2759136.0
 4    element inactive control  Nick Page  GRCh38  chr20   63177767.0
 ..                        ...        ...     ...    ...          ...
 212  element inactive control  Nick Page  GRCh38   chr3    4272406.0
 213  element inactive control  Nick Page  GRCh38  chr11    1336905.0
 214  element inactive control  Nick Page  GRCh38  chr15   32862132.0
 215  element inactive control  Nick Page  GRCh38   chr1  164588833.0
 216  element inactive control  Nick Page  GRCh38   chr4    6245249.0

              end strand variant_class variant_pos  SPDI allele  info
 0     89400556.0      .          None        None  None   None   NaN
 1    112626498.0      .          None        None  None   None   NaN
 2     63366841.0      .          None        None  None   None   NaN
 3      2759406.0      .          None        None  None   None   NaN
 4     63178037.0      .          None        None  None   None   NaN
 ..           ...    ...           ...         ...   ...    ...   ...
 212    4272676.0      .          None        None  None   None   NaN
 213    1337175.0      .          None        None  None   None   NaN
 214   32862402.0      .          None        None  None   None   NaN
 215  164589103.0      .          None        None  None   None   NaN
 216    6245519.0      .          None        None  None   None   NaN

 [217 rows x 15 columns],
                                                    name  \
 0     C_positive_neuron_CD:c1_NA_NA_NA_NA::72hr_top_...
 1     C_negative_heart_MK:tile_6903_chr11_9614045_96...
 2     C_negative_heart_MK:tile_35543_chr5_173245685_...
 3     C_negative_heart_MK:tile_36416_chr6_35490266_3...
 4     C_negative_heart_MK:tile_16405_chr16_58119639_...
 ...                                                 ...
 1081  C_positive_neuron_NP:GW18_PFC_ABC_chr12_121536...
 1082  C_positive_neuron_NP:NGN2_iPSC_ABC_chr4_850290...
 1083  C_positive_neuron_NP:GW18_PFC_ABC_NGN2_iPSC_AB...
 1084  C_positive_neuron_NP:Fetal_Cerebrum_Cicero_GW1...
 1085  C_positive_neuron_NP:GW18_PFC_ABC_chr1_1690485...

                                                sequence   category  \
 0     CCTTTCCTTCTTACTAGGTGTACCAGGTGTCATGGCCACCTCCAGA...  scrambled
 1     GAGCGTCTGGGGAGAGCGGGGCGGGGATAGAAGGAGGTGTTGGGGC...    element
 2     AGAGGAGTATCAGCGCGCGCACCAAATCTGCTCTGGTATGTCACCT...    element
 3     GCAGGCTTGGGAGCTGGGACAGACTGGGGGGGCGGGGCAGGCGGCC...    element
 4     GATTCTCAAACAAAGCTGGCAATGTTCAATGCCCTCCTGCTTTGAA...    element
 ...                                                 ...        ...
 1081  GCAGCGCGCCGGCACGAGTGGAGATAATGCGGGGAGTGGGGCTGAG...    element
 1082  TAACAGATGAAGCCTCAATTAGGTAGCTAGCCACTCTATTCTATAG...    element
 1083  CCGAGACCCGCACTTAGTTACCTGAGAAGGCGGGAAGGTGCGGCCG...    element
 1084  CAGCTCCAGCGGCATGAAATATTGATGCCCTGAGACTTTCCAGAGT...    element
 1085  GCGGACGTCACTTCCCCCGCCGGCTGCGGCACCGGGTTGGTGGGCT...    element

                          class           source     ref    chr        start  \
 0       element active control              NaN  GRCh38    NaN          NaN
 1     element inactive control  Michael Kosicki  GRCh38  chr11    9614044.0
 2     element inactive control  Michael Kosicki  GRCh38   chr5  173245684.0
 3     element inactive control  Michael Kosicki  GRCh38   chr6   35490265.0
 4     element inactive control  Michael Kosicki  GRCh38  chr16   58119638.0
 ...                        ...              ...     ...    ...          ...
 1081    element active control        Nick Page  GRCh38  chr12  121536100.0
 1082    element active control        Nick Page  GRCh38   chr4   85029018.0
 1083    element active control        Nick Page  GRCh38   chr4     781750.0
 1084    element active control        Nick Page  GRCh38   chr1  110538278.0
 1085    element active control        Nick Page  GRCh38   chr1   16904850.0

               end strand variant_class  variant_pos  SPDI allele  \
 0             NaN    NaN          None          NaN  None   None
 1       9614314.0      .          None          NaN  None   None
 2     173245954.0      .          None          NaN  None   None
 3      35490535.0      .          None          NaN  None   None
 4      58119908.0      .          None          NaN  None   None
 ...           ...    ...           ...          ...   ...    ...
 1081  121536370.0      .          None          NaN  None   None
 1082   85029288.0      .          None          NaN  None   None
 1083     782020.0      .          None          NaN  None   None
 1084  110538548.0      .          None          NaN  None   None
 1085   16905120.0      .          None          NaN  None   None

                                           info
 0     ; Information not restorable from header
 1                                          NaN
 2                                          NaN
 3                                          NaN
 4                                          NaN
 ...                                        ...
 1081                                       NaN
 1082                                       NaN
 1083                                       NaN
 1084                                       NaN
 1085                                       NaN

 [1086 rows x 15 columns],
                                                  name  \
 0   C_positive_neuron_NP:GW18_PFC_ABC_chr5_6873074...
 1   C_positive_neuron_NP:GW18_PFC_ABC_chr5_6873083...
 2   C_positive_neuron_NP:NGN2_iPSC_ABC_chrX_743252...
 3   C_positive_neuron_NP:GW18_PFC_ABC_NGN2_iPSC_AB...
 4   C_positive_neuron_NP:NGN2_iPSC_ABC_chr10_88387...
 ..                                                ...
 94  C_positive_neuron_NP:GW18_PFC_ABC_chr12_121536...
 95  C_positive_neuron_NP:NGN2_iPSC_ABC_chr4_850290...
 96  C_positive_neuron_NP:GW18_PFC_ABC_NGN2_iPSC_AB...
 97  C_positive_neuron_NP:Fetal_Cerebrum_Cicero_GW1...
 98  C_positive_neuron_NP:GW18_PFC_ABC_chr1_1690485...

                                              sequence category  \
 0   CTTTAAAAATGCAGATAGGAATATCAGACCTAGAAGTTTTCTGTGC...  element
 1   CTTTGTAACGGAAATTGGCTCTGATTTCTGAGATGGGCATTACATC...  element
 2   TGCCCCAGAGATCAGCTTTTCAAGAACAGGCATCTGAGACAGAGTG...  element
 3   CAAGTTGAAAATGTGACAAAGCTCAATTTCATTTCTTGTTTATTGC...  element
 4   CCGGAAGCCTTAAGTATTTGGAACTGCTCCAAACCCAGAAGAGGGG...  element
 ..                                                ...      ...
 94  GCAGCGCGCCGGCACGAGTGGAGATAATGCGGGGAGTGGGGCTGAG...  element
 95  TAACAGATGAAGCCTCAATTAGGTAGCTAGCCACTCTATTCTATAG...  element
 96  CCGAGACCCGCACTTAGTTACCTGAGAAGGCGGGAAGGTGCGGCCG...  element
 97  CAGCTCCAGCGGCATGAAATATTGATGCCCTGAGACTTTCCAGAGT...  element
 98  GCGGACGTCACTTCCCCCGCCGGCTGCGGCACCGGGTTGGTGGGCT...  element

                      class     source     ref    chr      start        end  \
 0   element active control  Nick Page  GRCh38   chr5   68730744   68731014
 1   element active control  Nick Page  GRCh38   chr5   68730834   68731104
 2   element active control  Nick Page  GRCh38   chrX   74325294   74325564
 3   element active control  Nick Page  GRCh38  chr21   37435137   37435407
 4   element active control  Nick Page  GRCh38  chr10   88387160   88387430
 ..                     ...        ...     ...    ...        ...        ...
 94  element active control  Nick Page  GRCh38  chr12  121536100  121536370
 95  element active control  Nick Page  GRCh38   chr4   85029018   85029288
 96  element active control  Nick Page  GRCh38   chr4     781750     782020
 97  element active control  Nick Page  GRCh38   chr1  110538278  110538548
 98  element active control  Nick Page  GRCh38   chr1   16904850   16905120

    strand variant_class variant_pos  SPDI allele  info
 0       .          None        None  None   None   NaN
 1       .          None        None  None   None   NaN
 2       .          None        None  None   None   NaN
 3       .          None        None  None   None   NaN
 4       .          None        None  None   None   NaN
 ..    ...           ...         ...   ...    ...   ...
 94      .          None        None  None   None   NaN
 95      .          None        None  None   None   NaN
 96      .          None        None  None   None   NaN
 97      .          None        None  None   None   NaN
 98      .          None        None  None   None   NaN

 [99 rows x 15 columns],
                                                  name  \
 0   C_positive_neuron_CD:c1_NA_NA_NA_NA::72hr_top_...
 1   C_positive_neuron_CD:c1_NA_NA_NA_NA::72hr_top_...
 2   C_positive_neuron_CD:p1_rs6813360_A_C_ref_50_A...
 3   C_positive_neuron_CD:p1_rs55985730_T_G_alt_50_...
 4   C_positive_neuron_CD:c1_NA_NA_NA_NA::72hr_top_...
 ..                                                ...
 91  C_positive_neuron_CD:p1_rs8049948_A_G_ref_50_A...
 92  C_positive_neuron_CD:p1_rs6791336_T_C_ref_50_T...
 93  C_positive_neuron_CD:p1_rs4982404_C_T_ref_50_C...
 94  C_positive_neuron_CD:p2_rs9926320_G_A_ref_25_A...
 95  C_positive_neuron_CD:n1_rs7214382_G_C_alt_50::...

                                              sequence   category  \
 0   CCTTTCCTTCTTACTAGGTGTACCAGGTGTCATGGCCACCTCCAGA...  scrambled
 1   TCTGGTTCAGAACAGCTTCCAGCAGGTTCCTGTGGGAGGGATGGGG...  scrambled
 2   GATTGTATAAAGAAAATGTGTATACACACACACACACACACACACA...    variant
 3   GGCGCCTGTAGTCCCAGCTACTTGGGAGGCTGAGGCAGGAGAATGG...    variant
 4   CTCCCCCGCACAGCGCAGGCTCTCACTGGGAATCTGCCGGGACCGC...  scrambled
 ..                                                ...        ...
 91  GTGGCTTAGGACTCTGTTTCCTTACCTGTAAAATGAGCAACATAAC...    variant
 92  AATATGTACATTAATTTTTGTGTTTTACACATATTTTTGATGTTAC...    variant
 93  AGGGGGAGCTCACCGCAGGGAGTGGAGGAGGGGCAGGGGCACTACT...    variant
 94  GTTTGCAGAGTGGGTGTGGTGCCGGAGCACAGGAGCACCTCTTCTG...    variant
 95  GGACATCCCCAGGGACCCCACCAGCCCGGCCCGTAGCCCAGCGGTG...    variant

                        class        source     ref    chr        start  \
 0     element active control           NaN  GRCh38    NaN          NaN
 1     element active control           NaN  GRCh38    NaN          NaN
 2   variant positive control  Chengyu Deng  GRCh38   chr4  155359187.0
 3   variant positive control  Chengyu Deng  GRCh38   chr7  128776855.0
 4     element active control           NaN  GRCh38    NaN          NaN
 ..                       ...           ...     ...    ...          ...
 91  variant positive control  Chengyu Deng  GRCh38  chr16   65064289.0
 92  variant positive control  Chengyu Deng  GRCh38   chr3  131059364.0
 93  variant positive control  Chengyu Deng  GRCh38  chr14   21071390.0
 94  variant positive control  Chengyu Deng  GRCh38  chr16   69094082.0
 95  variant positive control  Chengyu Deng  GRCh38  chr17   33292592.0

             end strand variant_class  variant_pos                        SPDI  \
 0           NaN    NaN          None          NaN                        None
 1           NaN    NaN          None          NaN                        None
 2   155359457.0      .           SNV          NaN                        None
 3   128777125.0      .           SNV        134.0  NC_000007.14:128776989:T:G
 4           NaN    NaN          None          NaN                        None
 ..          ...    ...           ...          ...                         ...
 91   65064559.0      .           SNV          NaN                        None
 92  131059634.0      .           SNV          NaN                        None
 93   21071660.0      .           SNV          NaN                        None
 94   69094352.0      .           SNV          NaN                        None
 95   33292862.0      .           SNV        134.0   NC_000017.11:33292726:G:C

    allele                                               info
 0    None           ; Information not restorable from header
 1    None           ; Information not restorable from header
 2     ref  possible reference but no alternative assigned...
 3     alt  possible alternative but no reference assigned...
 4    None           ; Information not restorable from header
 ..    ...                                                ...
 91    ref  possible reference but no alternative assigned...
 92    ref  possible reference but no alternative assigned...
 93    ref  possible reference but no alternative assigned...
 94    ref  possible reference but no alternative assigned...
 95    alt  possible alternative but no reference assigned...

 [96 rows x 15 columns],
                                                  name  \
 0   C_positive_heart_MK:tile_7939_chr11_65487592_6...
 1   C_positive_heart_MK:tile_7938_chr11_65487464_6...
 2   C_positive_heart_MK:tile_7940_chr11_65487692_6...
 3   C_positive_heart_MK:tile_5436_chr10_79221252_7...
 4   C_positive_heart_MK:tile_6898_chr11_9613179_96...
 ..                                                ...
 92  C_positive_heart_MK:tile_36383_chr6_30842134_3...
 93  C_positive_heart_MK:tile_480_chr1_11887300_118...
 94  C_positive_heart_MK:tile_27242_chr22_37998728_...
 95  C_positive_heart_MK:tile_37608_chr6_111551191_...
 96  C_positive_heart_MK:rdhs_632456_chr7_42125376_...

                                              sequence category  \
 0   TCTGGTTCAGAACAGCTTCCAGCAGGTTCCTGTGGGAGGGATGGGG...  element
 1   AAATGGCTGACAGCCTCTTCTGCCTTCAGAAAAGTACTTCAACTGC...  element
 2   CAGATTTCGGTGGCAAGAGGAAGGTGGCAGCCAATGAAGAGGCTCG...  element
 3   ATGTGCGTGCATGCATGCGTGTGTGTGTGTGCGTGTGTGTGTCCTG...  element
 4   CATAGTTCATCTTTTCTTACTGCCGTGTTTGGGAATGTTATTTTAC...  variant
 ..                                                ...      ...
 92  GCATTAATAAACCAGAGATCATAAGACTGACAGAACAAAGTATTTG...  element
 93  CCACCGGCCATTGGGCGGTCCCATGCGCCCTGCAGGCTGACCTCAT...  element
 94  AGAACAAGGGGCCCATTCTGTGTGTGGGAATTAATAGCAAAGAGTC...  element
 95  CCGAGCACAGGCTGCTGCTTGACGCGCAGCCCTCAGCTGGCTGGCC...  element
 96  AAGGCAGTCATCTGCTCCCCCAAGTCTTGCTAGCAGAGTTACATCA...  element

                        class           source     ref    chr      start  \
 0   element inactive control  Michael Kosicki  GRCh38  chr11   65487591
 1   element inactive control  Michael Kosicki  GRCh38  chr11   65487463
 2   element inactive control  Michael Kosicki  GRCh38  chr11   65487691
 3   element inactive control  Michael Kosicki  GRCh38  chr10   79221251
 4   variant negative control  Michael Kosicki  GRCh38  chr11    9613178
 ..                       ...              ...     ...    ...        ...
 92  element inactive control  Michael Kosicki  GRCh38   chr6   30842133
 93  element inactive control  Michael Kosicki  GRCh38   chr1   11887299
 94  element inactive control  Michael Kosicki  GRCh38  chr22   37998727
 95  element inactive control  Michael Kosicki  GRCh38   chr6  111551190
 96  element inactive control  Michael Kosicki  GRCh38   chr7   42125375

           end strand variant_class  variant_pos                      SPDI  \
 0    65487861      .          None          NaN                      None
 1    65487733      .          None          NaN                      None
 2    65487961      .          None          NaN                      None
 3    79221521      .          None          NaN                      None
 4     9613448      .           SNV        260.0  NC_000011.10:9613438:T:A
 ..        ...    ...           ...          ...                       ...
 92   30842403      .          None          NaN                      None
 93   11887569      .          None          NaN                      None
 94   37998997      .          None          NaN                      None
 95  111551460      .          None          NaN                      None
 96   42125645      .          None          NaN                      None

    allele                  info
 0    None                   NaN
 1    None                   NaN
 2    None                   NaN
 3    None                   NaN
 4     alt  ; No reference given
 ..    ...                   ...
 92   None                   NaN
 93   None                   NaN
 94   None                   NaN
 95   None                   NaN
 96   None                   NaN

 [97 rows x 15 columns],
                                                   name  \
 0    C_negative_heart_MK:tile_6903_chr11_9614045_96...
 1    C_negative_heart_MK:tile_35543_chr5_173245685_...
 2    C_negative_heart_MK:tile_36416_chr6_35490266_3...
 3    C_negative_heart_MK:tile_16405_chr16_58119639_...
 4    C_negative_heart_MK:tile_27236_chr22_37986181_...
 ..                                                 ...
 238  C_negative_heart_MK:tile_173_chr1_3345764_3346...
 239  C_negative_heart_MK:tile_34344_chr5_112577066_...
 240  C_negative_heart_MK:tile_36077_chr6_15953270_1...
 241  C_negative_heart_MK:tile_27871_chr3_38581227_3...
 242  C_negative_heart_MK:tile_33791_chr5_89253269_8...

                                               sequence category  \
 0    GAGCGTCTGGGGAGAGCGGGGCGGGGATAGAAGGAGGTGTTGGGGC...  element
 1    AGAGGAGTATCAGCGCGCGCACCAAATCTGCTCTGGTATGTCACCT...  element
 2    GCAGGCTTGGGAGCTGGGACAGACTGGGGGGGCGGGGCAGGCGGCC...  element
 3    GATTCTCAAACAAAGCTGGCAATGTTCAATGCCCTCCTGCTTTGAA...  element
 4    AGAGGAGCCGCCCTGGATGGACAGAGGGACGAGGGACGAGCATCTG...  element
 ..                                                 ...      ...
 238  TCCTCCCGTGCTGCCCCCTCTGTGGTCCAGGCCACCCCTTGGTTCC...  element
 239  ACAAGGCCTCAGGTAATGCTAATGCTTGTGTGCCATGGCCCACACT...  element
 240  AGTAAGGAGGGAATATGGAGTTGATTATTTTATAATTAAAGAAGAC...  element
 241  AGGTGGTCCGCTTGACAAAGCGCAGGCCCCTCTGGATGCGGGCCAG...  element
 242  GTGTTAATCATTTGGGTATGTCCAAACACTTGATCGAAGGTTCACA...  element

                         class           source     ref    chr      start  \
 0    element inactive control  Michael Kosicki  GRCh38  chr11    9614044
 1    element inactive control  Michael Kosicki  GRCh38   chr5  173245684
 2    element inactive control  Michael Kosicki  GRCh38   chr6   35490265
 3    element inactive control  Michael Kosicki  GRCh38  chr16   58119638
 4    element inactive control  Michael Kosicki  GRCh38  chr22   37986180
 ..                        ...              ...     ...    ...        ...
 238  element inactive control  Michael Kosicki  GRCh38   chr1    3345763
 239  element inactive control  Michael Kosicki  GRCh38   chr5  112577065
 240  element inactive control  Michael Kosicki  GRCh38   chr6   15953269