## Notebook showing the general numbers of the MPRA dataset
- Loads sequencing replicates
- Filters with thresholds
- Merge replicates

In [2]:
import pandas as pd
import numpy as np
import os
import yaml
import re


# load helpful functions
import sys
sys.path.append('../../00_helpful_functions')
import helpful_functions as hf

# config
config_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/global80K_config.yaml"
with open(config_path) as conf:
    config = yaml.load(conf, Loader=yaml.FullLoader)
    conf.close()

_total_number_oligos = config["analysis_info"]["total_number_oligos"]

### Check MPRAsnakeflow results and merge the filtered replicates based on the assignment file
#### Investigate assignment file

In [3]:
def get_assignment_ratio(assignment_numbers):
    """
    Gets assignment numbers from the assignment file (e.g. 9/11) and returns their ratio 0.82
    """
    assigned_barcodes = int(assignment_numbers.split("/")[0])
    found_barcodes = int(assignment_numbers.split("/")[1])
    return round(assigned_barcodes/found_barcodes, 4)

def get_found_barcode_number(assignment_numbers):
    """
    Gets assignment numbers from the assignment file (e.g. 9/11) and returns their ratio 0.82
    """
    found_barcodes = int(assignment_numbers.split("/")[1])
    return found_barcodes

def get_assignment_barcode_number(assignment_numbers):
    """
    Gets assignment numbers from the assignment file (e.g. 9/11) and returns their ratio 0.82
    """
    assigned_barcodes = int(assignment_numbers.split("/")[0])
    return assigned_barcodes

# combine mprasnakeflow result
def combine_replicates(df_allreps, total_dna_counts, total_rna_counts):
    df_allreps = df_allreps.groupby(by=["condition", "name"]).aggregate(
        {
            "replicate": "count",
            "dna_counts": ["sum", "mean"],
            "rna_counts": ["sum", "mean"],
            "dna_normalized": "mean",
            "rna_normalized": "mean",
            "ratio": "mean",
            "log2": "mean",
            "n_obs_bc": ["sum", "mean"],
        }
    )

    df_allreps = df_allreps.reset_index()
    df_out = df_allreps.iloc[:, 0:2]
    df_out.columns = ["condition", "name"]

    df_out["replicates"] = df_allreps.replicate["count"]

    scaling = 10**6

    df_out["dna_counts"] = df_allreps.dna_counts["sum"]
    df_out["rna_counts"] = df_allreps.rna_counts["sum"]


    df_out["dna_normalized"] = df_out["dna_counts"] / total_dna_counts * scaling
    df_out["rna_normalized"] = df_out["rna_counts"] / total_rna_counts * scaling

    df_out["ratio"] = df_out["rna_normalized"] / df_out["dna_normalized"]
    df_out["log2"] = np.log2(df_out.ratio)

    df_out["mean_dna_counts"] = df_allreps.dna_counts["mean"]
    df_out["mean_rna_counts"] = df_allreps.rna_counts["mean"]
    df_out["mean_dna_normalized"] = df_allreps.dna_normalized["mean"]
    df_out["mean_rna_normalized"] = df_allreps.rna_normalized["mean"]
    df_out["mean_ratio"] = df_allreps.ratio["mean"]
    df_out["mean_log2"] = df_allreps.log2["mean"]

    df_out["mean_n_obs_bc"] = df_allreps.n_obs_bc["mean"].apply(int)
    return df_out

In [4]:
# load assignemnt file
assignemnt_file = pd.read_csv(config['files']['final_design']['assignment_file'], sep="\t", header=None)
assignemnt_file.columns = ['barcode', 'name', 'alignment_info', 'assignment_number']

In [5]:
assignemnt_file = assignemnt_file.assign(assignment_ratio = assignemnt_file['assignment_number'].apply(get_assignment_ratio))
assignemnt_file = assignemnt_file.assign(assigned_barcodes_number = assignemnt_file['assignment_number'].apply(get_assignment_barcode_number))
assignemnt_file = assignemnt_file.assign(found_barcodes_number = assignemnt_file['assignment_number'].apply(get_found_barcode_number))

In [6]:
print(f"Number of barcodes assigned: {assignemnt_file.shape[0]}")

Number of barcodes assigned: 6305466

In [7]:
assignemnt_file.head()

,barcode,name,alignment_info,assignment_number,assignment_ratio,assigned_barcodes_number,found_barcodes_number
0,AAAAAAAAAAACGTC,GC_Vista:eye;fb;hb;mb_hs1644_vistaElementContr...,15;270M;NM:i:0;MD:Z:270;60,5/5,1.0000,5,5
1,AAAAAAAAAACAAGT,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,6/7,0.8571,6,7
2,AAAAAAAAAACACCA,cardiac_neuro_cava_random:ALT_FTO|ENSG00000140...,15;270M;NM:i:0;MD:Z:270;6,9/10,0.9000,9,10
3,AAAAAAAAAACCTCG,cardiac_neuro_cava_random:REF_FKRP|ENSG0000018...,15;270M;NM:i:0;MD:Z:270;6,7/7,1.0000,7,7
4,AAAAAAAAAAGCTGG,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,7/8,0.8750,7,8

In [8]:
print(f"Minimal number of assignment_ratio: {assignemnt_file['assignment_ratio'].min()}") # 0.7
print(f"Minimal number of assigned_barcodes_number: {assignemnt_file['assigned_barcodes_number'].min()}") # 3
print(f"Minimal number of found_barcodes_number: {assignemnt_file['found_barcodes_number'].min()}") # 3

Minimal number of assignment_ratio: 0.7
Minimal number of assigned_barcodes_number: 3
Minimal number of found_barcodes_number: 3

#### Merge Assignment files with the replicates
1. merge with assignment file
2. compute n_obs for each replicate

In [9]:
# load replicate files

# example workflow for one replicate
replicate_1 = pd.read_csv(config['files']['final_design']['barcodes_rep1'], sep="\t", header=None)
replicate_1.columns = ['barcode', 'dna_counts', 'rna_counts']
replicate_1['replicate'] = 1

print(f"Number of barcodes in replicate 1: {replicate_1['barcode'].nunique()}")
# print(f"Number of barcodes in replicate 1: {replicate_1.shape[0]}")

# same for replicate 2
replicate_2 = pd.read_csv(config['files']['final_design']['barcodes_rep2'], sep="\t", header=None)
replicate_2.columns = ['barcode', 'dna_counts', 'rna_counts']
replicate_2['replicate'] = 2

print(f"Number of barcodes in replicate 2: {replicate_2['barcode'].nunique()}")
# print(f"Number of barcodes in replicate 2: {replicate_2.shape[0]}")

# and 3
replicate_3 = pd.read_csv(config['files']['final_design']['barcodes_rep3'], sep="\t", header=None)
replicate_3.columns = ['barcode', 'dna_counts', 'rna_counts']
replicate_3['replicate'] = 3

print(f"Number of barcodes in replicate 3: {replicate_3['barcode'].nunique()}")
# print(f"Number of barcodes in replicate 3: {replicate_3.shape[0]}")

# Number of barcodes in replicate 1: 4695996
# Number of barcodes in replicate 2: 4704637
# Number of barcodes in replicate 3: 4734536

Number of barcodes in replicate 1: 4695996
Number of barcodes in replicate 2: 4704637
Number of barcodes in replicate 3: 4734536

In [10]:
# merge with assignment file
replicate_1_assignment = pd.merge(replicate_1, assignemnt_file[['barcode', 'name', 'assignment_number']], on='barcode', how='left')

# merge with assignment file
replicate_2_assignment = pd.merge(replicate_2, assignemnt_file[['barcode', 'name', 'assignment_number']], on='barcode', how='left')

# merge with assignment file
replicate_3_assignment = pd.merge(replicate_3, assignemnt_file[['barcode', 'name', 'assignment_number']], on='barcode', how='left')

In [11]:
replicate_1_assignment.loc[replicate_1_assignment['assignment_number'].isna()] # all can be matched

Empty DataFrame
Columns: [barcode, dna_counts, rna_counts, replicate, name, assignment_number]
Index: []

In [12]:
replicate_1_assignment.loc[replicate_1_assignment['name'] == 'cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000181722.18|EH38E2228539_rev_tile1-1_ZBTB20|ENSG00000181722.18|EH38E2228539|3-114510161-A-G'].shape[0]

45

:

In [56]:
# compute n_obs: groupby name and count the number of barcodes
replicate_1_assignment['n_obs_bc'] = replicate_1_assignment.groupby('name')['barcode'].transform('count')

In [57]:
replicate_1_assignment.loc[replicate_1_assignment['name'] == 'cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000181722.18|EH38E2228539_rev_tile1-1_ZBTB20|ENSG00000181722.18|EH38E2228539|3-114510161-A-G']

,barcode,dna_counts,rna_counts,replicate,name,assignment_number,n_obs_bc
1,AAAAAAAAAACAAGT,1,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,6/7,45
1876,AAAAACTATCGCCTA,3,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,22/23,45
27289,AAACTACTAGCGGAT,2,2,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,4/4,45
55420,AAATCTGTTTTGTCA,1,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,6/7,45
148447,AAGCCCCTATATGTT,4,5,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,23/24,45
168281,AAGGCGTGGTCGTTA,4,11,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,11/15,45
575334,AGAGGCGAACCTATT,8,6,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,42/44,45
635666,AGCCTTGAGAAACGA,4,9,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,49/57,45
733715,AGGGGGTCCCTCGTT,4,4,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,24/25,45
996572,ATGAGTGTCCCGGAA,8,7,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,47/50,45
1079690,ATTAGCCAGTAACAA,3,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,9/10,45
1086206,ATTATGTGTCTCAGC,1,5,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,15/15,45
1088143,ATTCAATAGGGGCGC,1,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,15/15,45
1125700,ATTTAAACGTGCGTT,2,5,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,14/15,45
1187758,CAATCAAAACACCAT,1,2,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,3/4,45
1242389,CACTGGAGAAACAGT,1,2,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,12/12,45
1297856,CAGTATGCCGAGTGC,6,4,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,11/13,45
1307526,CAGTTCAATGGCTAG,4,2,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,21/21,45
1314583,CATACACCCTCCGAT,1,4,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,13/14,45
1402772,CCAGGCCTACATTGG,1,2,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,17/18,45
1744022,CGGGTGCCCCAATAA,2,6,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,14/15,45
1849267,CTACGCAGAACTGTC,3,5,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,22/24,45
1946771,CTGAGTGCGGGACGA,6,8,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,24/25,45
2133459,GAATCAAGCGACTAG,2,4,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,15/16,45
2147627,GAATTTGACATCAGG,5,5,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,27/29,45
2316301,GATAACGGATCTGTC,4,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,14/14,45
2416923,GCACAATCTGACGAA,5,6,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,21/21,45
2656504,GCTATCGGTGCATAC,2,5,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,23/24,45
2787139,GGAGTCTCCCCTTTC,2,2,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,14/15,45
2862727,GGCGAGCTGACTGAA,1,2,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,9/9,45
3026331,GGTACGACTCCGTTC,2,3,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,16/18,45
3060961,GGTCTATCAAAGAGA,2,2,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,33/37,45
3154413,GTACCTCACTAAGGA,2,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,7/7,45
3370089,GTGGTTACCGTGTGA,2,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,13/16,45
3375411,GTGTACTGTCAGTCG,2,3,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,8/8,45
3403129,GTTAACTCGAACATG,2,6,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,27/28,45
3465479,GTTGTACTTGAGATG,4,9,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,8/8,45
3542978,TAAGTCGCCCATTCA,1,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,6/7,45
3611129,TACTAAGAGATTTGG,1,5,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,15/15,45
3623034,TACTTATGTGCATAA,5,6,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,29/30,45
3778477,TCAAACTTTCGTTGC,1,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,3/3,45
3789023,TCAATGAATGCGCAG,1,6,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,9/10,45
4049274,TGAATTAGTCGTGAA,2,3,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,13/13,45
4175924,TGCGTTGGTACCGAT,6,7,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,32/34,45
4339361,TGTCTAGAATGACGT,1,2,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,25/26,45

#### Investigate number of barcodes per replicate
- What is the average number of inserts? 
- add n_obs_bc 
- drop duplicates in name 
- histogram of n_obs_bc + mean and median of n_obs_bc

In [58]:
replicate_1_assignment['n_obs_bc'] = replicate_1_assignment.groupby('name')['barcode'].transform('count')
replicate_2_assignment['n_obs_bc'] = replicate_2_assignment.groupby('name')['barcode'].transform('count')
replicate_3_assignment['n_obs_bc'] = replicate_3_assignment.groupby('name')['barcode'].transform('count')

In [59]:

print('Replicate 1')
print(f"Number of oligos assigned: {replicate_1_assignment['name'].nunique()}") # 74782
print(f"Minimal number of n_obs_bc: {replicate_1_assignment['n_obs_bc'].min()}") # 1

print('Replicate 2')
print(f"Number of oligos assigned: {replicate_2_assignment['name'].nunique()}") # 74760
print(f"Minimal number of n_obs_bc: {replicate_2_assignment['n_obs_bc'].min()}") # 1

print('Replicate 3')
print(f"Number of oligos assigned: {replicate_3_assignment['name'].nunique()}") # 74781
print(f"Minimal number of n_obs_bc: {replicate_3_assignment['n_obs_bc'].min()}") # 1

Replicate 1
Number of oligos assigned: 74782
Minimal number of n_obs_bc: 1
Replicate 2
Number of oligos assigned: 74760
Minimal number of n_obs_bc: 1
Replicate 3
Number of oligos assigned: 74781
Minimal number of n_obs_bc: 1

#### Investigate the overlab and union without filtering: 
- How many sequences are in all replicates?
- Overlap of sequences between the replicates is `74597`
- All replicates together provide measurements for `74907` sequences
- 7% der oligos können wir nicht analysieren, weil wir sie nicht assignen können

In [60]:
rep1_oligos = set(replicate_1_assignment['name'].to_list())
rep2_oligos = set(replicate_2_assignment['name'].to_list())
rep3_oligos = set(replicate_3_assignment['name'].to_list())

#  Check the overlap between replicates
replicate_overlap = rep1_oligos.intersection(rep2_oligos).intersection(rep3_oligos)
print(f'Before filtering based on barcode count: {len(replicate_overlap)} oligos overlap') # 74597
#  Check the overlap between replicates
replicate_union = rep1_oligos.union(rep2_oligos).union(rep3_oligos)
print(f'Before filtering based on barcode count: {len(replicate_union)} oligos union') # 74907

# Check how many get lost through experiment and MPRAsnakeflow:
print(f'Intersection based number of oligos lost through experiment and MPRAsnakeflow: {_total_number_oligos - len(replicate_overlap)} ({round((_total_number_oligos - len(replicate_overlap))/_total_number_oligos*100, 3)}%)')
print(f'Union based number of oligos lost through experiment and MPRAsnakeflow: {_total_number_oligos - len(replicate_union)} ({round((_total_number_oligos - len(replicate_union))/_total_number_oligos*100, 3)}%)')

Before filtering based on barcode count: 74597 oligos overlap
Before filtering based on barcode count: 74907 oligos union
Intersection based number of oligos lost through experiment and MPRAsnakeflow: 5618 (7.004%)
Union based number of oligos lost through experiment and MPRAsnakeflow: 5308 (6.617%)

#### Filter replicates based on barcode count: 
- final resequencing with wrong UMI and not perfect alignment step: 
    - 5 barcodes per oligo per replicate
        - Rep1: 72057
        - Rep2: 72053
        - Rep3: 72043
        - 71627 oligos overlap (0.8929)
        - 72422 oligos in total (union) (0.9028)
    - 10 barcodes per oligo per replicate
        - Rep1: 68657
        - Rep2: 68677
        - Rep3: 68673
        - 67977 oligos overlap (0.8474)
        - 69297 oligos in total (union) (0.8639)
    - 20 barcodes per oligo per replicate
        - Rep1: 61292
        - Rep2: 61320
        - Rep3: 61351
        - 60271 oligos overlap (0.7514)
        - 62313 oligos in total (union) (0.7768)
    - 50 barcodes per oligo per replicate
        - Rep1: 39313
        - Rep2: 39355
        - Rep3: 39498
        - 37977 oligos overlap (0.4734)
        - 40803 oligos in total (union) (0.5087)

In [61]:
def filter_barcodes(df, print_text, threshold=5, barcode_column="n_obs_bc", verbose=True):
    """
    Filters the given df based on the barcode column, prints the number of unique names in df and returns the filtered df
    """
    df_filtered = df.loc[df[barcode_column] >= threshold]
    if verbose:
        print(f"{name}: {df_filtered['name'].nunique()}")
    return df_filtered

:

In [39]:
print("Start filtering the replicates based on the number of barcodes")

rep_df_dict = {
    'Rep1': replicate_1_assignment,
    'Rep2': replicate_2_assignment,
    'Rep3': replicate_3_assignment
}

for threshold in [5,10,20,50]:
    replicate_oligo_sets = []
    print(f"Minimum number of barcodes: {threshold}")
    for name, df in rep_df_dict.items():
        rep = filter_barcodes(df, print_text=name, threshold=threshold)
        # compute set of oligos per replicate
        replicate_oligo_sets.append(set(rep['name'].to_list()))
    # compute the overlap between replicates
    replicate_overlap = replicate_oligo_sets[0].intersection(replicate_oligo_sets[1]).intersection(replicate_oligo_sets[2])
    print(f'{len(replicate_overlap)} oligos overlap')
    # compute the proportion compared to the overall number of oligos (80215)
    print(f'{round(len(replicate_overlap) / _total_number_oligos, 4)} proportion of oligos overlap')
    # Compute the proportion compared to the maximal possible overlap (union of all replicates without filtering)
    print(f'{round(len(replicate_overlap) / len(replicate_union), 4)} proportion of oligos overlap in the union')
    # compute the union of oligos between replicates
    replicate_union = replicate_oligo_sets[0].union(replicate_oligo_sets[1]).union(replicate_oligo_sets[2])
    print(f'{len(replicate_union)} oligos in total')
    # compute the proportion compared to the overall number of oligos (80215)
    print(f'{round(len(replicate_union) / _total_number_oligos, 4)} proportion of oligos union')

Start filtering the replicates based on the number of barcodes
Minimum number of barcodes: 5
Rep1: 72057
Rep2: 72053
Rep3: 72043
71627 oligos overlap
0.8929 proportion of oligos overlap
72422 oligos in total
0.9028 proportion of oligos union
Minimum number of barcodes: 10
Rep1: 68657
Rep2: 68677
Rep3: 68673
67977 oligos overlap
0.8474 proportion of oligos overlap
69297 oligos in total
0.8639 proportion of oligos union
Minimum number of barcodes: 20
Rep1: 61292
Rep2: 61320
Rep3: 61351
60271 oligos overlap
0.7514 proportion of oligos overlap
62313 oligos in total
0.7768 proportion of oligos union
Minimum number of barcodes: 50
Rep1: 39313
Rep2: 39355
Rep3: 39498
37977 oligos overlap
0.4734 proportion of oligos overlap
40803 oligos in total
0.5087 proportion of oligos union

#### Merge replicates together
- merge all replicates with their barcodes together / looked into mprasnakeflow and Pias commit: (https://github.com/kircherlab/MPRAsnakeflow/commit/2e534d11b3b517cf4bcc6cca6f59dc2b04ca5b77) in `workflow/scripts/count/merge_replicates_barcode_counts.py` the barcode assigned files are combined and converted into bc mpralm readable format

In [36]:
replicate_1_assignment.head()

,barcode,rep1_dna_counts,rep1_rna_counts,name,assignment_number
0,AAAAAAAAAACAAGT,1,1,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,6/7
1,AAAAAAAAAAGCTGG,4,11,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,7/8
2,AAAAAAAAAATCCTA,2,6,cardiac_neuro_cava_random:ALT_ANK3|ENSG0000015...,15/16
3,AAAAAAAAAATCTAC,3,12,cardiac_neuro_cava_random:ALT_NBEA|ENSG0000017...,19/20
4,AAAAAAAAAATGTTT,4,4,cardiac_neuro_cava_random:ALT_CFAP91|ENSG00000...,8/10

In [12]:
replicate_1_assignment['name'].to_list()

['GC_Vista:eye;fb;hb;mb_hs1644_vistaElementControl|chr6:139888452-139888701',
 'cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000181722.18|EH38E2228539_rev_tile1-1_ZBTB20|ENSG00000181722.18|EH38E2228539|3-114510161-A-G',
 'cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000182185.19|EH38E3101266_fwd_tile1-1_RAD51B|ENSG00000182185.19|EH38E3101266|14-68243623-G-A',
 'cardiac_neuro_cava_random:ALT_ANK3|ENSG00000151150.22|EH38E1470921_rev_tile1-1_ANK3|ENSG00000151150.22|EH38E1470921|10-60424168-C-G',
 'cardiac_neuro_cava_random:ALT_NBEA|ENSG00000172915.20|EH38E1667609_fwd_tile1-1_NBEA|ENSG00000172915.20|EH38E1667609|13-35636102-G-A',
 'cardiac_neuro_cava_random:ALT_CFAP91|ENSG00000183833.16|EH38E3533715_fwd_tile1-1_CFAP91|ENSG00000183833.16|EH38E3533715|3-119665026-T-G',
 'cardiac_neuro_cava_random:ALT_TCF20|ENSG00000100207.21|EH38E3484401_rev_tile1-1_TCF20|ENSG00000100207.21|EH38E3484401|22-42381710-G-A',
 'cardiac_neuro_cava_random:ALT_SYNGAP1|ENSG00000197283.18|EH38E3702084_fwd_tile1-1_SYNGAP1|ENSG00000197283.18|EH38E3702084|6-33429911-T-C',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E2358394_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E2358394|5-14408083-G-T',
 'cardiac_neuro_cava_random:ALT_NRXN1|ENSG00000179915.25|EH38E3343414_rev_tile1-1_NRXN1|ENSG00000179915.25|EH38E3343414|2-49973655-T-A',
 'MK:tile_39693|chr7-42051777+42052046|scramble_negative',
 'cardiac_neuro_cava_random:REF_CIC|ENSG00000079432.9|EH38E3307682_fwd_tile1-1',
 'cardiac_neuro_cava_random:REF_NF2|ENSG00000186575.19|EH38E2157139_fwd_tile1-1',
 'cardiac_neuro_cava_random:REF_NRXN1|ENSG00000179915.25|EH38E3343411_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_DTNA|ENSG00000134769.23|EH38E1908880_fwd_tile1-1_DTNA|ENSG00000134769.23|EH38E1908880|18-34838045-T-C',
 'cardiac_neuro_cava_random:REF_MED13L|ENSG00000123066.9|EH38E1647374_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_GATA6|ENSG00000141448.11|EH38E1903163_fwd_tile1-1_GATA6|ENSG00000141448.11|EH38E1903163|18-22207106-C-G',
 'GC_Cort_Chengyu:da|chr3:72769931-72770200|2.02|IN_CGE~IN_MGE',
 'cardiac_neuro_cava_random:ALT_CNPY3|ENSG00000137161.18|EH38E3708663_fwd_tile1-1_CNPY3|ENSG00000137161.18|EH38E3708663|6-42919855-G-C',
 'cardiac_neuro_cava_random:ALT_MAX|ENSG00000125952.20|EH38E1721658_rev_tile1-1_MAX|ENSG00000125952.20|EH38E1721658|14-65070552-G-A',
 'GC_Mendelian_variants:REF_chr7:156791257G*A|SHH',
 'cardiac_neuro_cava_random:ALT_PACS1|ENSG00000175115.13|EH38E2965251_fwd_tile1-1_PACS1|ENSG00000175115.13|EH38E2965251|11-66113597-C-T',
 'cardiac_neuro_cava_random:ALT_MBD5|ENSG00000204406.14|EH38E3376770_fwd_tile1-1_MBD5|ENSG00000204406.14|EH38E3376770|2-148022156-C-G',
 'cardiac_neuro_cava_random:ALT_EIF3G|ENSG00000130811.12|EH38E3289107_rev_tile1-1_EIF3G|ENSG00000130811.12|EH38E3289107|19-10111640-C-G',
 'C_positive_heart_AB:NAA15-ENST00000700275.1:Oligo-Sub-Id:0.4:chr4:139299732-139300002:Length::270',
 'cardiac_neuro_cava_random:REF_NBEA|ENSG00000172915.20|EH38E1667597_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_IZUMO1|ENSG00000182264.9|EH38E1960278_rev_tile1-1_IZUMO1|ENSG00000182264.9|EH38E1960278|19-48769544-C-A',
 'GC_GABA_Chengyu:GABA|chr12:44688248-44688517|-|1.63',
 'cardiac_neuro_cava_random:REF_PPP3CA|ENSG00000138814.17|EH38E3597249_rev_tile1-1',
 'cardiac_neuro_cava_random:SYNGAP1|ENSG00000197283.18|EH38E3702048_fwd_tile1-1',
 'cardiac_neuro_cava_random:CHD7|ENSG00000171316.14|EH38E2634730_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_SIN3A|ENSG00000169375.17|EH38E3146822_rev_tile1-1_SIN3A|ENSG00000169375.17|EH38E3146822|15-75393964-C-T',
 'cardiac_neuro_cava_random:ALT_IRF4|ENSG00000137265.16|EH38E3684951_fwd_tile1-1_IRF4|ENSG00000137265.16|EH38E3684951|6-360858-G-A',
 'cardiac_neuro_cava_random:REF_VEZF1|ENSG00000136451.9|EH38E1873808_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_IGLV3-25|ENSG00000211659.2|EH38E3470175_fwd_tile1-1_IGLV3-25|ENSG00000211659.2|EH38E3470175|22-22639257-C-T',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3627221_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3627221|5-14497167-G-A',
 'cardiac_neuro_cava_random:FOXP1|ENSG00000114861.24|EH38E2213109_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_RBM20|ENSG00000203867.8|EH38E2924832_fwd_tile1-1_RBM20|ENSG00000203867.8|EH38E2924832|10-110865919-G-C',
 'cardiac_neuro_cava_random:ALT_CHD7|ENSG00000171316.14|EH38E2634600_fwd_tile1-1_CHD7|ENSG00000171316.14|EH38E2634600|8-60676395-C-T',
 'cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000182185.19|EH38E3101103_fwd_tile1-1_RAD51B|ENSG00000182185.19|EH38E3101103|14-67907665-G-C',
 'cardiac_neuro_cava_random:ALT_MAX|ENSG00000125952.20|EH38E1721690_rev_tile1-1_MAX|ENSG00000125952.20|EH38E1721690|14-65101136-C-T',
 'cardiac_neuro_cava_random:ALT_PPP3CA|ENSG00000138814.17|EH38E3597373_rev_tile1-1_PPP3CA|ENSG00000138814.17|EH38E3597373|4-101367865-G-T',
 'MK:tile_16997|chr16-86865331+86865600|scramble_negative',
 'cardiac_neuro_cava_random:ALT_ZMYND8|ENSG00000101040.20|EH38E2116922_rev_tile1-1_ZMYND8|ENSG00000101040.20|EH38E2116922|20-47355470-C-T',
 'cardiac_neuro_cava_random:ALT_NBEA|ENSG00000172915.20|EH38E3060591_fwd_tile1-1_NBEA|ENSG00000172915.20|EH38E3060591|13-35700109-T-C',
 'cardiac_neuro_cava_random:ALT_ATP6V0A1|ENSG00000033627.18|EH38E1863589_fwd_tile1-1_ATP6V0A1|ENSG00000033627.18|EH38E1863589|17-42484508-G-C',
 'cardiac_neuro_cava_random:REF_AUTS2|ENSG00000158321.19|EH38E3778114_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E2783803_rev_tile1-1_RERE|ENSG00000142599.20|EH38E2783803|1-8456178-G-A',
 'cardiac_neuro_cava_random:ALT_KMT2C|ENSG00000055609.21|EH38E3809506_rev_tile1-1_KMT2C|ENSG00000055609.21|EH38E3809506|7-152298311-C-A',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3626963_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_HADH|ENSG00000138796.18|EH38E2318673_fwd_tile1-1_HADH|ENSG00000138796.18|EH38E2318673|4-108053532-C-T',
 'cardiac_neuro_cava_random:ALT_CNN3|ENSG00000117519.16|EH38E2826039_rev_tile1-1_CNN3|ENSG00000117519.16|EH38E2826039|1-94942422-T-G',
 'cardiac_neuro_cava_random:ALT_ACVR1|ENSG00000115170.16|EH38E2043956_rev_tile1-1_ACVR1|ENSG00000115170.16|EH38E2043956|2-157899479-A-T',
 'cardiac_neuro_cava_random:ALT_NBN|ENSG00000104320.15|EH38E2646274_rev_tile1-1_NBN|ENSG00000104320.15|EH38E2646274|8-89961610-G-A',
 'cardiac_neuro_cava_random:ALT_SHANK2|ENSG00000162105.21|EH38E0225988_rev_tile1-1_SHANK2|ENSG00000162105.21|EH38E0225988|11-71102882-A-G',
 'cardiac_neuro_cava_random:REF_PRDM16|ENSG00000142611.17|EH38E2779932_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_MYT1L|ENSG00000186487.21|EH38E3320526_rev_tile1-1_MYT1L|ENSG00000186487.21|EH38E3320526|2-2109374-T-C',
 'cardiac_neuro_cava_random:REF_SOS1|ENSG00000115904.15|EH38E1989628_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_RBM20|ENSG00000203867.8|EH38E1499073_fwd_tile1-1_RBM20|ENSG00000203867.8|EH38E1499073|10-110637386-C-T',
 'cardiac_neuro_cava_random:ALT_BRCA2|ENSG00000139618.18|EH38E3059517_fwd_tile1-1_BRCA2|ENSG00000139618.18|EH38E3059517|13-32341061-G-A',
 'cardiac_neuro_cava_random:REF_NBEA|ENSG00000172915.20|EH38E1667379_fwd_tile1-1',
 'cardiac_neuro_cava_random:REF_RAF1|ENSG00000132155.14|EH38E3496217_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_TMEM43|ENSG00000170876.8|EH38E2180532_fwd_tile1-1_TMEM43|ENSG00000170876.8|EH38E2180532|3-14142076-G-C',
 'cardiac_neuro_cava_random:SRPRA|ENSG00000182934.12|EH38E1579732_rev_tile1-1',
 'cardiac_neuro_cava_random:DTNA|ENSG00000134769.23|EH38E1908713_fwd_tile1-1',
 'cardiac_neuro_cava_random:EBF3|ENSG00000108001.16|EH38E1511121_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_ACVR2B|ENSG00000114739.14|EH38E3506563_fwd_tile1-1_ACVR2B|ENSG00000114739.14|EH38E3506563|3-38443347-T-G',
 'cardiac_neuro_cava_random:ALT_NRXN1|ENSG00000179915.25|EH38E3343571_rev_tile1-1_NRXN1|ENSG00000179915.25|EH38E3343571|2-50661834-C-T',
 'cardiac_neuro_cava_random:ALT_CHD7|ENSG00000171316.14|EH38E2634711_fwd_tile1-1_CHD7|ENSG00000171316.14|EH38E2634711|8-60780985-A-G',
 'cardiac_neuro_cava_random:ALT_MAP2K1|ENSG00000169032.11|EH38E3140953_fwd_tile1-1_MAP2K1|ENSG00000169032.11|EH38E3140953|15-66454270-C-T',
 'cardiac_neuro_cava_random:ALT_PPP2R2A|ENSG00000221914.11|EH38E3824342_fwd_tile1-1_PPP2R2A|ENSG00000221914.11|EH38E3824342|8-26367571-G-A',
 'cardiac_neuro_cava_random:ALT_CTNNB1|ENSG00000168036.18|EH38E3507622_fwd_tile1-1_CTNNB1|ENSG00000168036.18|EH38E3507622|3-41159954-C-T',
 'cardiac_neuro_cava_random:CIC|ENSG00000079432.9|EH38E1955424_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_PPP1R9B|ENSG00000108819.11|EH38E3229730_rev_tile1-1_PPP1R9B|ENSG00000108819.11|EH38E3229730|17-50098209-C-A',
 'cardiac_neuro_cava_random:ALT_CDH1|ENSG00000039068.20|EH38E3187941_fwd_tile1-1_CDH1|ENSG00000039068.20|EH38E3187941|16-68782322-C-T',
 'cardiac_neuro_cava_random:ALT_KANSL1|ENSG00000120071.15|EH38E3227094_rev_tile1-1_KANSL1|ENSG00000120071.15|EH38E3227094|17-46138956-C-A',
 'cardiac_neuro_cava_random:ALT_SH3PXD2B|ENSG00000174705.13|EH38E3678555_rev_tile1-1_SH3PXD2B|ENSG00000174705.13|EH38E3678555|5-172314459-C-G',
 'cardiac_neuro_cava_random:ALT_CNN3|ENSG00000117519.16|EH38E2826003_rev_tile1-1_CNN3|ENSG00000117519.16|EH38E2826003|1-94887417-A-G',
 'cardiac_neuro_cava_random:ALT_PBX1|ENSG00000185630.20|EH38E1393295_fwd_tile1-1_PBX1|ENSG00000185630.20|EH38E1393295|1-164777796-G-A',
 'cardiac_neuro_cava_random:REF_EYA4|ENSG00000112319.21|EH38E3733485_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_VPS13B|ENSG00000132549.20|EH38E3847559_fwd_tile1-1_VPS13B|ENSG00000132549.20|EH38E3847559|8-99034862-T-C',
 'cardiac_neuro_cava_random:ALT_F9|ENSG00000101981.12|EH38E3946788_fwd_tile1-1_F9|ENSG00000101981.12|EH38E3946788|X-139590570-T-C',
 'cardiac_neuro_cava_random:ALT_HIVEP2|ENSG00000010818.11|EH38E2510425_rev_tile1-1_HIVEP2|ENSG00000010818.11|EH38E2510425|6-142829787-T-C',
 'cardiac_neuro_cava_random:ALT_FTO|ENSG00000140718.21|EH38E3181214_fwd_tile1-1_FTO|ENSG00000140718.21|EH38E3181214|16-53772247-A-G',
 'cardiac_neuro_cava_random:ALT_RFX3|ENSG00000080298.16|EH38E3872008_rev_tile1-1_RFX3|ENSG00000080298.16|EH38E3872008|9-3290888-G-A',
 'cardiac_neuro_cava_random:FOXP2|ENSG00000128573.28|EH38E3794725_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_CHAMP1|ENSG00000198824.8|EH38E3084976_fwd_tile1-1_CHAMP1|ENSG00000198824.8|EH38E3084976|13-114269130-G-A',
 'cardiac_neuro_cava_random:ALT_CUL3|ENSG00000036257.14|EH38E2079080_rev_tile1-1_CUL3|ENSG00000036257.14|EH38E2079080|2-224515653-T-C',
 'cardiac_neuro_cava_random:REF_WDFY3|ENSG00000163625.17|EH38E3592886_rev_tile1-1',
 'cardiac_neuro_cava_random:REF_ASH1L|ENSG00000116539.14|EH38E1387153_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_FANCM|ENSG00000187790.12|EH38E3092927_fwd_tile1-1_FANCM|ENSG00000187790.12|EH38E3092927|14-45136615-C-T',
 'cardiac_neuro_cava_random:REF_RAD51|ENSG00000051180.17|EH38E1756088_fwd_tile1-1',
 'cardiac_neuro_cava_random:REF_TMEM70|ENSG00000175606.11|EH38E3840334_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_CTCF|ENSG00000102974.16|EH38E3186944_fwd_tile1-1_CTCF|ENSG00000102974.16|EH38E3186944|16-67650517-C-T',
 'cardiac_neuro_cava_random:ALT_RALGAPB|ENSG00000170471.15|EH38E2111706_fwd_tile1-1_RALGAPB|ENSG00000170471.15|EH38E2111706|20-38560816-A-T',
 'cardiac_neuro_cava_random:REF_GATA4|ENSG00000136574.19|EH38E2611082_fwd_tile1-1',
 'cardiac_neuro_cava_random:REF_NEBL|ENSG00000078114.19|EH38E1453558_rev_tile1-1',
 'cardiac_neuro_cava_random:REF_PPP3CA|ENSG00000138814.17|EH38E3597256_rev_tile1-1',
 'cardiac_neuro_cava_random:SOX5|ENSG00000134532.20|EH38E1598797_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_HADH|ENSG00000138796.18|EH38E3599035_fwd_tile1-1_HADH|ENSG00000138796.18|EH38E3599035|4-108072367-T-C',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E1316480_rev_tile1-1_RERE|ENSG00000142599.20|EH38E1316480|1-8785140-C-A',
 'cardiac_neuro_cava_random:REF_SLC1A2|ENSG00000110436.13|EH38E1532729_rev_tile1-1',
 'MK:tile_44634|chr8-123231998+123232267|reference',
 'cardiac_neuro_cava_random:ALT_CITED2|ENSG00000164442.10|EH38E3736422_rev_tile1-1_CITED2|ENSG00000164442.10|EH38E3736422|6-139379044-T-A',
 'cardiac_neuro_cava_random:ALT_DTNA|ENSG00000134769.23|EH38E3263225_fwd_tile1-1_DTNA|ENSG00000134769.23|EH38E3263225|18-34750226-T-C',
 'cardiac_neuro_cava_random:ALT_SMC1A|ENSG00000072501.19|EH38E2755350_rev_tile1-1_SMC1A|ENSG00000072501.19|EH38E2755350|X-53456538-A-G',
 'cardiac_neuro_cava_random:REF_CHD7|ENSG00000171316.14|EH38E3836218_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_WWOX|ENSG00000186153.18|EH38E3192081_fwd_tile1-1_WWOX|ENSG00000186153.18|EH38E3192081|16-78129977-T-C',
 'cardiac_neuro_cava_random:ALT_TANC2|ENSG00000170921.16|EH38E1877142_fwd_tile1-1_TANC2|ENSG00000170921.16|EH38E1877142|17-63024956-C-G',
 'cardiac_neuro_cava_random:TNRC6B|ENSG00000100354.21|EH38E2165314_fwd_tile1-1',
 'C_positive_heart_AB:ZEB2-ENST00000444559.5:Oligo-Sub-Id:0.5:chr2:144523121-144523391:Length::270',
 'cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000182185.19|EH38E1723179_fwd_tile1-1_RAD51B|ENSG00000182185.19|EH38E1723179|14-68048140-A-G',
 'cardiac_neuro_cava_random:ALT_DTNA|ENSG00000134769.23|EH38E1908797_fwd_tile1-1_DTNA|ENSG00000134769.23|EH38E1908797|18-34709910-G-T',
 'cardiac_neuro_cava_random:ALT_ZEB1|ENSG00000148516.23|EH38E2894341_fwd_tile1-1_ZEB1|ENSG00000148516.23|EH38E2894341|10-31328914-A-G',
 'cardiac_neuro_cava_random:ALT_KCNQ3|ENSG00000184156.17|EH38E2669169_rev_tile1-1_KCNQ3|ENSG00000184156.17|EH38E2669169|8-132195378-C-T',
 'cardiac_neuro_cava_random:ALT_RELN|ENSG00000189056.15|EH38E3791051_rev_tile1-1_RELN|ENSG00000189056.15|EH38E3791051|7-103539148-A-G',
 'cardiac_neuro_cava_random:REF_ECE1|ENSG00000117298.16|EH38E1325895_rev_tile1-1',
 'cardiac_neuro_cava_random:FOXP1|ENSG00000114861.24|EH38E2213532_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_KIAA0232|ENSG00000170871.12|EH38E3570769_fwd_tile1-1_KIAA0232|ENSG00000170871.12|EH38E3570769|4-6766603-G-A',
 'cardiac_neuro_cava_random:REF_KCNT2|ENSG00000162687.19|EH38E2855766_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_LDB3|ENSG00000122367.21|EH38E2914219_fwd_tile1-1_LDB3|ENSG00000122367.21|EH38E2914219|10-86691512-G-C',
 'cardiac_neuro_cava_random:REF_ANK3|ENSG00000151150.22|EH38E2902484_rev_tile1-1',
 'cardiac_neuro_cava_random:REF_TRIO|ENSG00000038382.23|EH38E3626943_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_FGF12|ENSG00000114279.15|EH38E2269623_rev_tile1-1_FGF12|ENSG00000114279.15|EH38E2269623|3-192281652-T-C',
 'cardiac_neuro_cava_random:ALT_ATP1A2|ENSG00000018625.15|EH38E2842809_fwd_tile1-1_ATP1A2|ENSG00000018625.15|EH38E2842809|1-160149468-A-G',
 'cardiac_neuro_cava_random:ALT_LINC01583|ENSG00000259518.2|EH38E3150540_fwd_tile1-1_LINC01583|ENSG00000259518.2|EH38E3150540|15-82058177-C-T',
 'cardiac_neuro_cava_random:ALT_OXR1|ENSG00000164830.19|EH38E2655521_fwd_tile1-1_OXR1|ENSG00000164830.19|EH38E2655521|8-106287006-A-G',
 'cardiac_neuro_cava_random:REF_PRRX1|ENSG00000116132.12|EH38E1396722_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_ACTB|ENSG00000075624.17|EH38E3756181_rev_tile1-1_ACTB|ENSG00000075624.17|EH38E3756181|7-5582751-T-A',
 'cardiac_neuro_cava_random:ALT_MYOM1|ENSG00000101605.14|EH38E3254033_rev_tile1-1_MYOM1|ENSG00000101605.14|EH38E3254033|18-3218497-A-G',
 'cardiac_neuro_cava_random:MKX|ENSG00000150051.14|EH38E1457197_rev_tile1-1',
 'cardiac_neuro_cava_random:REF_SOX5|ENSG00000134532.20|EH38E1598812_rev_tile1-1',
 'cardiac_neuro_cava_random:REF_RAD51B|ENSG00000182185.19|EH38E3101210_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_TRAK1|ENSG00000182606.17|EH38E3508009_fwd_tile1-1_TRAK1|ENSG00000182606.17|EH38E3508009|3-42177703-A-G',
 'cardiac_neuro_cava_random:ALT_MYPN|ENSG00000138347.17|EH38E2905019_fwd_tile1-1_MYPN|ENSG00000138347.17|EH38E2905019|10-68173317-G-A',
 'cardiac_neuro_cava_random:REF_DHCR7|ENSG00000172893.18|EH38E1550142_rev_tile1-1',
 'cardiac_neuro_cava_random:REF_CITED2|ENSG00000164442.10|EH38E3736422_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_FOXP1|ENSG00000114861.24|EH38E3522303_rev_tile1-1_FOXP1|ENSG00000114861.24|EH38E3522303|3-71240259-G-A',
 'cardiac_neuro_cava_random:ALT_UGDH|ENSG00000109814.12|EH38E3581096_rev_tile1-1_UGDH|ENSG00000109814.12|EH38E3581096|4-39481542-G-A',
 'cardiac_neuro_cava_random:EHMT1|ENSG00000181090.21|EH38E3921738_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_GNAO1|ENSG00000087258.16|EH38E3182118_fwd_tile1-1_GNAO1|ENSG00000087258.16|EH38E3182118|16-56174688-G-A',
 'cardiac_neuro_cava_random:REF_KMT2C|ENSG00000055609.21|EH38E3809515_rev_tile1-1',
 'cardiac_neuro_cava_random:REF_NF1|ENSG00000196712.20|EH38E3217379_fwd_tile1-1',
 'cardiac_neuro_cava_random:REF_RERE|ENSG00000142599.20|EH38E2783765_rev_tile1-1',
 'MK:newcore_304083|chr5-61408443+61408712|A-T-261',
 'cardiac_neuro_cava_random:REF_WDFY3|ENSG00000163625.17|EH38E2309122_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_TRIO|ENSG00000038382.23|EH38E3626897_fwd_tile1-1_TRIO|ENSG00000038382.23|EH38E3626897|5-14098208-T-C',
 'cardiac_neuro_cava_random:REF_MTHFR|ENSG00000177000.13|EH38E1319107_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_SFPQ|ENSG00000116560.12|EH38E2802405_rev_tile1-1_SFPQ|ENSG00000116560.12|EH38E2802405|1-35193971-G-A',
 'cardiac_neuro_cava_random:STAMBP|ENSG00000124356.17|EH38E2009968_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_LDB1|ENSG00000198728.11|EH38E1494802_rev_tile1-1_LDB1|ENSG00000198728.11|EH38E1494802|10-102153213-C-A',
 'cardiac_neuro_cava_random:ALT_MSL3|ENSG00000005302.19|EH38E3925285_fwd_tile1-1_MSL3|ENSG00000005302.19|EH38E3925285|X-11750268-A-G',
 'cardiac_neuro_cava_random:ALT_TMEM43|ENSG00000170876.8|EH38E3497565_fwd_tile1-1_TMEM43|ENSG00000170876.8|EH38E3497565|3-14137773-A-G',
 'cardiac_neuro_cava_random:ALT_CACNA1C|ENSG00000151067.23|EH38E1586832_fwd_tile1-1_CACNA1C|ENSG00000151067.23|EH38E1586832|12-2172759-A-C',
 'cardiac_neuro_cava_random:CACNA2D3|ENSG00000157445.15|EH38E3516022_fwd_tile1-1',
 'cardiac_neuro_cava_random:ALT_CRELD1|ENSG00000163703.20|EH38E3494678_fwd_tile1-1_CRELD1|ENSG00000163703.20|EH38E3494677|3-9979052-G-A',
 'cardiac_neuro_cava_random:ALT_ANK2|ENSG00000145362.21|EH38E2321052_fwd_tile1-1_ANK2|ENSG00000145362.21|EH38E2321052|4-113074213-C-T',
 'cardiac_neuro_cava_random:ALT_MYOZ2|ENSG00000172399.6|EH38E2323078_fwd_tile1-1_MYOZ2|ENSG00000172399.6|EH38E2323078|4-119136400-G-A',
 'cardiac_neuro_cava_random:REF_KDM5B|ENSG00000117139.18|EH38E2858911_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_MORF4L1|ENSG00000185787.15|EH38E1780847_fwd_tile1-1_MORF4L1|ENSG00000185787.15|EH38E1780847|15-78878582-A-C',
 'cardiac_neuro_cava_random:ALT_MORF4L1|ENSG00000185787.15|EH38E3149007_fwd_tile1-1_MORF4L1|ENSG00000185787.15|EH38E3149007|15-78913280-G-T',
 'cardiac_neuro_cava_random:REF_LRRC4C|ENSG00000148948.8|EH38E2954589_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_CASQ2|ENSG00000118729.12|EH38E1379000_rev_tile1-1_CASQ2|ENSG00000118729.12|EH38E1379000|1-115745484-C-T',
 'cardiac_neuro_cava_random:ALT_SOX5|ENSG00000134532.20|EH38E3007324_rev_tile1-1_SOX5|ENSG00000134532.20|EH38E3007324|12-23731687-C-T',
 'cardiac_neuro_cava_random:ALT_CDH1|ENSG00000039068.20|EH38E3187941_fwd_tile1-1_CDH1|ENSG00000039068.20|EH38E3187941|16-68782481-C-A',
 'cardiac_neuro_cava_random:ALT_HIVEP2|ENSG00000010818.11|EH38E3737511_rev_tile1-1_HIVEP2|ENSG00000010818.11|EH38E3737511|6-142882391-A-G',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E2844123_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E2844123|1-162071024-A-T',
 'cardiac_neuro_cava_random:ALT_SMARCA4|ENSG00000127616.21|EH38E3290105_fwd_tile1-1_SMARCA4|ENSG00000127616.21|EH38E3290105|19-11022361-G-A',
 'cardiac_neuro_cava_random:ALT_HADH|ENSG00000138796.18|EH38E3598982_fwd_tile1-1_HADH|ENSG00000138796.18|EH38E3598982|4-107976713-G-A',
 'cardiac_neuro_cava_random:NRXN1|ENSG00000179915.25|EH38E1997463_rev_tile1-1',
 'cardiac_neuro_cava_random:REF_ECE1|ENSG00000117298.16|EH38E1326025_rev_tile1-1',
 'cardiac_neuro_cava_random:ALT_BRCA2|ENSG00000139618.18|EH38E3059551_fwd_tile1-1_BRCA2|ENSG00000139618.18|EH38E3059551|13-32446408-T-C',
 'MK:tile_47753|chr5-88484310+88484580|reference',

In [34]:
# sort df by name
replicate_1_assignment.sort_values(by='name')

,barcode,rep1_dna_counts,rep1_rna_counts,name,assignment_number
1764659,CTCGTGATGAAGCGG,3,7,C_SLEA:SLEA_hg18:chr2:210861483-210861650|103:...,16/16
1672917,CGTTCTACCCGTTTA,10,10,C_SLEA:SLEA_hg18:chr2:210861483-210861650|103:...,23/26
2521186,GGACAATGACCGCCG,3,15,C_SLEA:SLEA_hg18:chr2:210861483-210861650|103:...,12/12
516158,AGACTGAACGCTAGG,8,14,C_SLEA:SLEA_hg18:chr2:210861483-210861650|103:...,24/24
3575377,TCGAAGGACGGGGGC,2,1,C_SLEA:SLEA_hg18:chr2:210861483-210861650|103:...,5/6
...,...,...,...,...,...
1916051,GAAAGTAGCCTCCTT,3,6,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,12/14
1739567,CTCAGGTTACCAAGT,4,5,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,7/7
4260902,TTTCGACCGGATGCG,3,8,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,9/9
611673,AGCTGAGGTGCGCAA,1,1,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,8/8
872023,ATCCTTTGTCTCTTG,4,3,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,7/9

In [2]:
# merged data from MPRAsnakeflow
mpra_results_minThreshold = pd.read_csv(config['files']['final_design']['merged_mprasnakeflow_final_resequencing'], sep='\t')
mpra_results_minThreshold

,condition,replicate,name,dna_counts,rna_counts,dna_normalized,rna_normalized,ratio,log2,n_obs_bc
0,NGN2,1,C_SLEA:SLEA_hg18:chr2:210861483-210861650|103:...,455,1333,0.117015,0.113946,1.003588,0.005167,112
1,NGN2,1,C_SLEA:SLEA_hg18:chr2:210861483-210861650|103:...,428,2869,0.122060,0.271955,2.296273,1.199294,101
2,NGN2,1,C_SLEA:SLEA_hg18:chr2:210861483-210861650|10:V...,286,874,0.117684,0.119537,1.046844,0.066047,70
3,NGN2,1,C_SLEA:SLEA_hg18:chr2:210861483-210861650|10:V...,359,1189,0.108848,0.119825,1.134551,0.182122,95
4,NGN2,1,C_SLEA:SLEA_hg18:chr2:210861483-210861650|10:V...,235,736,0.123071,0.128116,1.072869,0.101474,55
...,...,...,...,...,...,...,...,...,...,...
206005,NGN2,3,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,280,1571,0.092946,0.188011,2.106237,1.074668,83
206006,NGN2,3,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,102,357,0.100368,0.126647,1.313885,0.393838,28
206007,NGN2,3,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,96,172,0.073472,0.047458,0.672584,-0.572214,36
206008,NGN2,3,cardiac_neuro_cava_random:ZNF462|ENSG000001481...,449,1048,0.105733,0.088974,0.876202,-0.190665,117
206009,NGN2,3,no_BC,18184104,49644897,0.086600,0.085238,1.024877,0.035451,5785309

,0,1,2,3
0,AAAAAAAAAAACGTC,GC_Vista:eye;fb;hb;mb_hs1644_vistaElementContr...,15;270M;NM:i:0;MD:Z:270;60,5/5
1,AAAAAAAAAACAAGT,cardiac_neuro_cava_random:ALT_ZBTB20|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,6/7
2,AAAAAAAAAACACCA,cardiac_neuro_cava_random:ALT_FTO|ENSG00000140...,15;270M;NM:i:0;MD:Z:270;6,9/10
3,AAAAAAAAAACCTCG,cardiac_neuro_cava_random:REF_FKRP|ENSG0000018...,15;270M;NM:i:0;MD:Z:270;6,7/7
4,AAAAAAAAAAGCTGG,cardiac_neuro_cava_random:ALT_RAD51B|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,7/8
...,...,...,...,...
6305461,TTTTTTTTTTGACCG,cardiac_neuro_cava_random:ALT_CPS1|ENSG0000002...,15;270M;NM:i:0;MD:Z:270;6,32/33
6305462,TTTTTTTTTTGACGA,cardiac_neuro_cava_random:ALT_ACTN2|ENSG000000...,15;270M;NM:i:0;MD:Z:270;6,11/11
6305463,TTTTTTTTTTGCACA,cardiac_neuro_cava_random:ALT_CARD11|ENSG00000...,15;270M;NM:i:0;MD:Z:270;6,22/26
6305464,TTTTTTTTTTGCTAA,cardiac_neuro_cava_random:REF_NR4A2|ENSG000001...,15;270M;NM:i:0;MD:Z:270;6,6/6
6305465,TTTTTTTTTTGTCCC,cardiac_neuro_cava_random:ALT_NBN|ENSG00000104...,15;270M;NM:i:0;MD:Z:270;6,3/3