### Investigate the hypothesis that the variants with higher effect sizes are enriched for gwas hits

### Process:
1. read in the metadata file which was used to generate the data for the langenberg group
2. identify which variants are matchable (SPDIs)
- Do we have matching problems still?
3. Get the ALT ids which are associated with a GWAS hit
- Add the has_GWAS_hit column to the variant data
4. Add the is significant column
5. Add the has_high_effect column
6. Find out how to compare the proportion of varaints with GWAS hits in the significant variants vs the non-significant variants
7. Plot the results

In [41]:
import pandas as pd
import yaml


# load helpful functions
import sys
sys.path.append('../../00_helpful_functions')
import helpful_functions as hf

# config
config_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/global80K_config.yaml"
with open(config_path) as conf:
    config = yaml.load(conf, Loader=yaml.FullLoader)
    conf.close()

In [42]:
col_name = 'name'
col_sequence = 'sequence'
col_category = 'category'
col_class = 'class'
col_source = 'source'
col_ref = 'ref'
col_chr = 'chr'
col_start = 'start'
col_end = 'end'
col_strand = 'strand'
col_variant_class = 'variant_class' # SNV
col_variant_pos = 'variant_pos'
col_SPDI = 'SPDI'
col_allele = 'allele'
col_info = 'info'


import ast

# Function to safely evaluate string representations of lists
def safe_eval(x):
    if pd.isna(x):
        return None
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return x

sig_level = 0.1

In [43]:
#first version
summary_table = "/home/kisa/coding/80K_MPRA/collaborations/langenberg/sig_variants_80k_MPRA_unique_kircher.gwas_summary.tsv"
overlap_table = "/home/kisa/coding/80K_MPRA/collaborations/langenberg/sig_variants_80k_MPRA_unique_kircher.gwas_overlap.tsv"

# all variants
summary_table = "/home/kisa/coding/80K_MPRA/collaborations/langenberg/all_variants_80k_MPRA_unique_kircher.gwas_summary.tsv.gz"
overlap_table = "/home/kisa/coding/80K_MPRA/collaborations/langenberg/all_variants_80k_MPRA_unique_kircher.gwas_overlap.tsv.gz"

summary_df = pd.read_csv(summary_table, sep="\t", low_memory=False)
overlap_df = pd.read_csv(overlap_table, sep="\t", low_memory=False)

In [44]:
summary_df["has_gwas_annotation"] = summary_df["mapped_trait_efo"].notna()
gwas_annotation_spdis = summary_df.loc[summary_df['has_gwas_annotation']]['spdi'].to_list()

In [45]:
metadata_file_path ="/home/kisa/coding/80K_MPRA/element_analysis_output/202502_element_analysis/element_metadata_with_bcalm_2025_02_bbmap_vs_scrambled.tsv.gz"
metadata_file_path ="/home/kisa/coding/80K_MPRA/element_analysis_output/202502_element_analysis/NGN2_element_metadata_with_bcalm_2025_04_normalized_counts_bbmap_vs_scrambled.tsv.gz"
metadata_file = pd.read_csv(metadata_file_path, sep="\t", low_memory=False)

# list columns col_variant_class, col_variant_pos, col_SPDI, col_allele
list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]

# Apply the safe_eval function to the specified columns
for col in list_columns:
    metadata_file[col] = metadata_file[col].apply(safe_eval)

In [46]:
variant_metadata_path ="/home/kisa/coding/80K_MPRA/element_variant_analysis_output/NGN2_variants_metadata_with_bcalm_2025_02_bbmap_scrambled.tsv.gz"
variant_bcalm_df = pd.read_csv(variant_metadata_path, sep="\t", low_memory=False)

# # list columns col_variant_class, col_variant_pos, col_SPDI, col_allele
list_columns = [col_variant_pos]

# Apply the safe_eval function to the specified columns
for col in list_columns:
    variant_bcalm_df[col] = variant_bcalm_df[col].apply(safe_eval)

variant_bcalm_df = variant_bcalm_df.loc[variant_bcalm_df['bcalm_variant_effect_data_exists']].copy()

In [47]:
variant_bcalm_df

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity,label
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,[116],True,0.979716,0.032099,1.000000,-0.664178,1.000000e+00,-0.675062,cardiac_neuro_cava_random
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,[205],True,0.929889,-0.053121,1.000000,-0.011245,1.000000e+00,-0.028705,cardiac_neuro_cava_random
6,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[71],True,0.775543,-0.212077,1.000000,-0.530696,1.000000e+00,-0.725193,cardiac_neuro_cava_random
7,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[144],True,0.999288,0.001458,1.000000,-0.530696,1.000000e+00,-0.612857,cardiac_neuro_cava_random
8,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[183],True,0.729637,-0.211652,1.000000,-0.530696,8.129874e-01,-0.774325,cardiac_neuro_cava_random
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47039,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,[136],True,0.101141,0.229206,1.000000,-0.322271,1.000000e+00,-0.106460,C_positive_heart_CAD
47040,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,[136],True,0.222166,-0.468693,0.000576,-1.130559,1.863777e-11,-1.557981,C_positive_heart_CAD
47041,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,[136],True,0.518546,0.246189,1.000000,-0.240604,1.000000e+00,0.009369,C_positive_heart_CAD
47042,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,[136],True,0.812184,0.128220,0.576842,-0.758037,1.000000e+00,-0.630269,C_positive_heart_CAD
47043,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,[136],True,0.781808,-0.176904,1.000000,0.221772,1.000000e+00,0.066261,C_positive_heart_CAD

In [48]:
# read variant table and add the spdi column there as well
metadata_file_tested_alt = metadata_file.loc[metadata_file["name"].str.startswith("cardiac_neuro_cava_random:ALT_") & (metadata_file[col_SPDI].notna())].copy()

In [49]:
metadata_file_tested_alt # 46,374

,name,sequence,category,class,source,ref,chr,start,end,strand,...,SPDI,allele,info,bcalm_element_adjusted_p_value,bcalm_element_log_ratio_activity,bcalm_data_exists,label,not_shifted_bcalm_element_log_ratio_activity,bcalm_element_log_ratio_activity_z_score_neg_ctrl,bcalm_element_log_ratio_activity_z_score_scrambled_ctrl
29853,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GTCCCAGCTCCCCACTGATGTGAAAGGTGGTGGTGAGTTAACAGCT...,variant,test,NaN,GRCh38,chr1,2179507.0,2179777.0,+,...,[NC_000001.11:2179590:T:C],[alt],NaN,5.965362e-07,0.190591,True,cardiac_neuro_cava_random,0.190591,7.760601,5.320544
29854,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTGATCTGCCCTGTCCGTGACGCTTCTGCTCAGTAGCTGAGCACG...,variant,test,NaN,GRCh38,chr1,2191262.0,2191532.0,+,...,[NC_000001.11:2191443:G:A],[alt],NaN,NaN,NaN,False,cardiac_neuro_cava_random,NaN,NaN,NaN
29855,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCTGGGTGACCCGGAGAACACCAAGGCTGTGAGAAATGGGATGC...,variant,test,NaN,GRCh38,chr1,2191971.0,2192241.0,+,...,[NC_000001.11:2192014:G:T],[alt],NaN,NaN,NaN,False,cardiac_neuro_cava_random,NaN,NaN,NaN
29856,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,variant,test,NaN,GRCh38,chr1,2192249.0,2192519.0,+,...,[NC_000001.11:2192365:T:G],[alt],NaN,1.000000e+00,-0.072051,True,cardiac_neuro_cava_random,-0.072051,0.324578,-1.471449
29857,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,variant,test,NaN,GRCh38,chr1,2192936.0,2193206.0,+,...,[NC_000001.11:2193141:G:A],[alt],NaN,1.000000e+00,-0.005889,True,cardiac_neuro_cava_random,-0.005889,2.197787,0.239523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76222,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,GGAGCTCTGCCTCACCCCACCTGGCCCCAATTGTCCAGCTTGTAGA...,variant,test,NaN,GRCh38,chrX,154545000.0,154545270.0,-,...,[NC_000023.11:154545205:A:G],[alt],NaN,4.511542e-01,0.065547,True,cardiac_neuro_cava_random,0.065547,4.220287,2.086855
76223,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,ATGTCTGAATTCACCTCCAAATAATGGGAAAACTCCTAGGTATATA...,variant,test,NaN,GRCh38,chrX,154549802.0,154550072.0,-,...,[NC_000023.11:154549922:T:G],[alt],NaN,9.174673e-02,-0.090558,True,cardiac_neuro_cava_random,-0.090558,-0.199415,-1.950059
76224,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTTCCC...,variant,test,NaN,GRCh38,chrX,154552145.0,154552415.0,-,...,[NC_000023.11:154552288:C:T],[alt],NaN,4.362900e-01,0.052674,True,cardiac_neuro_cava_random,0.052674,3.855845,1.753977
76225,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTTCTC...,variant,test,NaN,GRCh38,chrX,154552145.0,154552415.0,-,...,[NC_000023.11:154552370:G:A],[alt],NaN,1.000000e+00,0.016824,True,cardiac_neuro_cava_random,0.016824,2.840822,0.826865
76226,cardiac_neuro_cava_random:ALT_G6PD|ENSG0000016...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTCCCC...,variant,test,NaN,GRCh38,chrX,154552145.0,154552415.0,-,...,[NC_000023.11:154552372:A:G],[alt],NaN,9.968914e-02,0.071148,True,cardiac_neuro_cava_random,0.071148,4.378877,2.231710

In [50]:
metadata_file_tested_alt["SPDI"] = metadata_file_tested_alt[col_SPDI].apply(lambda spdi_list: spdi_list[0] if isinstance(spdi_list, list) and len(spdi_list) > 0 else None)

In [51]:
metadata_file_tested_alt['has_gwas_annotation'] = metadata_file_tested_alt["SPDI"].isin(gwas_annotation_spdis)

In [52]:
metadata_file_tested_alt['has_gwas_annotation'].sum()

808

In [54]:
alternative_name_has_gwas_annotation = metadata_file_tested_alt.loc[metadata_file_tested_alt['has_gwas_annotation'], 'name'].to_list()
alternative_name_has_gwas_annotation

['cardiac_neuro_cava_random:ALT_SKI|ENSG00000157933.11|EH38E2778534_fwd_tile1-1_SKI|ENSG00000157933.11|EH38E2778534|1-2210427-C-T',
 'cardiac_neuro_cava_random:ALT_SKI|ENSG00000157933.11|EH38E2778534_fwd_tile1-1_SKI|ENSG00000157933.11|EH38E2778534|1-2210546-C-A',
 'cardiac_neuro_cava_random:ALT_SKI|ENSG00000157933.11|EH38E2778579_fwd_tile1-1_SKI|ENSG00000157933.11|EH38E2778579|1-2233496-G-T',
 'cardiac_neuro_cava_random:ALT_SKI|ENSG00000157933.11|EH38E2778605_fwd_tile1-1_SKI|ENSG00000157933.11|EH38E2778605|1-2249085-G-A',
 'cardiac_neuro_cava_random:ALT_SKI|ENSG00000157933.11|EH38E2778610_fwd_tile1-1_SKI|ENSG00000157933.11|EH38E2778610|1-2250903-T-C',
 'cardiac_neuro_cava_random:ALT_SKI|ENSG00000157933.11|EH38E1311725_fwd_tile1-1_SKI|ENSG00000157933.11|EH38E1311725|1-2271528-T-C',
 'cardiac_neuro_cava_random:ALT_PRDM16|ENSG00000142611.17|EH38E2779527_fwd_tile1-1_PRDM16|ENSG00000142611.17|EH38E2779527|1-3033770-G-A',
 'cardiac_neuro_cava_random:ALT_PRDM16|ENSG00000142611.17|EH38E2779663_fwd_tile1-1_PRDM16|ENSG00000142611.17|EH38E2779663|1-3133291-C-T',
 'cardiac_neuro_cava_random:ALT_PRDM16|ENSG00000142611.17|EH38E2779707_fwd_tile1-1_PRDM16|ENSG00000142611.17|EH38E2779707|1-3164745-T-C',
 'cardiac_neuro_cava_random:ALT_PRDM16|ENSG00000142611.17|EH38E2779716_fwd_tile1-1_PRDM16|ENSG00000142611.17|EH38E2779716|1-3169737-C-A',
 'cardiac_neuro_cava_random:ALT_PRDM16|ENSG00000142611.17|EH38E2779716_fwd_tile1-1_PRDM16|ENSG00000142611.17|EH38E2779716|1-3169900-G-A',
 'cardiac_neuro_cava_random:ALT_PRDM16|ENSG00000142611.17|EH38E2779725_fwd_tile1-1_PRDM16|ENSG00000142611.17|EH38E2779725|1-3174204-A-G',
 'cardiac_neuro_cava_random:ALT_PRDM16|ENSG00000142611.17|EH38E2779730_fwd_tile1-1_PRDM16|ENSG00000142611.17|EH38E2779730|1-3178392-G-A',
 'cardiac_neuro_cava_random:ALT_PRDM16|ENSG00000142611.17|EH38E2779780_fwd_tile1-1_PRDM16|ENSG00000142611.17|EH38E2779780|1-3211832-C-T',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E2783657_rev_tile1-1_RERE|ENSG00000142599.20|EH38E2783657|1-8329094-G-A',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E2783712_rev_tile1-1_RERE|ENSG00000142599.20|EH38E2783712|1-8366176-G-A',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E2783774_rev_tile1-1_RERE|ENSG00000142599.20|EH38E2783774|1-8420956-T-G',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E2783807_rev_tile1-1_RERE|ENSG00000142599.20|EH38E2783807|1-8462493-C-A',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E1316161_rev_tile1-1_RERE|ENSG00000142599.20|EH38E1316161|1-8478242-G-C',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E1316480_rev_tile1-1_RERE|ENSG00000142599.20|EH38E1316480|1-8785140-C-A',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E2784071_rev_tile1-1_RERE|ENSG00000142599.20|EH38E2784071|1-8870326-G-A',
 'cardiac_neuro_cava_random:ALT_RERE|ENSG00000142599.20|EH38E2784108_rev_tile1-1_RERE|ENSG00000142599.20|EH38E2784108|1-8896887-T-C',
 'cardiac_neuro_cava_random:ALT_CASZ1|ENSG00000130940.15|EH38E2785651_rev_tile1-1_CASZ1|ENSG00000130940.15|EH38E2785651|1-10667560-G-A',
 'cardiac_neuro_cava_random:ALT_CASZ1|ENSG00000130940.15|EH38E2785674_rev_tile1-1_CASZ1|ENSG00000130940.15|EH38E2785674|1-10677616-C-T',
 'cardiac_neuro_cava_random:ALT_CASZ1|ENSG00000130940.15|EH38E2785691_rev_tile1-1_CASZ1|ENSG00000130940.15|EH38E2785691|1-10686398-G-C',
 'cardiac_neuro_cava_random:ALT_CASZ1|ENSG00000130940.15|EH38E2785699_rev_tile1-1_CASZ1|ENSG00000130940.15|EH38E2785699|1-10690138-G-A',
 'cardiac_neuro_cava_random:ALT_CASZ1|ENSG00000130940.15|EH38E2785820_rev_tile1-1_CASZ1|ENSG00000130940.15|EH38E2785820|1-10763729-T-A',
 'cardiac_neuro_cava_random:ALT_MTOR|ENSG00000198793.14|EH38E2786093_rev_tile1-1_MTOR|ENSG00000198793.14|EH38E2786093|1-11072160-G-A',
 'cardiac_neuro_cava_random:ALT_MTOR|ENSG00000198793.14|EH38E2786115_rev_tile1-1_MTOR|ENSG00000198793.14|EH38E2786115|1-11134534-G-A',
 'cardiac_neuro_cava_random:ALT_MTOR|ENSG00000198793.14|EH38E2786160_rev_tile1-1_MTOR|ENSG00000198793.14|EH38E2786160|1-11215019-C-T',
 'cardiac_neuro_cava_random:ALT_MTHFR|ENSG00000177000.13|EH38E2786584_rev_tile1-1_MTHFR|ENSG00000177000.13|EH38E2786584|1-11797869-G-A',
 'cardiac_neuro_cava_random:ALT_MTHFR|ENSG00000177000.13|EH38E2786585_rev_tile1-1_MTHFR|ENSG00000177000.13|EH38E2786585|1-11798527-T-C',
 'cardiac_neuro_cava_random:ALT_MTHFR|ENSG00000177000.13|EH38E1319127_rev_tile1-1_MTHFR|ENSG00000177000.13|EH38E1319127|1-11812927-A-G',
 'cardiac_neuro_cava_random:ALT_MTHFR|ENSG00000177000.13|EH38E2786615_rev_tile1-1_MTHFR|ENSG00000177000.13|EH38E2786615|1-11832558-G-C',
 'cardiac_neuro_cava_random:ALT_SDHB|ENSG00000117118.10|EH38E2789917_rev_tile1-1_SDHB|ENSG00000117118.10|EH38E2789917|1-16977297-C-T',
 'cardiac_neuro_cava_random:ALT_SDHB|ENSG00000117118.10|EH38E2789953_rev_tile1-1_SDHB|ENSG00000117118.10|EH38E2789953|1-17009758-C-T',
 'cardiac_neuro_cava_random:ALT_SDHB|ENSG00000117118.10|EH38E1322809_rev_tile1-1_SDHB|ENSG00000117118.10|EH38E1322809|1-17016429-G-A',
 'cardiac_neuro_cava_random:ALT_ECE1|ENSG00000117298.16|EH38E1326022_rev_tile1-1_ECE1|ENSG00000117298.16|EH38E1326022|1-21308923-C-T',
 'cardiac_neuro_cava_random:ALT_ECE1|ENSG00000117298.16|EH38E2792783_rev_tile1-1_ECE1|ENSG00000117298.16|EH38E2792783|1-21317252-T-C',
 'cardiac_neuro_cava_random:ALT_ECE1|ENSG00000117298.16|EH38E2792810_rev_tile1-1_ECE1|ENSG00000117298.16|EH38E2792810|1-21330909-C-T',
 'cardiac_neuro_cava_random:ALT_ECE1|ENSG00000117298.16|EH38E2792810_rev_tile1-1_ECE1|ENSG00000117298.16|EH38E2792810|1-21331014-C-T',
 'cardiac_neuro_cava_random:ALT_ECE1|ENSG00000117298.16|EH38E2792869_rev_tile1-1_ECE1|ENSG00000117298.16|EH38E2792869|1-21392772-C-G',
 'cardiac_neuro_cava_random:ALT_AHDC1|ENSG00000126705.15|EH38E2797807_rev_tile1-1_AHDC1|ENSG00000126705.15|EH38E2797807|1-27505637-A-G',
 'cardiac_neuro_cava_random:ALT_FHL3|ENSG00000183386.10|EH38E2803959_rev_tile1-1_FHL3|ENSG00000183386.10|EH38E2803959|1-37987358-C-T',
 'cardiac_neuro_cava_random:ALT_FHL3|ENSG00000183386.10|EH38E2804038_rev_tile1-1_FHL3|ENSG00000183386.10|EH38E2804038|1-38041651-G-A',
 'cardiac_neuro_cava_random:ALT_SZT2|ENSG00000198198.17|EH38E2807349_fwd_tile1-1_SZT2|ENSG00000198198.17|EH38E2807349|1-43392966-A-G',
 'cardiac_neuro_cava_random:ALT_ST3GAL3|ENSG00000126091.21|EH38E1342696_fwd_tile1-1_ST3GAL3|ENSG00000126091.21|EH38E1342696|1-43688808-G-C',
 'cardiac_neuro_cava_random:ALT_ST3GAL3|ENSG00000126091.21|EH38E1342773_fwd_tile1-1_ST3GAL3|ENSG00000126091.21|EH38E1342773|1-43787237-C-T',
 'cardiac_neuro_cava_random:ALT_ST3GAL3|ENSG00000126091.21|EH38E1342785_fwd_tile1-1_ST3GAL3|ENSG00000126091.21|EH38E1342785|1-43800524-G-A',
 'cardiac_neuro_cava_random:ALT_ST3GAL3|ENSG00000126091.21|EH38E2807677_fwd_tile1-1_ST3GAL3|ENSG00000126091.21|EH38E2807677|1-43866412-G-A',
 'cardiac_neuro_cava_random:ALT_ST3GAL3|ENSG00000126091.21|EH38E1342909_fwd_tile1-1_ST3GAL3|ENSG00000126091.21|EH38E1342909|1-43924720-C-T',
 'cardiac_neuro_cava_random:ALT_POMGNT1|ENSG00000085998.15|EH38E2809115_rev_tile1-1_POMGNT1|ENSG00000085998.15|EH38E2809115|1-46191548-C-T',
 'cardiac_neuro_cava_random:ALT_PLPP3|ENSG00000162407.9|EH38E2813768_rev_tile1-1_PLPP3|ENSG00000162407.9|EH38E2813768|1-56520434-T-C',
 'cardiac_neuro_cava_random:ALT_PLPP3|ENSG00000162407.9|EH38E1350506_rev_tile1-1_PLPP3|ENSG00000162407.9|EH38E1350506|1-56522879-A-C',
 'cardiac_neuro_cava_random:ALT_PLPP3|ENSG00000162407.9|EH38E1350523_rev_tile1-1_PLPP3|ENSG00000162407.9|EH38E1350523|1-56538745-A-G',
 'cardiac_neuro_cava_random:ALT_DOCK7|ENSG00000116641.18|EH38E1353993_rev_tile1-1_DOCK7|ENSG00000116641.18|EH38E1353993|1-62426778-C-T',
 'cardiac_neuro_cava_random:ALT_NEXN|ENSG00000162614.19|EH38E2820352_fwd_tile1-1_NEXN|ENSG00000162614.19|EH38E2820352|1-77926761-G-A',
 'cardiac_neuro_cava_random:ALT_NEXN|ENSG00000162614.19|EH38E2820381_fwd_tile1-1_NEXN|ENSG00000162614.19|EH38E2820381|1-77984833-C-A',
 'cardiac_neuro_cava_random:ALT_CNN3|ENSG00000117519.16|EH38E2826036_rev_tile1-1_CNN3|ENSG00000117519.16|EH38E2826036|1-94936057-A-G',
 'cardiac_neuro_cava_random:ALT_CSDE1|ENSG00000009307.17|EH38E2832540,NRAS|ENSG00000213281.5|EH38E2832540_rev_tile1-1_CSDE1|ENSG00000009307.17|EH38E2832540|1-114753903-A-G,NRAS|ENSG00000213281.5|EH38E2832540|1-114753903-A-G',
 'cardiac_neuro_cava_random:ALT_NOTCH2|ENSG00000134250.21|EH38E2834931_rev_tile1-1_NOTCH2|ENSG00000134250.21|EH38E2834931|1-119929884-C-A',
 'cardiac_neuro_cava_random:ALT_GJA5|ENSG00000265107.3|EH38E2836115_rev_tile1-1_GJA5|ENSG00000265107.3|EH38E2836115|1-147757554-G-A',
 'cardiac_neuro_cava_random:ALT_GJA5|ENSG00000265107.3|EH38E1382862_rev_tile1-1_GJA5|ENSG00000265107.3|EH38E1382862|1-147792138-T-C',
 'cardiac_neuro_cava_random:ALT_RIT1|ENSG00000143622.12|EH38E2840274_rev_tile1-1_RIT1|ENSG00000143622.12|EH38E2840274|1-155939119-T-C',
 'cardiac_neuro_cava_random:ALT_LMNA|ENSG00000160789.24|EH38E1387638_fwd_tile1-1_LMNA|ENSG00000160789.24|EH38E1387638|1-156113705-T-C',
 'cardiac_neuro_cava_random:ALT_LMNA|ENSG00000160789.24|EH38E2840477_fwd_tile1-1_LMNA|ENSG00000160789.24|EH38E2840477|1-156117415-A-G',
 'cardiac_neuro_cava_random:ALT_LMNA|ENSG00000160789.24|EH38E2840499_fwd_tile1-1_LMNA|ENSG00000160789.24|EH38E2840499|1-156127844-G-C',
 'cardiac_neuro_cava_random:ALT_LMNA|ENSG00000160789.24|EH38E1387748_fwd_tile1-1_LMNA|ENSG00000160789.24|EH38E1387748|1-156178374-T-C',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E2844143_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E2844143|1-162114868-T-C',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E2844157_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E2844157|1-162142292-T-C',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E1391853_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E1391853|1-162184119-C-T',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E1391864_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E1391864|1-162192957-G-T',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E2844200_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E2844200|1-162198364-G-A',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E2844208_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E2844208|1-162212768-C-G',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E1391894_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E1391894|1-162215756-G-T',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E1391945_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E1391945|1-162272247-A-T',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E1391968_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E1391968|1-162293480-G-A',
 'cardiac_neuro_cava_random:ALT_NOS1AP|ENSG00000198929.13|EH38E1392070_fwd_tile1-1_NOS1AP|ENSG00000198929.13|EH38E1392070|1-162407781-T-C',
 'cardiac_neuro_cava_random:ALT_PRRX1|ENSG00000116132.12|EH38E2847495_fwd_tile1-1_PRRX1|ENSG00000116132.12|EH38E2847495|1-170619453-T-C',
 'cardiac_neuro_cava_random:ALT_PRRX1|ENSG00000116132.12|EH38E1396651_fwd_tile1-1_PRRX1|ENSG00000116132.12|EH38E1396651|1-170620296-G-A',
 'cardiac_neuro_cava_random:ALT_PRRX1|ENSG00000116132.12|EH38E2847511_fwd_tile1-1_PRRX1|ENSG00000116132.12|EH38E2847511|1-170665943-T-C',
 'cardiac_neuro_cava_random:ALT_PRRX1|ENSG00000116132.12|EH38E2847512_fwd_tile1-1_PRRX1|ENSG00000116132.12|EH38E2847512|1-170666228-A-G',
 'cardiac_neuro_cava_random:ALT_PRRX1|ENSG00000116132.12|EH38E1396723_fwd_tile1-1_PRRX1|ENSG00000116132.12|EH38E1396723|1-170694334-A-G',
 'cardiac_neuro_cava_random:ALT_PRRX1|ENSG00000116132.12|EH38E2847534_fwd_tile1-1_PRRX1|ENSG00000116132.12|EH38E2847534|1-170695096-G-A',
 'cardiac_neuro_cava_random:ALT_PRRX1|ENSG00000116132.12|EH38E2847553_fwd_tile1-1_PRRX1|ENSG00000116132.12|EH38E2847553|1-170732291-C-T',
 'cardiac_neuro_cava_random:ALT_KCNT2|ENSG00000162687.19|EH38E1408810_rev_tile1-1_KCNT2|ENSG00000162687.19|EH38E1408810|1-196394414-G-A',
 'cardiac_neuro_cava_random:ALT_CHI3L1|ENSG00000133048.13|EH38E2859143_rev_tile1-1_CHI3L1|ENSG00000133048.13|EH38E2859143|1-203134258-G-A',
 'cardiac_neuro_cava_random:ALT_CHI3L1|ENSG00000133048.13|EH38E1413248_rev_tile1-1_CHI3L1|ENSG00000133048.13|EH38E1413248|1-203149276-C-G',
 'cardiac_neuro_cava_random:ALT_FBXO28|ENSG00000143756.12|EH38E2868766_fwd_tile1-1_FBXO28|ENSG00000143756.12|EH38E2868766|1-224067816-C-A',
 'cardiac_neuro_cava_random:ALT_FBXO28|ENSG00000143756.12|EH38E1426256_fwd_tile1-1_FBXO28|ENSG00000143756.12|EH38E1426256|1-224074447-G-A',
 'cardiac_neuro_cava_random:ALT_FBXO28|ENSG00000143756.12|EH38E1426258_fwd_tile1-1_FBXO28|ENSG00000143756.12|EH38E1426258|1-224080297-T-C',
 'cardiac_neuro_cava_random:ALT_FBXO28|ENSG00000143756.12|EH38E2868777_fwd_tile1-1_FBXO28|ENSG00000143756.12|EH38E2868777|1-224113408-T-C',
 'cardiac_neuro_cava_random:ALT_ARV1|ENSG00000173409.14|EH38E1431116_fwd_tile1-1_ARV1|ENSG00000173409.14|EH38E1431116|1-230950625-C-T',
 'cardiac_neuro_cava_random:ALT_DISC1|ENSG00000162946.23|EH38E1431486_fwd_tile1-1_DISC1|ENSG00000162946.23|EH38E1431486|1-231577297-C-T',
 'cardiac_neuro_cava_random:ALT_RYR2|ENSG00000198626.18|EH38E2876461_fwd_tile1-1_RYR2|ENSG00000198626.18|EH38E2876461|1-237779580-G-C',
 'cardiac_neuro_cava_random:ALT_CELF2|ENSG00000048740.19|EH38E1447700_fwd_tile1-1_CELF2|ENSG00000048740.19|EH38E1447700|10-11081734-T-C',
 'cardiac_neuro_cava_random:ALT_NEBL|ENSG00000078114.19|EH38E2889823_rev_tile1-1_NEBL|ENSG00000078114.19|EH38E2889823|10-20891107-T-A',
 'cardiac_neuro_cava_random:ALT_NEBL|ENSG00000078114.19|EH38E1453547_rev_tile1-1_NEBL|ENSG00000078114.19|EH38E1453547|10-21054484-G-A',
 'cardiac_neuro_cava_random:ALT_MKX|ENSG00000150051.14|EH38E1457194_rev_tile1-1_MKX|ENSG00000150051.14|EH38E1457194|10-27714630-C-T',
 'cardiac_neuro_cava_random:ALT_WAC|ENSG00000095787.25|EH38E2892812_fwd_tile1-1_WAC|ENSG00000095787.25|EH38E2892812|10-28530477-G-A',
 'cardiac_neuro_cava_random:ALT_WAC|ENSG00000095787.25|EH38E2892832_fwd_tile1-1_WAC|ENSG00000095787.25|EH38E2892832|10-28559399-T-A',
 'cardiac_neuro_cava_random:ALT_ZEB1|ENSG00000148516.23|EH38E2894346_fwd_tile1-1_ZEB1|ENSG00000148516.23|EH38E2894346|10-31343717-A-G',
 'cardiac_neuro_cava_random:ALT_ZEB1|ENSG00000148516.23|EH38E2894352_fwd_tile1-1_ZEB1|ENSG00000148516.23|EH38E2894352|10-31360190-A-C',
 'cardiac_neuro_cava_random:ALT_ANK3|ENSG00000151150.22|EH38E1470637_rev_tile1-1_ANK3|ENSG00000151150.22|EH38E1470637|10-60080409-C-T',
 'cardiac_neuro_cava_random:ALT_ANK3|ENSG00000151150.22|EH38E2902588_rev_tile1-1_ANK3|ENSG00000151150.22|EH38E2902588|10-60312978-T-C',
 'cardiac_neuro_cava_random:ALT_ANK3|ENSG00000151150.22|EH38E1470846_rev_tile1-1_ANK3|ENSG00000151150.22|EH38E1470846|10-60353928-C-T',
 'cardiac_neuro_cava_random:ALT_ANK3|ENSG00000151150.22|EH38E2902624_rev_tile1-1_ANK3|ENSG00000151150.22|EH38E2902624|10-60375499-G-A',
 'cardiac_neuro_cava_random:ALT_ANK3|ENSG00000151150.22|EH38E2902627_rev_tile1-1_ANK3|ENSG00000151150.22|EH38E2902627|10-60377176-A-T',
 'cardiac_neuro_cava_random:ALT_ANK3|ENSG00000151150.22|EH38E2902643_rev_tile1-1_ANK3|ENSG00000151150.22|EH38E2902643|10-60399593-T-G',
 'cardiac_neuro_cava_random:ALT_CTNNA3|ENSG00000183230.18|EH38E2904749_rev_tile1-1_CTNNA3|ENSG00000183230.18|EH38E2904749|10-67089463-G-A',
 'cardiac_neuro_cava_random:ALT_MYPN|ENSG00000138347.17|EH38E1474289_fwd_tile1-1_MYPN|ENSG00000138347.17|EH38E1474289|10-68066486-A-G',
 'cardiac_neuro_cava_random:ALT_MYPN|ENSG00000138347.17|EH38E1474324_fwd_tile1-1_MYPN|ENSG00000138347.17|EH38E1474324|10-68097349-T-C',
 'cardiac_neuro_cava_random:ALT_MYPN|ENSG00000138347.17|EH38E2905019_fwd_tile1-1_MYPN|ENSG00000138347.17|EH38E2905019|10-68173481-C-A',
 'cardiac_neuro_cava_random:ALT_MYPN|ENSG00000138347.17|EH38E2905024_fwd_tile1-1_MYPN|ENSG00000138347.17|EH38E2905024|10-68180481-C-T',
 'cardiac_neuro_cava_random:ALT_MYPN|ENSG00000138347.17|EH38E2905035_fwd_tile1-1_MYPN|ENSG00000138347.17|EH38E2905035|10-68203093-G-A',
 'cardiac_neuro_cava_random:ALT_VCL|ENSG00000035403.18|EH38E2908818_fwd_tile1-1_VCL|ENSG00000035403.18|EH38E2908818|10-74023077-A-G',
 'cardiac_neuro_cava_random:ALT_VCL|ENSG00000035403.18|EH38E2908854_fwd_tile1-1_VCL|ENSG00000035403.18|EH38E2908854|10-74079696-A-G',
 'cardiac_neuro_cava_random:ALT_LDB3|ENSG00000122367.21|EH38E2914290_fwd_tile1-1_LDB3|ENSG00000122367.21|EH38E2914290|10-86759199-G-A',
 'cardiac_neuro_cava_random:ALT_PTEN|ENSG00000171862.13|EH38E2914731_fwd_tile1-1_PTEN|ENSG00000171862.13|EH38E2914731|10-87857400-A-G',
 'cardiac_neuro_cava_random:ALT_PTEN|ENSG00000171862.13|EH38E1486069_fwd_tile1-1_PTEN|ENSG00000171862.13|EH38E1486069|10-87916275-G-A',
 'cardiac_neuro_cava_random:ALT_PTEN|ENSG00000171862.13|EH38E2914793_fwd_tile1-1_PTEN|ENSG00000171862.13|EH38E2914793|10-88004733-T-G',
 'cardiac_neuro_cava_random:ALT_ANKRD1|ENSG00000148677.7|EH38E1487913_rev_tile1-1_ANKRD1|ENSG00000148677.7|EH38E1487913|10-90954883-T-C',
 'cardiac_neuro_cava_random:ALT_CYP2C19|ENSG00000165841.11|EH38E2917481_fwd_tile1-1_CYP2C19|ENSG00000165841.11|EH38E2917481|10-94800730-T-C',
 'cardiac_neuro_cava_random:ALT_LDB1|ENSG00000198728.11|EH38E1494802_rev_tile1-1_LDB1|ENSG00000198728.11|EH38E1494802|10-102153213-C-A',
 'cardiac_neuro_cava_random:ALT_RBM20|ENSG00000203867.8|EH38E2924645_fwd_tile1-1_RBM20|ENSG00000203867.8|EH38E2924645|10-110650540-T-A',
 'cardiac_neuro_cava_random:ALT_TCF7L2|ENSG00000148737.18|EH38E1500378_fwd_tile1-1_TCF7L2|ENSG00000148737.18|EH38E1500378|10-112916421-A-G',
 'cardiac_neuro_cava_random:ALT_TCF7L2|ENSG00000148737.18|EH38E1500484_fwd_tile1-1_TCF7L2|ENSG00000148737.18|EH38E1500484|10-113025665-G-A',
 'cardiac_neuro_cava_random:ALT_TCF7L2|ENSG00000148737.18|EH38E2925667_fwd_tile1-1_TCF7L2|ENSG00000148737.18|EH38E2925667|10-113060432-T-C',
 'cardiac_neuro_cava_random:ALT_TCF7L2|ENSG00000148737.18|EH38E1500620_fwd_tile1-1_TCF7L2|ENSG00000148737.18|EH38E1500620|10-113128058-A-G',
 'cardiac_neuro_cava_random:ALT_TCF7L2|ENSG00000148737.18|EH38E1500643_fwd_tile1-1_TCF7L2|ENSG00000148737.18|EH38E1500643|10-113140748-G-T',
 'cardiac_neuro_cava_random:ALT_BAG3|ENSG00000151929.10|EH38E2928860_fwd_tile1-1_BAG3|ENSG00000151929.10|EH38E2928860|10-119673412-C-T',
 'cardiac_neuro_cava_random:ALT_HRAS|ENSG00000174775.18|EH38E1513706_rev_tile1-1_HRAS|ENSG00000174775.18|EH38E1513706|11-579354-C-T',
 'cardiac_neuro_cava_random:ALT_DRD4|ENSG00000069696.7|EH38E2937836_fwd_tile1-1_DEAF1|ENSG00000177030.19|EH38E2937836|11-641548-C-T,DRD4|ENSG00000069696.7|EH38E2937836|11-641548-C-T',
 'cardiac_neuro_cava_random:ALT_DEAF1|ENSG00000177030.19|EH38E2937836_rev_tile1-1_DEAF1|ENSG00000177030.19|EH38E2937836|11-641548-C-T,DRD4|ENSG00000069696.7|EH38E2937836|11-641548-C-T',
 'cardiac_neuro_cava_random:ALT_SLC25A22|ENSG00000177542.11|EH38E1513947_rev_tile1-1_SLC25A22|ENSG00000177542.11|EH38E1513947|11-786953-C-G',
 'cardiac_neuro_cava_random:ALT_SLC25A22|ENSG00000177542.11|EH38E2938146_rev_tile1-1_SLC25A22|ENSG00000177542.11|EH38E2938146|11-836008-T-C',
 'cardiac_neuro_cava_random:ALT_BRSK2|ENSG00000174672.16|EH38E2939131_fwd_tile1-1_BRSK2|ENSG00000174672.16|EH38E2939131|11-1483785-C-T',
 'cardiac_neuro_cava_random:ALT_DENND5A|ENSG00000184014.9|EH38E2943582_rev_tile1-1_DENND5A|ENSG00000184014.9|EH38E2943582|11-9230573-G-A',
 'cardiac_neuro_cava_random:ALT_CSRP3|ENSG00000129170.10|EH38E2948272_rev_tile1-1_CSRP3|ENSG00000129170.10|EH38E2948272|11-19199971-G-A',
 'cardiac_neuro_cava_random:ALT_CSRP3|ENSG00000129170.10|EH38E2948285_rev_tile1-1_CSRP3|ENSG00000129170.10|EH38E2948285|11-19225882-A-G',
 'cardiac_neuro_cava_random:ALT_CSRP3|ENSG00000129170.10|EH38E2948294_rev_tile1-1_CSRP3|ENSG00000129170.10|EH38E2948294|11-19242659-T-C',
 'cardiac_neuro_cava_random:ALT_SLC1A2|ENSG00000110436.13|EH38E1532674_rev_tile1-1_SLC1A2|ENSG00000110436.13|EH38E1532674|11-35289966-C-T',
 'cardiac_neuro_cava_random:ALT_SLC1A2|ENSG00000110436.13|EH38E2953246_rev_tile1-1_SLC1A2|ENSG00000110436.13|EH38E2953246|11-35302696-A-G',
 'cardiac_neuro_cava_random:ALT_LRRC4C|ENSG00000148948.8|EH38E2954542_rev_tile1-1_LRRC4C|ENSG00000148948.8|EH38E2954542|11-41052052-C-T',

In [55]:
# add the gwas information to the variant table
variant_bcalm_df['has_gwas_annotation'] = variant_bcalm_df["ALT"].isin(alternative_name_has_gwas_annotation)

In [56]:
variant_bcalm_df['has_gwas_annotation'].sum() # 774

663

In [64]:
variant_bcalm_df['high_variant_effect'] = variant_bcalm_df['bcalm_variant_effect_log_ratio_activity'] > 1

In [57]:
variant_bcalm_df['is_significant'] = variant_bcalm_df['bcalm_variant_effect_adjusted_p_value'] < sig_level

In [58]:
variant_bcalm_df

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_data_exists,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity,label,has_gwas_annotation,is_significant
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,[116],True,0.979716,0.032099,1.000000,-0.664178,1.000000e+00,-0.675062,cardiac_neuro_cava_random,False,False
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,[205],True,0.929889,-0.053121,1.000000,-0.011245,1.000000e+00,-0.028705,cardiac_neuro_cava_random,False,False
6,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[71],True,0.775543,-0.212077,1.000000,-0.530696,1.000000e+00,-0.725193,cardiac_neuro_cava_random,False,False
7,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[144],True,0.999288,0.001458,1.000000,-0.530696,1.000000e+00,-0.612857,cardiac_neuro_cava_random,False,False
8,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,CCTCCACTTGTCAGGAAGCCTGACCCCCAATCCCCTCCCGCCTGAC...,[183],True,0.729637,-0.211652,1.000000,-0.530696,8.129874e-01,-0.774325,cardiac_neuro_cava_random,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47039,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,[136],True,0.101141,0.229206,1.000000,-0.322271,1.000000e+00,-0.106460,C_positive_heart_CAD,False,False
47040,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,[136],True,0.222166,-0.468693,0.000576,-1.130559,1.863777e-11,-1.557981,C_positive_heart_CAD,False,False
47041,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,[136],True,0.518546,0.246189,1.000000,-0.240604,1.000000e+00,0.009369,C_positive_heart_CAD,False,False
47042,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,[136],True,0.812184,0.128220,0.576842,-0.758037,1.000000e+00,-0.630269,C_positive_heart_CAD,False,False
47043,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,[136],True,0.781808,-0.176904,1.000000,0.221772,1.000000e+00,0.066261,C_positive_heart_CAD,False,False

7. How to compare the proportion of variants with GWAS hits in the significant variants vs the non-significant variants
- Use a chi-squared test to compare the proportions of variants with GWAS hits in the significant and non-significant variants

In [61]:
# test for significant difference in the number of variants with gwas annotation

# Create a contingency table
contingency_table = pd.crosstab(variant_bcalm_df['has_gwas_annotation'], variant_bcalm_df['is_significant'])
contingency_table
# # Perform the Chi-squared test
# from scipy.stats import chi2_contingency

# chi2, p_value, _, _ = chi2_contingency(contingency_table)
# print(f"Chi-squared test statistic: {chi2}")
# print(f"P-value: {p_value}")
# # Interpret the result
# if p_value < 0.05:
#     print("There is a significant association between the two categorical variables.")

is_significant       False  True
has_gwas_annotation
False                36731    892
True                   651     12

In [ ]:
# compute the proportions:
contingency_table_proportions = contingency_table.div(contingency_table.sum(axis=1), axis=0)
contingency_table_proportions # => no enrichment based on significance

is_significant          False     True
has_gwas_annotation
False                0.976291  0.023709
True                 0.981900  0.018100

Using high effect not only significants

In [66]:
variant_bcalm_df['high_variant_effect'].sum()

31

In [ ]:

contingency_table = pd.crosstab(variant_bcalm_df['has_gwas_annotation'], variant_bcalm_df['high_variant_effect'])
contingency_table
# no enrichment for high variant effects at all

high_variant_effect  False  True
has_gwas_annotation
False                37592     31
True                   663      0

### Use only common variants