### Musti would like to test element and variant analysis steps:
- Data processing: give him sequences with bcalm results and variant position

In [1]:
import ast
import pandas as pd
import os
import yaml

# load helpful functions
import sys
sys.path.append('../../00_helpful_functions')
import helpful_functions as hf

# config
config_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/global80K_config.yaml"
with open(config_path) as conf:
    config = yaml.load(conf, Loader=yaml.FullLoader)
    conf.close()

In [2]:
# column names
col_name = 'name'
col_header = 'name'
col_sequence = 'sequence'
col_category = 'category'
col_class = 'class'
col_source = 'source'
col_ref = 'ref'
col_chr = 'chr'
col_start = 'start'
col_end = 'end'
col_strand = 'strand'
col_variant_class = 'variant_class'
col_variant_pos = 'variant_pos'
col_SPDI = 'SPDI'
col_allele = 'allele'
col_info = 'info'


list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]

# Function to safely evaluate string representations of lists
def safe_eval(x):
    if pd.isna(x):
        return None
    try:
        return ast.literal_eval(x)
    except (ValueError, SyntaxError):
        return x

write_output = True

In [29]:
# bcalm elements compared against negative controls
bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/202501_bwa_finest_80k_element_toptreat_results.tsv"
bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/202501_80k_element_bbmap_outlier_removed_toptreat_results.tsv"
bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/undiffWTC11_202505_80k_element_bbmap_no_outlier_removal_bc10_toptreat_results_negative_ctrl_result_095_both_sied.tsv"
bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/NGN2_202504_80k_element_bbmap_no_outlier_removal_bc10_toptreat_results_negative_ctrl_result_095.tsv"

# # bcalm elements compared against scrambled controls
# bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/202501_80k_element_bbmap_outlier_removed_toptreat_results_scrambled_NP_MK_result_095.tsv"
# bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/WTC11_202503_80k_element_bbmap_outlier_removed_toptreat_results_scrambled_NP_MK_result_095.tsv"
# bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/undiffWTC11_202505_80k_element_bbmap_no_outlier_removal_bc10_toptreat_results_scrambled_NP_MK_result_095_both_sided.tsv"
bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/undiffWTC11_202505_80k_element_bbmap_no_outlier_removal_bc10_toptreat_results_scrambled_NP_MK_result_095_both_sided.tsv"
bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/NGN2_202504_80k_element_bbmap_no_outlier_removal_bc10_toptreat_results_scrambled_NP_MK_result_095.tsv"
bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/undiffWTC11_202505_80k_element_bbmap_no_outlier_removal_bc10_toptreat_results_scrambled_NP_MK_result_095_both_sided.tsv"
bcalm_element_results="/home/kisa/coding/80K_MPRA/element_analysis_output/undiffWTC11_202505_80k_element_bbmap_no_outlier_removal_bc10_toptreat_results_scrambled_NP_MK_result_075_both_sided.tsv"


# # bcalm variants bwa finest and bbmap
# bcalm_variant_results="/home/kisa/coding/80K_MPRA/bc_MPRAlm_results/results/variant_bcalm_80k_bwa_finest_outlier_removal_no_hashtag_exists_variant_map_unique_id.tsv"
# bcalm_variant_results="/home/kisa/coding/80K_MPRA/bc_MPRAlm_results/results/variant_bcalm_80K_bbmap_std_mapq30_no_hashtag_variant_map_unique_variant_id.tsv"
# bcalm_variant_results="/home/kisa/coding/80K_MPRA/bc_MPRAlm_results/results/WTC11_variant_bcalm_80k_bbmap_outlier_removal_default_design_variant_map_unique_id.tsv"
# bcalm_variant_results="/home/kisa/coding/80K_MPRA/bc_MPRAlm_results/results/NGN2_variant_bcalm_80k_bbmap_no_outlier_removal_normalized_counts_mpralib_design_variant_map_unique_id_all_rep_DNA_RNA.tsv"


# general info
# variant_map = "/home/kisa/coding/80K_MPRA/server_results/80k_counts_after_metadatafile/unique_id_renamed_variant_region_map_mprasnakeflow_input.tsv.gz"
mpra_80k_metadata = "/data/cephfs-2/unmirrored/groups/kircher/MPRA/IGVF_Y1_design/design/mpra_metadata_format/MPRA_80215.metadata.tsv.gz"
mpra_80k_metadata = "/home/kisa/coding/80K_MPRA/80K-Analysis/07_quality_control/notebooks/control_metadata/MPRA_80215.metadata.tsv.gz"
mpra_80k_metadata = "/data/cephfs-2/unmirrored/groups/kircher/MPRA/IGVF_Y1_design/design/mpra_metadata_format/MPRA_80215.metadata.tsv.gz"

output_elements = "element_metadata_with_bcalm_2025_02"
output_elements = "element_metadata_with_bcalm_2025_02_bbmap"
output_elements = "element_metadata_with_bcalm_2025_02_bbmap_scrambled"
output_elements = "NGN2_element_metadata_with_bcalm_2025_02_bbmap_scrambled"
output_elements = "WTC11_element_metadata_with_bcalm_2025_02_bbmap_scrambled"
output_elements = "undiffWTC11_element_metadata_with_bcalm_2025_05_bbmap_normalized_counts_scrambled"
output_elements = "undiffWTC11_element_metadata_with_bcalm_2025_05_bbmap_normalized_counts_neuro_ctrls"
output_elements = "NGN2_element_metadata_with_bcalm_2025_04_bbmap_normalized_counts_neuro_ctrl"
output_elements = "NGN2_element_metadata_with_bcalm_2025_04_bbmap_normalized_counts_scrambled"
output_elements = "undiffWTC11_element_metadata_with_bcalm_2025_05_bbmap_normalized_counts_scrambled"
output_elements = "undiffWTC11_element_metadata_with_bcalm_2025_05_bbmap_normalized_counts_scrambled_075"
# output_variants = "variants_metadata_bcalm_2025"
# output_variants = "variants_metadata_bcalm_2025_bbmap"
# output_variants = "variants_metadata_bcalm_2025_bbmap_scrambled"
# output_variants = "NGN2_variants_metadata_bcalm_2025_bbmap_scrambled"
# output_variants = "WTC11_variants_metadata_bcalm_2025_bbmap_scrambled"
# output_variants = "NGN2_variants_metadata_bcalm_2025_bbmap_normalized_counts"

In [30]:
mpra_80k_metadata_df = pd.read_csv(mpra_80k_metadata, sep='\t', compression='gzip', low_memory=False)

# use safe eval on list
# Apply the safe_eval function to the specified columns
for col in list_columns:
    mpra_80k_metadata_df[col] = mpra_80k_metadata_df[col].apply(safe_eval)

In [5]:
# not needed for the wtc11 results
# mpra_80k_metadata_df[col_name] = mpra_80k_metadata_df[col_name].apply(lambda name: name.replace(",", "~") if "cardiac_neuro_cava_random" in name else name)

### Metadata + bcalm element information  (+ bcalm_data_exists column)

In [31]:
bcalm_element_df = pd.read_csv(bcalm_element_results, sep="\t")
# TODO: add the element bcalm information

mpra_80k_metadata_df_bcalm =  mpra_80k_metadata_df.merge(bcalm_element_df[[col_name, 'adj.P.Val', 'logFC']], on=col_name, how='left')
mpra_80k_metadata_df_bcalm.rename(columns={'adj.P.Val': 'bcalm_element_adjusted_p_value', 'logFC': 'bcalm_element_log_ratio_activity'}, inplace=True)

In [32]:
mpra_80k_metadata_df_bcalm['bcalm_element_adjusted_p_value'].notna().sum() # 68669 # 69945 # bbmap: 69093 # 72271 # wtc11: 41333 # NGN2 negative control: 73687 # wtc11 resequencing: 72897

72897

In [33]:
mpra_80k_metadata_df_bcalm["bcalm_data_exists"] = mpra_80k_metadata_df_bcalm['bcalm_element_adjusted_p_value'].notna()
mpra_80k_metadata_df_bcalm["bcalm_data_exists"].value_counts()

# bbmap:
# bcalm_data_exists
# True     69093
# False    11122

# wtc11 strand sensitive bbmap
# bcalm_data_exists
# True     41333
# False    38882

# no outlier removal
# bcalm_data_exists
# True     72271
# False     7944

# wtc11 resequencing no outlier removal
# bcalm_data_exists
# True     72897
# False     7318

bcalm_data_exists
True     72897
False     7318
Name: count, dtype: int64

In [34]:
mpra_80k_metadata_df_bcalm["label"] = mpra_80k_metadata_df_bcalm[col_name].apply(hf.get_label)
mpra_80k_metadata_df_bcalm["bcalm_data_exists"].value_counts(normalize=True)

# wtc11
# bcalm_data_exists
# True     0.515278
# False    0.484722

# ngn2 no outlier removal:
# bcalm_data_exists
# True     0.900966
# False    0.099034

# wtc11 no outlier removal
# bcalm_data_exists
# True     0.90877
# False    0.09123

bcalm_data_exists
True     0.90877
False    0.09123
Name: proportion, dtype: float64

In [35]:
normalized_counts = (
    mpra_80k_metadata_df_bcalm
    .groupby("label")["bcalm_data_exists"]
    .value_counts(normalize=True)
)

print(normalized_counts)

label                              bcalm_data_exists
C_SLEA                             True                 0.865000
                                   False                0.135000
C_negative_heart_MK                True                 0.880658
                                   False                0.119342
C_negative_neuron_MK               True                 0.846847
                                   False                0.153153
C_negative_neuron_NP               True                 0.622120
                                   False                0.377880
C_positive_heart_AB                True                 0.699670
                                   False                0.300330
C_positive_heart_CAD               True                 0.939394
                                   False                0.060606
C_positive_heart_MK                True                 0.907216
                                   False                0.092784
C_positive_neuron_CD               True                 0.765957
                                   False                0.234043
C_positive_neuron_MK               True                 0.968750
                                   False                0.031250
C_positive_neuron_NP               True                 0.757576
                                   False                0.242424
GC_Atrial_fib                      True                 0.977778
                                   False                0.022222
GC_Cort_Chengyu                    True                 1.000000
GC_DNase_negative_blood            True                 1.000000
GC_DNase_negative_blood_shuffeled  True                 0.947368
                                   False                0.052632
GC_DNase_negative_brain            True                 1.000000
GC_DNase_negative_brain_shuffeled  True                 1.000000
GC_DNase_positive                  True                 0.926829
                                   False                0.073171
GC_DNase_positive_shuffeled        True                 0.927273
                                   False                0.072727
GC_GABA_Chengyu                    True                 0.857143
                                   False                0.142857
GC_Glut_Chengyu                    True                 1.000000
GC_Hon                             True                 0.666667
                                   False                0.333333
GC_Kircher                         True                 0.955665
                                   False                0.044335
GC_Liang                           True                 0.875000
                                   False                0.125000
GC_Mendelian_variants              True                 0.966507
                                   False                0.033493
GC_Mohlke                          True                 0.894737
                                   False                0.105263
GC_Selvarajan                      True                 0.913408
                                   False                0.086592
GC_Vista                           True                 0.906250
                                   False                0.093750
MK                                 True                 0.882770
                                   False                0.117230
cardiac_neuro_cava_random          True                 0.912984
                                   False                0.087016
Name: proportion, dtype: float64

In [36]:
mpra_80k_metadata_df_bcalm

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,bcalm_element_adjusted_p_value,bcalm_element_log_ratio_activity,bcalm_data_exists,label
0,GC_Mohlke:REF_NC000001.11|159752292|A|G|Mohlke...,ATACATCCTTTAATTTGTTCCTACATCTTGCTTGGATTTTCCCCTG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,159752058.0,159752328.0,+,[SNV],[234],[NC_000001.11:159752292:A:G],[ref],NaN,9.999956e-01,-0.020027,True,GC_Mohlke
1,GC_Mohlke:REF_NC000001.11|230158967|C|A|Mohlke...,TGTGTCTGGTGAGGTTGCTGACACTGCTTTTGGATGAGAGAGAGAG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159023.0,230159293.0,+,[SNV],[145],[NC_000001.11:230159168:C:T],[ref],NaN,9.999956e-01,0.023176,True,GC_Mohlke
2,GC_Mohlke:REF_NC000001.11|230158967|C|A|Mohlke...,GTTTACCCAGCCGTGGGAAAGGACGCTGTACCCCTGCCCTATTGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159136.0,230159406.0,+,"[SNV, indel]","[32, 192]","[NC_000001.11:230159168:C:T, NC_000001.11:2301...","[ref, ref]",NaN,9.981770e-01,0.024018,True,GC_Mohlke
3,GC_Mohlke:ALT_NC000001.11|230158967|C|A|Mohlke...,GTTTACCCAGCCGTGGGAAAGGACGCTGTACCCCTGCCCTATTGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159136.0,230159406.0,+,[indel],[192],[NC_000001.11:230159328:TCTTAAAGTGTTCAGCACTCCC:T],[alt],NaN,9.999956e-01,0.008198,True,GC_Mohlke
4,GC_Mohlke:REF_NC000001.11|230161389|C|T|Mohlke...,CCTCAACTCTCCACATGCCCCAGTAGCATAGACCAGCTTCCTTACA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230161269.0,230161539.0,+,[SNV],[120],[NC_000001.11:230161389:C:T],[ref],NaN,9.999956e-01,-0.004509,True,GC_Mohlke
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80210,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element inactive control,NaN,GRCh38,chr12,44940898.0,44941168.0,-,None,None,None,None,NaN,4.953820e-01,0.046730,True,GC_Glut_Chengyu
80211,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element inactive control,NaN,GRCh38,chr2,212699380.0,212699650.0,+,None,None,None,None,NaN,4.624852e-04,0.076623,True,GC_Glut_Chengyu
80212,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element inactive control,NaN,GRCh38,chr10,26798828.0,26799098.0,-,None,None,None,None,NaN,1.641763e-07,0.101881,True,GC_Glut_Chengyu
80213,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element inactive control,NaN,GRCh38,chr7,31260963.0,31261233.0,+,None,None,None,None,NaN,4.879882e-13,0.122765,True,GC_Glut_Chengyu
80214,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element inactive control,NaN,GRCh38,chr12,44688247.0,44688517.0,-,None,None,None,None,NaN,2.124781e-11,0.126462,True,GC_Glut_Chengyu

In [37]:
# TODO: add scramble normalization

# get all scramble sequences (for the value normalization)

containing_scrambl = mpra_80k_metadata_df_bcalm.loc[mpra_80k_metadata_df_bcalm['name'].str.contains("scrambl")].copy()
containing_scrambl_bcalm = containing_scrambl.loc[containing_scrambl["bcalm_data_exists"]].copy()

# containing_negative_neuron = mpra_80k_metadata_df_bcalm.loc[mpra_80k_metadata_df_bcalm['name'].str.contains("negative_neuron")].copy()
# containing_negative_neuron_bcalm = containing_negative_neuron.loc[containing_negative_neuron["bcalm_data_exists"]].copy()

In [38]:
import numpy as np
# # change the logfc to be shifted over the negative neuron controls
# mpra_80k_metadata_df_bcalm["not_shifted_bcalm_element_log_ratio_activity"] = mpra_80k_metadata_df_bcalm["bcalm_element_log_ratio_activity"]
# mu_ref_neg_ctrl = containing_negative_neuron_bcalm['bcalm_element_log_ratio_activity'].median()
# sigma_ref_neg_ctrl = np.sqrt(containing_negative_neuron_bcalm['bcalm_element_log_ratio_activity'].var())

# mpra_80k_metadata_df_bcalm['bcalm_element_log_ratio_activity_z_score_neg_ctrl'] = (mpra_80k_metadata_df_bcalm['bcalm_element_log_ratio_activity'] - mu_ref_neg_ctrl) / sigma_ref_neg_ctrl

In [39]:
mu_ref_scrambled_ctrl = containing_scrambl_bcalm['bcalm_element_log_ratio_activity'].median()
sigma_ref_scrambled_ctrl = np.sqrt(containing_scrambl_bcalm['bcalm_element_log_ratio_activity'].var()) #

mpra_80k_metadata_df_bcalm['bcalm_element_log_ratio_activity_z_score_scrambled_ctrl'] = (mpra_80k_metadata_df_bcalm['bcalm_element_log_ratio_activity'] - mu_ref_scrambled_ctrl) / sigma_ref_scrambled_ctrl

In [45]:
write_output

True

In [41]:
output_elements

'undiffWTC11_element_metadata_with_bcalm_2025_05_bbmap_normalized_counts_scrambled_075'

In [44]:
config['files']['creating'][output_elements]

'/home/kisa/coding/80K_MPRA/element_analysis_output/202502_element_analysis/undiffWTC11_element_metadata_with_bcalm_2025_05_bbmap_normalized_counts_pvalue_log2_zscore_scrambled_not_neuro_ctrl_075.tsv.gz'

In [46]:
if write_output:
    # mpra_80k_metadata_df_bcalm.to_csv(config['files']['creating'][output_elements], sep="\t", index=False, compression='gzip')
    mpra_80k_metadata_df_bcalm.to_csv(config['files']['creating'][output_elements], sep="\t", index=False, compression='gzip')

In [25]:
config['files']['creating'][output_elements]

'/home/kisa/coding/80K_MPRA/element_analysis_output/202502_element_analysis/undiffWTC11_element_metadata_with_bcalm_2025_05_bbmap_normalized_counts_pvalue_log2_zscore_scrambled_log2_not_neuro_ctrl.tsv.gz'

In [15]:
mpra_80k_metadata_df_bcalm.columns

Index(['name', 'sequence', 'category', 'class', 'source', 'ref', 'chr',
       'start', 'end', 'strand', 'variant_class', 'variant_pos', 'SPDI',
       'allele', 'info', 'bcalm_element_adjusted_p_value',
       'bcalm_element_log_ratio_activity', 'bcalm_data_exists', 'label'],
      dtype='object')

In [16]:
mpra_80k_metadata_df_bcalm

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,bcalm_element_adjusted_p_value,bcalm_element_log_ratio_activity,bcalm_data_exists,label
0,GC_Mohlke:REF_NC000001.11|159752292|A|G|Mohlke...,ATACATCCTTTAATTTGTTCCTACATCTTGCTTGGATTTTCCCCTG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,159752058.0,159752328.0,+,[SNV],[234],[NC_000001.11:159752292:A:G],[ref],NaN,1.000000e+00,0.002170,True,GC_Mohlke
1,GC_Mohlke:REF_NC000001.11|230158967|C|A|Mohlke...,TGTGTCTGGTGAGGTTGCTGACACTGCTTTTGGATGAGAGAGAGAG...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159023.0,230159293.0,+,[SNV],[145],[NC_000001.11:230159168:C:T],[ref],NaN,1.000000e+00,-0.005898,True,GC_Mohlke
2,GC_Mohlke:REF_NC000001.11|230158967|C|A|Mohlke...,GTTTACCCAGCCGTGGGAAAGGACGCTGTACCCCTGCCCTATTGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159136.0,230159406.0,+,"[SNV, indel]","[32, 192]","[NC_000001.11:230159168:C:T, NC_000001.11:2301...","[ref, ref]",NaN,1.000000e+00,0.005348,True,GC_Mohlke
3,GC_Mohlke:ALT_NC000001.11|230158967|C|A|Mohlke...,GTTTACCCAGCCGTGGGAAAGGACGCTGTACCCCTGCCCTATTGGC...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230159136.0,230159406.0,+,[indel],[192],[NC_000001.11:230159328:TCTTAAAGTGTTCAGCACTCCC:T],[alt],NaN,1.000000e+00,-0.007093,True,GC_Mohlke
4,GC_Mohlke:REF_NC000001.11|230161389|C|T|Mohlke...,CCTCAACTCTCCACATGCCCCAGTAGCATAGACCAGCTTCCTTACA...,variant,variant negative control,general controls IGVF year 1 design 2023,GRCh38,chr1,230161269.0,230161539.0,+,[SNV],[120],[NC_000001.11:230161389:C:T],[ref],NaN,1.332728e-33,0.184521,True,GC_Mohlke
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80210,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element inactive control,NaN,GRCh38,chr12,44940898.0,44941168.0,-,None,None,None,None,NaN,1.000000e+00,-0.007241,True,GC_Glut_Chengyu
80211,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element inactive control,NaN,GRCh38,chr2,212699380.0,212699650.0,+,None,None,None,None,NaN,1.000000e+00,0.030434,True,GC_Glut_Chengyu
80212,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element inactive control,NaN,GRCh38,chr10,26798828.0,26799098.0,-,None,None,None,None,NaN,1.614862e-02,0.051942,True,GC_Glut_Chengyu
80213,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element inactive control,NaN,GRCh38,chr7,31260963.0,31261233.0,+,None,None,None,None,NaN,9.615387e-01,0.039459,True,GC_Glut_Chengyu
80214,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element inactive control,NaN,GRCh38,chr12,44688247.0,44688517.0,-,None,None,None,None,NaN,5.593827e-05,0.059866,True,GC_Glut_Chengyu

### Variant + bcalm ref, alt + sequences + coordinates 
- start from variant map with REF_seq, ALT_seq, REF_log_ratio_activity, ALT_log_ratio_activity, genomic_coordinates (chr, start, end), variant_position_in_string, bcalm_variant_effect, bcalm_variant_adjusted_p_value

In [17]:
variant_bcalm_df = pd.read_csv(bcalm_variant_results, sep="\t")
variant_bcalm_df

,logFC,AveExpr,t,P.Value,adj.P.Val,B,variant_id
0,1.443816,1.710741,23.571468,1.673005e-97,6.388034e-93,210.124431,cardiac_neuro_cava_random:ALT_TRIO|ENSG0000003...
1,1.389350,0.792320,18.609988,2.837799e-64,5.417784e-60,134.228897,cardiac_neuro_cava_random:ALT_TRIO|ENSG0000003...
2,-1.151234,0.917228,-17.499561,1.665878e-59,2.120274e-55,123.872987,cardiac_neuro_cava_random:ALT_DISC1|ENSG000001...
3,1.457050,0.773629,17.035695,1.317082e-54,1.257254e-50,112.066372,cardiac_neuro_cava_random:ALT_ANKZF1|ENSG00000...
4,0.806098,0.806494,14.790474,1.444289e-45,1.102946e-41,92.620300,cardiac_neuro_cava_random:ALT_ATR|ENSG00000175...
...,...,...,...,...,...,...,...
38178,-0.000300,-0.057601,-0.005550,9.955727e-01,9.991768e-01,-7.025549,cardiac_neuro_cava_random:ALT_CDK19|ENSG000001...
38179,0.000220,0.261966,0.004238,9.966195e-01,9.992879e-01,-7.025550,cardiac_neuro_cava_random:ALT_DMD|ENSG00000198...
38180,-0.000016,-0.245342,-0.000291,9.997676e-01,9.999247e-01,-7.025565,cardiac_neuro_cava_random:ALT_ATM|ENSG00000149...
38181,-0.000193,-0.035310,-0.003647,9.970904e-01,9.994609e-01,-7.025566,cardiac_neuro_cava_random:ALT_FOXP1|ENSG000001...
38182,-0.000161,0.211663,-0.003152,9.974858e-01,9.994609e-01,-7.025572,cardiac_neuro_cava_random:ALT_TRIP12|ENSG00000...

In [104]:
# Varianten + REF_sequenz, ALT_sequenz, REF_log_ratio_activity, ALT_log_ratio_activity, genomic_coordinates (chr, start, end), variant_position_in_string, bcalm_variant_effect, bcalm_variant_adjusted_p_value

In [18]:
mpra_80k_metadata_df_bcalm_tested = mpra_80k_metadata_df_bcalm.loc[mpra_80k_metadata_df_bcalm['label'] == "cardiac_neuro_cava_random"].copy()
mpra_80k_metadata_df_bcalm_tested[col_name].str.contains(',').sum()
mpra_80k_metadata_df_bcalm_tested[col_name] = mpra_80k_metadata_df_bcalm_tested[col_name].apply(lambda name: name.replace(",", "~") if "cardiac_neuro_cava_random" in name else name)
mpra_80k_metadata_df_bcalm_tested['gene_name'] = mpra_80k_metadata_df_bcalm_tested[col_name].apply(hf.get_gene_name)

In [19]:
mpra_80k_metadata_df_bcalm_tested.columns

Index(['name', 'sequence', 'category', 'class', 'source', 'ref', 'chr',
       'start', 'end', 'strand', 'variant_class', 'variant_pos', 'SPDI',
       'allele', 'info', 'bcalm_element_adjusted_p_value',
       'bcalm_element_log_ratio_activity', 'bcalm_data_exists', 'label',
       'gene_name'],
      dtype='object')

In [20]:
len(mpra_80k_metadata_df_bcalm_tested['gene_name'].unique())

525

In [21]:
element_genes_set = set(mpra_80k_metadata_df_bcalm_tested['gene_name'].unique())

In [22]:
variant_map_df = pd.read_csv(variant_map, sep="\t")

In [23]:
# rename the once which have "," in the header
variant_map_df['ID'].str.contains("~").sum()
variant_map_df['REF'].str.contains("~").sum()
variant_map_df['ALT'].str.contains("~").sum()

1663

In [24]:
variant_map_df

,ID,REF,ALT
0,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
1,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
2,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...
...,...,...,...
47039,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618
47040,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757
47041,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373
47042,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656
47043,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666

In [ ]:
# add alt sequences and ref sequences to the variant map from the metadata
variant_map_df = pd.read_csv(variant_map, sep="\t")
variant_map_df_seqs = variant_map_df.merge(mpra_80k_metadata_df[[col_name, col_sequence]], left_on="REF", right_on=col_name, how='left')
# rename col_sequence to "ref_sequence"
variant_map_df_seqs = variant_map_df_seqs.rename(columns={col_sequence: "ref_sequence"})
variant_map_df_seqs = variant_map_df_seqs.drop(columns=[col_name])
variant_map_df_seqs = variant_map_df_seqs.merge(mpra_80k_metadata_df[[col_name, col_sequence, col_variant_pos]], left_on="ALT", right_on=col_name, how='left')
variant_map_df_seqs = variant_map_df_seqs.rename(columns={col_sequence: "alt_sequence"})
variant_map_df_seqs = variant_map_df_seqs.drop(columns=[col_name])
variant_map_df_seqs = variant_map_df_seqs.merge(variant_bcalm_df[['variant_id', 'adj.P.Val', 'logFC']], left_on="ID", right_on="variant_id", how='left')

variant_map_df_seqs['bcalm_variant_effect_data_exists'] = variant_map_df_seqs['variant_id'].notna()
variant_map_df_seqs.drop(columns=['variant_id'], inplace=True)
variant_map_df_seqs.rename(columns={'adj.P.Val': 'bcalm_variant_effect_adjusted_p_value', 'logFC': 'bcalm_variant_effect_log_ratio_activity'}, inplace=True)
print("Number of variants without bcalm values: ", variant_map_df_seqs['bcalm_variant_effect_adjusted_p_value'].isna().sum()) # 8023
print("Number of variants with bcalm values: ", variant_map_df_seqs['bcalm_variant_effect_adjusted_p_value'].notna().sum()) # 39021

variant_map_df_seqs['label'] = variant_map_df_seqs['ID'].apply(hf.get_label)

normalized_counts = (
    variant_map_df_seqs
    .groupby("label")["bcalm_variant_effect_data_exists"]
    .value_counts(normalize=True)
)
print(normalized_counts)

# add the reference bcalm result
variant_map_df_seqs = variant_map_df_seqs.merge(bcalm_element_df[[col_name, 'adj.P.Val', 'logFC']], left_on='REF', right_on=col_name, how='left')
variant_map_df_seqs.rename(columns={'adj.P.Val': 'bcalm_reference_adjusted_p_value', 'logFC': 'bcalm_reference_log_ratio_activity'}, inplace=True)
variant_map_df_seqs = variant_map_df_seqs.drop(columns=[col_name])

# add the alternative bcalm result
variant_map_df_seqs = variant_map_df_seqs.merge(bcalm_element_df[[col_name, 'adj.P.Val', 'logFC']], left_on='ALT', right_on=col_name, how='left')
variant_map_df_seqs.rename(columns={'adj.P.Val': 'bcalm_alternative_adjusted_p_value', 'logFC': 'bcalm_alternative_log_ratio_activity'}, inplace=True)
variant_map_df_seqs = variant_map_df_seqs.drop(columns=[col_name])
variant_map_df_seqs

# NGN2 no outlier detection:
# Number of variants without bcalm values:  8861
# Number of variants with bcalm values:  38183

Number of variants without bcalm values:  8861
Number of variants with bcalm values:  38183
label                      bcalm_variant_effect_data_exists
C_positive_heart_CAD       True                                0.857143
                           False                               0.142857
GC_Atrial_fib              True                                0.652174
                           False                               0.347826
GC_Kircher                 False                               1.000000
GC_Liang                   True                                0.750000
                           False                               0.250000
GC_Mendelian_variants      True                                0.827586
                           False                               0.172414
GC_Mohlke                  False                               0.500000
                           True                                0.500000
GC_Selvarajan              False                               0.515152
                           True                                0.484848
cardiac_neuro_cava_random  True                                0.816621
                           False                               0.183379
Name: proportion, dtype: float64

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_variant_effect_data_exists,label,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity
0,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GTCCCAGCTCCCCACTGATGTGAAAGGTGGTGGTGAGTTAACAGCT...,GTCCCAGCTCCCCACTGATGTGAAAGGTGGTGGTGAGTTAACAGCT...,[83],NaN,NaN,False,cardiac_neuro_cava_random,0.022133,0.131536,5.965362e-07,0.190591
1,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTGATCTGCCCTGTCCGTGACGCTTCTGCTCAGTAGCTGAGCACG...,CCTGATCTGCCCTGTCCGTGACGCTTCTGCTCAGTAGCTGAGCACG...,[181],NaN,NaN,False,cardiac_neuro_cava_random,NaN,NaN,NaN,NaN
2,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCTGGGTGACCCGGAGAACACCAAGGCTGTGAGAAATGGGAGGC...,CCTCTGGGTGACCCGGAGAACACCAAGGCTGTGAGAAATGGGATGC...,[43],NaN,NaN,False,cardiac_neuro_cava_random,NaN,NaN,NaN,NaN
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,[116],0.944787,-0.043372,True,cardiac_neuro_cava_random,1.000000,-0.068107,1.000000e+00,-0.072051
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,[205],0.926799,-0.036392,True,cardiac_neuro_cava_random,1.000000,0.001944,1.000000e+00,-0.005889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47039,C_positive_heart_CAD:ALT_rs7865618_rs7865618,C_positive_heart_CAD:REF_rs7865618,C_positive_heart_CAD:ALT_rs7865618_rs7865618,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,TATTGATAACAGGGGATGGATTCTTGTGGACAAAAAAATTTAGAAT...,[136],0.069025,0.177548,True,C_positive_heart_CAD,1.000000,-0.037515,1.000000e+00,-0.012714
47040,C_positive_heart_CAD:ALT_rs4977757_rs4977757,C_positive_heart_CAD:REF_rs4977757,C_positive_heart_CAD:ALT_rs4977757_rs4977757,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,CTGATGGGCTTCCCTTTGTGGGTAACCCGACCTTTCTCTCTGGCTG...,[136],0.220035,-0.313776,True,C_positive_heart_CAD,0.042527,-0.087468,7.038279e-05,-0.102879
47041,C_positive_heart_CAD:ALT_rs1537373_rs1537373,C_positive_heart_CAD:REF_rs1537373,C_positive_heart_CAD:ALT_rs1537373_rs1537373,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,AGAAAACCATACCCACTTTCCCACATATCCCAACTATGACTGGGCA...,[136],0.341678,0.214433,True,C_positive_heart_CAD,1.000000,-0.027086,1.000000e+00,0.002929
47042,C_positive_heart_CAD:ALT_rs10811656_rs10811656,C_positive_heart_CAD:REF_rs10811656,C_positive_heart_CAD:ALT_rs10811656_rs10811656,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,AAATTAAAAGCTTCTAAACTAACAAACAGCCAATTTGTGGAGTGTC...,[136],0.775080,0.089574,True,C_positive_heart_CAD,1.000000,-0.070829,1.000000e+00,-0.067582
47043,C_positive_heart_CAD:ALT_rs507666_rs507666,C_positive_heart_CAD:REF_rs507666,C_positive_heart_CAD:ALT_rs507666_rs507666,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,ATTAAGACAAAAAAGGGAAAACAAAGACCACAAAGGAGGGACAGGG...,[136],0.829395,-0.099302,True,C_positive_heart_CAD,1.000000,0.018869,1.000000e+00,0.002536

#### Create gene list with the number of significant variants per gene

In [26]:
variant_map_df_seqs_tested = variant_map_df_seqs.loc[variant_map_df_seqs['label'] == "cardiac_neuro_cava_random"].copy()
variant_map_df_seqs_tested['gene_name'] = variant_map_df_seqs_tested["ID"].apply(hf.get_gene_name)
len(variant_map_df_seqs_tested['gene_name'].unique())
variant_map_df_seqs_tested['gene_name'].unique()
element_genes_set
variant_genes_set = set(variant_map_df_seqs_tested['gene_name'].unique())

In [27]:
element_genes_set - variant_genes_set

{'NRAS'}

In [28]:
gene_df_80k = pd.DataFrame({'gene_name': mpra_80k_metadata_df_bcalm_tested['gene_name'].unique()})
gene_df_80k['designed_variants_for_gene'] = gene_df_80k['gene_name'].isin(variant_genes_set)

# add significant variants per gene
significant_variant_map_df_seqs_tested = variant_map_df_seqs_tested.loc[variant_map_df_seqs_tested['bcalm_variant_effect_adjusted_p_value'] < 0.1].copy()
n_significant_variants_per_gene_table = significant_variant_map_df_seqs_tested['gene_name'].value_counts().reset_index(name="n_significant_variants_associated_to_gene")

gene_df_80k = gene_df_80k.merge(n_significant_variants_per_gene_table, on='gene_name', how='left').fillna(0)
gene_df_80k['n_significant_variants_associated_to_gene'] = gene_df_80k['n_significant_variants_associated_to_gene'].astype(int)

In [29]:
gene_df_80k

,gene_name,designed_variants_for_gene,n_significant_variants_associated_to_gene
0,SKI,True,3
1,PRDM16,True,10
2,PLEKHM2,True,1
3,SZT2,True,2
4,ST3GAL3,True,1
...,...,...,...
520,SLC5A1,True,1
521,CYP2D6,True,3
522,CFAP91,True,1
523,RINT1,True,1
524,CHRM2,True,0

In [30]:
gene_list_out = "/home/kisa/coding/80K_MPRA/design_data/design_info/all_genes_designed.csv"
gene_df_80k.to_csv(gene_list_out, sep="\t", index=False)

In [31]:
variant_map_df_seqs.columns

Index(['ID', 'REF', 'ALT', 'ref_sequence', 'alt_sequence', 'variant_pos',
       'bcalm_variant_effect_adjusted_p_value',
       'bcalm_variant_effect_log_ratio_activity',
       'bcalm_variant_effect_data_exists', 'label',
       'bcalm_reference_adjusted_p_value',
       'bcalm_reference_log_ratio_activity',
       'bcalm_alternative_adjusted_p_value',
       'bcalm_alternative_log_ratio_activity'],
      dtype='object')

In [32]:
interesting_variant_columns = ['ID', 'REF', 'ALT', 'ref_sequence', 'alt_sequence', 'variant_pos', 'bcalm_variant_effect_data_exists',
'bcalm_variant_effect_adjusted_p_value',
'bcalm_variant_effect_log_ratio_activity',
'bcalm_reference_adjusted_p_value',
'bcalm_reference_log_ratio_activity',
'bcalm_alternative_adjusted_p_value',
'bcalm_alternative_log_ratio_activity', 'label']

In [33]:
variant_map_df_seqs.head()

,ID,REF,ALT,ref_sequence,alt_sequence,variant_pos,bcalm_variant_effect_adjusted_p_value,bcalm_variant_effect_log_ratio_activity,bcalm_variant_effect_data_exists,label,bcalm_reference_adjusted_p_value,bcalm_reference_log_ratio_activity,bcalm_alternative_adjusted_p_value,bcalm_alternative_log_ratio_activity
0,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GTCCCAGCTCCCCACTGATGTGAAAGGTGGTGGTGAGTTAACAGCT...,GTCCCAGCTCCCCACTGATGTGAAAGGTGGTGGTGAGTTAACAGCT...,[83],NaN,NaN,False,cardiac_neuro_cava_random,0.022133,0.131536,5.965362e-07,0.190591
1,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTGATCTGCCCTGTCCGTGACGCTTCTGCTCAGTAGCTGAGCACG...,CCTGATCTGCCCTGTCCGTGACGCTTCTGCTCAGTAGCTGAGCACG...,[181],NaN,NaN,False,cardiac_neuro_cava_random,NaN,NaN,NaN,NaN
2,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCTCTGGGTGACCCGGAGAACACCAAGGCTGTGAGAAATGGGAGGC...,CCTCTGGGTGACCCGGAGAACACCAAGGCTGTGAGAAATGGGATGC...,[43],NaN,NaN,False,cardiac_neuro_cava_random,NaN,NaN,NaN,NaN
3,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,CCATGCGGTGGCCACAGCCTCGGGTGAGTTCCGGTTCCAAAGTACC...,[116],0.944787,-0.043372,True,cardiac_neuro_cava_random,1.000000,-0.068107,1.000000e+00,-0.072051
4,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,cardiac_neuro_cava_random:REF_SKI|ENSG00000157...,cardiac_neuro_cava_random:ALT_SKI|ENSG00000157...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,GGACTCCGGTGCCTTCGCATTCCCGAGCTGTTTTTGCTTCTGGAAG...,[205],0.926799,-0.036392,True,cardiac_neuro_cava_random,1.000000,0.001944,1.000000e+00,-0.005889

In [38]:
if write_output:
    variant_map_df_seqs[interesting_variant_columns].to_csv(config['files']['creating'][output_variants], sep="\t", index=False, compression='gzip')

In [122]:
variant_map_df_seqs.columns

Index(['ID', 'REF', 'ALT', 'ref_sequence', 'alt_sequence', 'variant_pos',
       'bcalm_variant_effect_adjusted_p_value',
       'bcalm_variant_effect_log_ratio_activity',
       'bcalm_variant_effect_data_exists', 'label',
       'bcalm_reference_adjusted_p_value',
       'bcalm_reference_log_ratio_activity',
       'bcalm_alternative_adjusted_p_value',
       'bcalm_alternative_log_ratio_activity'],
      dtype='object')

In [123]:
# Was ich dir jetzt probiere vorzubereiten ist dieses File + die daten von bcalm für die elemente und dann ein zweites File mit den Varianten + REF_sequenz, ALT_sequenz, REF_log_ratio_activity, ALT_log_ratio_activity, genomic_coordinates (chr, start, end), variant_position_in_string, bcalm_variant_effect, bcalm_variant_adjusted_p_value. Habe ich etwas vergessen?

### Get the numbers from design to bcalm
- bwa: 
    - Number of alternative sequences in design:  46458
    - Number of alternative sequences with bcalm:  40939
    - Number of alternatives without info:  5519
    - Ratio of sequences with info:  0.8812045288217315
- bbmap: 
    - ALT: 
    - Number of alternative sequences in design:  46458
    - Number of alternative sequences with bcalm:  39808
    - Number of alternatives without info:  6650
    - Ratio of sequences with info:  0.8568599595333419
    - ELEMENTS: 
    - Number of element sequences in design:  27482
    - Number of element sequences with bcalm:  24234
    - Number of elements without info:  3248
    - Ratio of sequences with info:  0.8818135506877228
    - CONTROLS:
    - Number of control sequences in design:  6275
    - Number of control sequences with bcalm:  5051
    - Number of controls without info:  1224
    - Ratio of sequences with info:  0.8049402390438247
- get number of elements and variants in design
- get numbers of elements and variants with bcalm information 
- calculate numbers of missing 
- get numbers of controls in design 
- get number of controls with bcalm information
- calculate numbers of missing

In [124]:
element_bcalm_metadata_df = pd.read_csv(config['files']['creating'][output_elements], low_memory=False, sep="\t")

# list columns col_variant_class, col_variant_pos, col_SPDI, col_allele
list_columns = [col_variant_class, col_variant_pos, col_SPDI, col_allele]

# Apply the safe_eval function to the specified columns
for col in list_columns:
    element_bcalm_metadata_df[col] = element_bcalm_metadata_df[col].apply(safe_eval)

In [125]:
config['files']['creating'][output_elements]

'/home/kisa/coding/80K_MPRA/element_analysis_output/202502_element_analysis/WTC11_element_metadata_with_bcalm_2025_02_bbmap_vs_scrambled.tsv.gz'

In [126]:
element_bcalm_metadata_df

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,bcalm_element_adjusted_p_value,bcalm_element_log_ratio_activity,bcalm_data_exists,label
0,MK:rdhs_664198|chr8-10365156+10365425|reference,AAAAAAAAAGTCGAGACTGGAAGAAGCAAACTTTCAGCTAATTATC...,variant,element active control,Michael Kosicki,GRCh38,chr8,10365155.0,10365425.0,+,"[SNV, SNV, SNV, SNV, SNV, SNV, indel, indel, i...","[20, 252, 20, 252, 36, 36, 17, 249, 33]",None,"[ref, ref, ref, ref, ref, ref, ref, ref, ref]",NaN,0.999945,0.212246,True,MK
1,MK:tile_47691|chr20-20492859+20493129|reference,AAAAAAAATTTGCAAATCATTGCCTGGTTGCCAAGCAGGGAGATAA...,variant,element active control,Michael Kosicki,GRCh38,chr20,20492858.0,20493129.0,+,[SNV],[40],None,[ref],NaN,0.999945,-0.038314,True,MK
2,MK:tile_47699|chr22-42282878+42283148|reference,AAAAAGGGAGGGCCAAATAAAGCCCCACGCCGCCCAGCACGGGCTC...,variant,element active control,Michael Kosicki,GRCh38,chr22,42282877.0,42283148.0,+,[SNV],[172],None,[ref],NaN,0.999945,0.258518,True,MK
3,MK:tile_38401|chr7-1226231+1226500|reference,AAAACTATTAGACGACAGGCGGATGTGCTACTAAAACTCTTGGTTA...,variant,element active control,Michael Kosicki,GRCh38,chr7,1226230.0,1226500.0,+,"[SNV, SNV, SNV, SNV, indel, indel]","[84, 84, 248, 248, 245, 81]",None,"[ref, ref, ref, ref, ref, ref]",NaN,0.999945,-0.113640,True,MK
4,MK:tile_47638|chr16-52435608+52435878|reference,AAAAGCCACCCCAGCTCTCCACTTTCCCATCCGATTCTAGTAGGTC...,variant,element active control,Michael Kosicki,GRCh38,chr16,52435607.0,52435878.0,+,[SNV],[0],None,[ref],NaN,0.999945,0.356566,True,MK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80191,GC_Glut_Chengyu:Glut|chr12:44940899-44941168|-...,TGTCCAAAAAAAGTAAAAGTCATAACAGAAATTGGATTTCAAATGG...,element,element active control,NaN,GRCh38,chr12,44940898.0,44941168.0,-,None,None,None,None,NaN,0.999945,0.400228,True,GC_Glut_Chengyu
80192,GC_Glut_Chengyu:Glut|chr2:212699381-212699650|...,TGTGAGTGCTATAATTGTAACCCTTTATAATTGACAGACATTAATT...,element,element active control,NaN,GRCh38,chr2,212699380.0,212699650.0,+,None,None,None,None,NaN,0.999945,0.420121,True,GC_Glut_Chengyu
80193,GC_Glut_Chengyu:Glut|chr10:26798829-26799098|-...,TTTAATAGGAGTACTATTGAATTTACATTTAATGTAGTTAATGATA...,element,element active control,NaN,GRCh38,chr10,26798828.0,26799098.0,-,None,None,None,None,NaN,0.999945,0.199611,True,GC_Glut_Chengyu
80194,GC_Glut_Chengyu:Glut|chr7:31260964-31261233|+|...,TTTCTTATACTGTATGTTTAAAGATATAGACAATGCATATACAAGT...,element,element active control,NaN,GRCh38,chr7,31260963.0,31261233.0,+,None,None,None,None,NaN,0.999945,0.481224,True,GC_Glut_Chengyu
80195,GC_Glut_Chengyu:Glut|chr12:44688248-44688517|-...,TTTTTCTTATGAGGTTGTTAGGGAAGCAAAGATTAAGTACGATTAA...,element,element active control,NaN,GRCh38,chr12,44688247.0,44688517.0,-,None,None,None,None,NaN,0.999945,0.452971,True,GC_Glut_Chengyu

In [127]:
element_bcalm_metadata_df_tested = element_bcalm_metadata_df.loc[element_bcalm_metadata_df[col_name].str.contains("cardiac_neuro_cava_random")]
element_bcalm_metadata_df_tested_no_alt = element_bcalm_metadata_df_tested.loc[~element_bcalm_metadata_df_tested[col_name].str.contains(":ALT_")]

In [128]:
element_bcalm_metadata_df_tested_alt = element_bcalm_metadata_df_tested.loc[element_bcalm_metadata_df_tested[col_name].str.contains(":ALT_")]
print("Number of alternative sequences in design: ", element_bcalm_metadata_df_tested_alt.shape[0])
print("Number of alternative sequences with bcalm: ", element_bcalm_metadata_df_tested_alt.loc[element_bcalm_metadata_df_tested_alt['bcalm_data_exists']].shape[0])
print("Number of alternatives without info: ", element_bcalm_metadata_df_tested_alt.shape[0]-element_bcalm_metadata_df_tested_alt.loc[element_bcalm_metadata_df_tested_alt['bcalm_data_exists']].shape[0])
print("Ratio of sequences with info: ", (element_bcalm_metadata_df_tested_alt.loc[element_bcalm_metadata_df_tested_alt['bcalm_data_exists']].shape[0]/element_bcalm_metadata_df_tested_alt.shape[0]))

Number of alternative sequences in design:  46458
Number of alternative sequences with bcalm:  23476
Number of alternatives without info:  22982
Ratio of sequences with info:  0.5053166300744759

In [129]:
element_bcalm_metadata_df_tested_no_alt # + 84 because of error in removing

,name,sequence,category,class,source,ref,chr,start,end,strand,variant_class,variant_pos,SPDI,allele,info,bcalm_element_adjusted_p_value,bcalm_element_log_ratio_activity,bcalm_data_exists,label
4964,cardiac_neuro_cava_random:SKI|ENSG00000157933....,AAGAATACAAGTAACTGATGAATGAAGGGGGCATCTTGTGTCCCCA...,element,test,NaN,GRCh38,chr1,2181843.0,2182113.0,+,None,None,None,None,NaN,NaN,NaN,False,cardiac_neuro_cava_random
4965,cardiac_neuro_cava_random:SKI|ENSG00000157933....,TTGGGTATGCTGCCCCCCAGCTGGCGGGGCACCGGGGACAGGCACA...,element,test,NaN,GRCh38,chr1,2182439.0,2182709.0,+,None,None,None,None,NaN,NaN,NaN,False,cardiac_neuro_cava_random
4966,cardiac_neuro_cava_random:SKI|ENSG00000157933....,ACGAGCAAGGGAATGAGAGAGAGTGGGTTAGAGAGTGAGTGAGCCA...,element,test,NaN,GRCh38,chr1,2182830.0,2183100.0,+,None,None,None,None,NaN,NaN,NaN,False,cardiac_neuro_cava_random
4967,cardiac_neuro_cava_random:SKI|ENSG00000157933....,CGTGGACACGCGTGATTGACCCTTTAACTGTATCCTTAACCACCGC...,element,test,NaN,GRCh38,chr1,2185027.0,2185297.0,+,None,None,None,None,NaN,NaN,NaN,False,cardiac_neuro_cava_random
4968,cardiac_neuro_cava_random:SKI|ENSG00000157933....,CCGGAGAGTCTCAGCTCCCGCAGCCCTAACAAACGACCACAGACCT...,element,test,NaN,GRCh38,chr1,2188389.0,2188659.0,+,None,None,None,None,NaN,NaN,NaN,False,cardiac_neuro_cava_random
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32525,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,ACCCCACTGCTGCACCAGATTGAGCTGGAGAAGCCCAAGCCCATCC...,variant,test,NaN,GRCh38,chrX,154531979.0,154532249.0,-,"[SNV, SNV, SNV, SNV]","[207, 152, 92, 35]","[NC_000023.11:154532041:C:G, NC_000023.11:1545...","[ref, ref, ref, ref]",NaN,NaN,NaN,False,cardiac_neuro_cava_random
32526,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,TTGCTGAGTAGTATCCGTTGTATGAATGCACAGTTTGCCGGGTCAC...,variant,test,NaN,GRCh38,chrX,154539055.0,154539325.0,-,"[SNV, SNV, SNV, SNV]","[148, 109, 84, 75]","[NC_000023.11:154539176:A:G, NC_000023.11:1545...","[ref, ref, ref, ref]",NaN,0.999945,-0.035912,True,cardiac_neuro_cava_random
32527,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,GGAGCTCTGCCTCACCCCACCTGGCCCCAATTGTCCAGCTTGTAGA...,variant,test,NaN,GRCh38,chrX,154545000.0,154545270.0,-,[SNV],[64],[NC_000023.11:154545205:A:G],[ref],NaN,NaN,NaN,False,cardiac_neuro_cava_random
32528,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,ATGTCTGAATTCACCTCCAAATAATGGGAAAACTCCTAGGTATATA...,variant,test,NaN,GRCh38,chrX,154549802.0,154550072.0,-,[SNV],[149],[NC_000023.11:154549922:T:G],[ref],NaN,NaN,NaN,False,cardiac_neuro_cava_random
32529,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,CCTCTGCCCTCCCTGGCTTCTTCCCCTGTCCCTCCTTTCCCTTCCC...,variant,test,NaN,GRCh38,chrX,154552145.0,154552415.0,-,"[SNV, SNV, SNV]","[126, 44, 42]","[NC_000023.11:154552288:C:T, NC_000023.11:1545...","[ref, ref, ref]",NaN,0.999945,0.644172,True,cardiac_neuro_cava_random

In [130]:
print("Number of element sequences in design: ", element_bcalm_metadata_df_tested_no_alt.shape[0])
print("Number of element sequences with bcalm: ", element_bcalm_metadata_df_tested_no_alt.loc[element_bcalm_metadata_df_tested_no_alt['bcalm_data_exists']].shape[0])
print("Number of elements without info: ", element_bcalm_metadata_df_tested_no_alt.shape[0]-element_bcalm_metadata_df_tested_no_alt.loc[element_bcalm_metadata_df_tested_no_alt['bcalm_data_exists']].shape[0])
print("Ratio of sequences with info: ", (element_bcalm_metadata_df_tested_no_alt.loc[element_bcalm_metadata_df_tested_no_alt['bcalm_data_exists']].shape[0]/element_bcalm_metadata_df_tested_no_alt.shape[0]))

Number of element sequences in design:  27482
Number of element sequences with bcalm:  14869
Number of elements without info:  12613
Ratio of sequences with info:  0.5410450476675642

In [131]:
# controls:
element_bcalm_metadata_df_controls = element_bcalm_metadata_df.loc[~element_bcalm_metadata_df[col_name].str.contains("cardiac_neuro_cava_random")]
print("Number of control sequences in design: ", element_bcalm_metadata_df_controls.shape[0])
print("Number of control sequences with bcalm: ", element_bcalm_metadata_df_controls.loc[element_bcalm_metadata_df_controls['bcalm_data_exists']].shape[0])
print("Number of controls without info: ", element_bcalm_metadata_df_controls.shape[0]-element_bcalm_metadata_df_controls.loc[element_bcalm_metadata_df_controls['bcalm_data_exists']].shape[0])
print("Ratio of sequences with info: ", (element_bcalm_metadata_df_controls.loc[element_bcalm_metadata_df_controls['bcalm_data_exists']].shape[0]/element_bcalm_metadata_df_controls.shape[0]))

Number of control sequences in design:  6256
Number of control sequences with bcalm:  2807
Number of controls without info:  3449
Ratio of sequences with info:  0.44868925831202044