## One location for the blat of all genomic sequences in design (regions + references)

In [2]:
import pandas as pd 
import yaml 

# import local module helpful functions as hf (/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/00_helpful_functions/helpful_functions.py)
import sys
sys.path.append("/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/00_helpful_functions")
import helpful_functions as hf

# # reload helpful_functions module
# import importlib
# importlib.reload(hf)


config_path = "/data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/global80K_config.yaml"
config_path = "../global80K_config.yaml"
# config_path = "/home/kisa/coding/80K_MPRA/80K-Analysis/global80K_config.yaml"
# load config file
with open(config_path, "r") as f:
    config = yaml.load(f, Loader=yaml.FullLoader)

In [3]:
# load design file
designd_sequences = hf.fasta_to_dataframe(config['files']['final_design']['design_fasta'])

### blat results from tested elements and sequences
- input for blat: /data/gpfs-1/users/kisa11_c/work/coding/80K_analysis/05_variant_region_list/tested_ref_and_elements_finished.fasta (all tested sequences (regions and references))

In [4]:
# bash commands to generate a tsv out of the psl file
# tail -n +6 blat_matched_file.psl > blat_result_without_header.tsv
file = '/data/cephfs-2/unmirrored/groups/ag-kircher/MPRA/kilian_projects/hg38/ncbi_dataset/data/GCF_000001405.26/blat_result_without_header.tsv'
# remove header

blat_result_df = pd.read_csv(file, sep='\t', header=None)

# add column names
blat_result_columns = ['match', 'mismatch', 'rep_match', 'Ns', 'Q_gap_count', 'Q_gap_bases', 'T_gap_count', 'T_gap_bases', 'strand', 'Q_name', 'Q_size', 'Q_start', 'Q_end', 'T_name', 'T_size', 'T_start', 'T_end', 'block_count', 'blockSizes', 'qStarts', 'tStarts']

blat_result_df.columns = blat_result_columns

blat_result_df
# filter: number of matches=270, 
perfect_matches = blat_result_df[blat_result_df['match'] == 270]
perfect_matches.shape # 28276
# filter for blockSizes = 270
perfect_matches = perfect_matches[perfect_matches['blockSizes'] == '270,']
perfect_matches.shape # 28236
# check all columns for unique values and did not find any suspecious values
perfect_matches.T_name.value_counts() # 0 
# filter for matches startwith "NC_" in T_name
perfect_matches = perfect_matches[perfect_matches['T_name'].str.startswith('NC_')]
perfect_matches.shape # 27482
perfect_matches.Q_name.nunique() # 27482

# get subset of interesting columns
interesting_blat_results = ['Q_name', 'match', 'strand', 'T_name', 'T_start', 'T_end']
interesting_blat_results

perfect_matches = perfect_matches[interesting_blat_results]
perfect_matches

,Q_name,match,strand,T_name,T_start,T_end
0,cardiac_neuro_cava_random:SKI|ENSG00000157933....,270,+,NC_000001.11,2181843,2182113
1,cardiac_neuro_cava_random:SKI|ENSG00000157933....,270,+,NC_000001.11,2182439,2182709
64,cardiac_neuro_cava_random:SKI|ENSG00000157933....,270,+,NC_000001.11,2182830,2183100
122,cardiac_neuro_cava_random:SKI|ENSG00000157933....,270,+,NC_000001.11,2185027,2185297
124,cardiac_neuro_cava_random:SKI|ENSG00000157933....,270,+,NC_000001.11,2188389,2188659
...,...,...,...,...,...,...
369505,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,270,-,NC_000023.11,154531979,154532249
369506,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,270,-,NC_000023.11,154539055,154539325
369507,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,270,-,NC_000023.11,154545000,154545270
369562,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,270,-,NC_000023.11,154549802,154550072
369612,cardiac_neuro_cava_random:REF_G6PD|ENSG0000016...,270,-,NC_000023.11,154552145,154552415

### Blat for control variants (tried to do all REF sequences)

In [5]:
# load blat results and check if only one perfect match of each sequence
header_names = ['match', 'mismatch', 'rep_match', 'Ns', 'Q_gap_count', 'Q_gap_bases', 'T_gap_count', 'T_gap_bases', 'strand', 'Q_name', 'Q_size', 'Q_start', 'Q_end', 'T_name', 'T_size', 'T_start', 'T_end', 'block_count', 'blockSizes', 'qStarts', 'tStarts']
path_to_blat_results = '/data/cephfs-2/unmirrored/groups/ag-kircher/MPRA/kilian_projects/hg38/ncbi_dataset/data/GCF_000001405.26/blat_variant_control_sequences_matched_file.tsv'
blat_results = pd.read_csv(path_to_blat_results, sep="\t", header=None)
blat_results.columns = header_names
blat_results

# filter: number of matches=270, 
perfect_matches = blat_results[blat_results['match'] == 270]
perfect_matches.shape # 314
# filter for blockSizes = 270
perfect_matches = perfect_matches[perfect_matches['blockSizes'] == '270,']
perfect_matches.shape # 311
# check all columns for unique values and did not find any suspecious values
perfect_matches.T_name.value_counts() # 0 
# filter for matches startwith "NC_" in T_name
perfect_matches = perfect_matches[perfect_matches['T_name'].str.startswith('NC_')]
perfect_matches.shape # 309
perfect_matches.Q_name.nunique() # 309

# get subset of interesting columns
interesting_blat_results = ['Q_name', 'match', 'strand', 'T_name', 'T_start', 'T_end']
interesting_blat_results

perfect_matches = perfect_matches[interesting_blat_results]
perfect_matches

,Q_name,match,strand,T_name,T_start,T_end
0,GC_Atrial_fib:REF_rs74541936|KCNN3|STARR-seq-A...,270,+,NC_000001.11,154813248,154813518
1,GC_Atrial_fib:REF_rs34292822|KCNN3|STARR-seq-A...,270,+,NC_000001.11,154839744,154840014
2,GC_Atrial_fib:REF_rs12754189|KCNN3|STARR-seq-A...,270,+,NC_000001.11,154840018,154840288
3,GC_Atrial_fib:REF_rs36088503|KCNN3|STARR-seq-A...,270,+,NC_000001.11,154840331,154840601
4,GC_Atrial_fib:REF_rs1218584|KCNN3|STARR-seq-AF...,270,+,NC_000001.11,154860467,154860737
...,...,...,...,...,...,...
5563,C_positive_heart_CAD:REF_rs7865618,270,+,NC_000009.12,22030870,22031140
5939,C_positive_heart_CAD:REF_rs4977757,270,+,NC_000009.12,22094195,22094465
6625,C_positive_heart_CAD:REF_rs1537373,270,+,NC_000009.12,22103206,22103476
6626,C_positive_heart_CAD:REF_rs10811656,270,+,NC_000009.12,22124337,22124607
6627,C_positive_heart_CAD:REF_rs507666,270,+,NC_000009.12,133273847,133274117